### ISSUE TITLE
Le et al citation update?

### ISSUE THREAD

**Issue by raybellwaves** [EpistasisLab/tpot#1007]
Curious is the citation for the Le et al (2019) paper needs to be updated as it looks like it has been put into a 2020 issue

https://epistasislab.github.io/tpot/citing/

https://academic.oup.com/bioinformatics/article/36/1/250/5511404

**Comment by weixuanfu** [comment]
Hmm, it looks right. We will update the citation.

**Comment by weixuanfu** [comment]
I closed this issue because it was fixed in master branch. Thank you for reporting it.
