### ISSUE TITLE
Custom scorer bug

### ISSUE THREAD

**Issue by manuchema** [EpistasisLab/tpot#1010]
Hello,

I am using TPOT and after several runs i am trying to give TPOT a custom scoring function. The problem iss i aalwayss end up with the error message :

> ValueError: Scoring function make_scorer(maximize_true_pos) looks like it is a metric function rather than a scikit-learn scorer. This scoring type was removed in version 0.11. Please update your custom scoring function.

I first thought i made something wrong but the problem is that i have the same result with the exemple code given in TPOT documentation . https://epistasislab.github.io/tpot/using/#scoring-functions

If you take the code and run it, iny my case in a jupyter notebook, that doesn't work (https://epistasislab.github.io/tpot/using/#scoring-functions) :

I was expecting that all should go ok and figure out what i made wrong but instead the same error raised.

![TPOT](https://user-images.githubusercontent.com/28356853/73307074-caac5d80-421d-11ea-9431-e43969e6b5f9.jpg)

Can someone tell me how to implement a scoring function that TPOT accepts, by the way updating the doc will be great.

Many thanks

**Comment by weixuanfu** [comment]
Could you please let me know what is the versions of TPOT and scikit-learn in your environment?

We recently updated TPOT for supporting new scoring API in scikit-learn v0.22. If both were not up-to-date, which may cause this error.

**Comment by weixuanfu** [comment]
I tested those codes in a Colab notebook (see this [link](https://colab.research.google.com/gist/weixuanfu/f1a0efb0be1f8e8b361df7a04033c9d4/issue1010.ipynb)) and this Error did not shown up.

**Comment by manuchema** [comment]
Hello,
Many thanks, for the quick answer. I confirm you that the problem was on my configuration with Anaconda Jupyter. Even after i updated Anaconda and Scikit-learn the latter was still remaining in version 0.21.

After a complete removal of Scikit-Learn and TPOT i reainstalled first Scikit-Learn and now the version is 0.22.1 and everything works fine as you showed it in the Colab.net notebook.

Again many thanks and sorry for my mistake 👍 

Regards

**Comment by weixuanfu** [comment]
No problem! I closed this issue and please feel free to reopen it if you have any other questions.
