### ISSUE TITLE
can't set up emulator

### ISSUE THREAD

**Issue by Guire9** [EpistasisLab/tpot#1011]
I am new to android studio and I am trying to set up my emulator, but no matter what I do when I run I try to run my emulator I get this error:  Emulator: Process finished with exit code 133 (interrupter by signal 5: SigTrap) 
I also get this. 
21:37	Emulator: Referenced from: /Users/max/Library/Android/sdk/emulator/lib64/qt/lib/libQt5WebEngineCoreAndroidEmu.5.12.1.dylib
21:37	Emulator: Reason: image not found
How do I fix this

**Comment by weixuanfu** [comment]
Hmm, is this a TPOT-related issue?
