### ISSUE TITLE
tutorials/Titanic_Kaggle.ipynb - missing generations argument

### ISSUE THREAD

**Issue by raybellwaves** [EpistasisLab/tpot#1012]
In https://github.com/EpistasisLab/tpot/blob/master/tutorials/Titanic_Kaggle.ipynb
It seems the supporting text for the `TPOTClassifier` says "An important TPOT parameter to set is the number of generations. Since our aim is to just illustrate the use of TPOT, we have set it to 5." However, when looking at the command it does not specify `generations`:
```
tpot = TPOTClassifier(verbosity=2, max_time_mins=2, max_eval_time_mins=0.04, population_size=40)
```
Does the text need to be changed?

**Comment by weixuanfu** [comment]
Hmm, nice catch. That is a error in docs. We will correct it.

**Comment by weixuanfu** [comment]
I fixed this error and closed this issue. Thanks again for this report.
