### ISSUE TITLE
Pickling failure for custom CV splitter

### ISSUE THREAD

**Issue by adriangb** [EpistasisLab/tpot#1017]
Working:
```python3
from tpot import TPOTClassifier
from sklearn.model_selection import LeaveOneGroupOut
import numpy as np


X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 1, 2])
groups = np.array([1, 1, 2, 2])

logo = list(LeaveOneGroupOut().split(X=X, y=y, groups=groups))

t = TPOTClassifier(verbosity=2, max_time_mins=1, n_jobs=-1, cv=logo)
t.fit(features=X, target=y)
```

Not working:
```python3
logo = LeaveOneGroupOut().split(X=X, y=y, groups=groups)

t = TPOTClassifier(verbosity=2, max_time_mins=1, n_jobs=-1, cv=logo)
t.fit(features=X, target=y)
```
```
TypeError: can't pickle generator objects
_pickle.PicklingError: Could not pickle the task to send it to the workers.
```

It seems like the `logo` generator is getting sent to `joblib`

Looking at the `sklearn` source, it seems like the generator gets converted into an array before parallelizing (see [here](https://github.com/scikit-learn/scikit-learn/blob/21686b7147ea9f24a8e415d05a5046477e976864/sklearn/model_selection/_validation.py#L735)). I tried stealing `check_cv` from `sklearn` and it fixed the issue, I'm not sure about importing a function from a `_` prefixed module in `sklearn`, otherwise I think this would be the ideal solution.

**Comment by weixuanfu** [comment]
Thank you for reporting this bug. I think this solution is good. I think [this line](https://github.com/EpistasisLab/tpot/blob/v0.11.1/tpot/gp_deap.py#L416) should be moved before before parallelizing ([here](https://github.com/EpistasisLab/tpot/blob/v0.11.1/tpot/base.py#L1271)). You are welcome to submit a PR to fix it for your credit.

**Comment by adriangb** [comment]
Awesome, will do.

Do you think we can use the `self.classification` parameter instead of checking each pipeline with `is_classifier(sklearn_pipeline)`?

**Comment by weixuanfu** [comment]
Yes, I think that is better.
