### ISSUE TITLE
docs: DOI link is dead

### ISSUE THREAD

**Issue by ckastner** [EpistasisLab/tpot#1021]
I noticed that the DOI link at the very bottom of `docs_sources/citing.md` is dead. zenodo.org reports that the page cannot be found.

**Comment by weixuanfu** [comment]
Nice check! I didn’t notice the link was broken. We will fix that for next minor release later.

**Comment by weixuanfu** [comment]
I just fixed the link. Please feel free to reopen this issue if you have any questions/issues.
