### ISSUE TITLE
Issue specifying kernel with Gaussian Process Regressor using a custom configuration

### ISSUE THREAD

**Issue by lukeconibear** [EpistasisLab/tpot#1030]
Hi,
Firstly, TPOT is great, thanks.
The issue I have is with specifying a Gaussian Process Regressor kernel whilst using a custom configuration. Using the below code as a contained example; if I don't specify the kernel everything works, and if I specify the kernel I receive the RuntimeError below. The kernel within the Gaussian Process Regressor is an kernel object type, while other keys specified in the default [regressor config](https://github.com/EpistasisLab/tpot/blob/master/tpot/config/regressor.py) have kernels that are strings (e.g. Nystroem).
I'll be very grateful if anyone can help here.
Thanks,
Luke

```python
import sklearn
from tpot import TPOTRegressor
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data,
                                                    digits.target,
                                                    train_size=0.75,
                                                    test_size=0.25)

tpot_config = {
    'sklearn.gaussian_process.GaussianProcessRegressor': {
    'kernel': [sklearn.gaussian_process.kernels.DotProduct]
    },
}

tpot = TPOTRegressor(generations=5,
                     population_size=20,
                     verbosity=2,
                     config_dict=tpot_config)

tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
tpot.export('tpot_digits_pipeline.py')
```
```
RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly.
```

**Comment by weixuanfu** [comment]
TPOT does not support this `kernel` usage so far. It should be a nice enhancement feature. Any contribution is welcome.

**Comment by lukeconibear** [comment]
Okay. Thinking about what would be needed for TPOT, running a test using a custom configuration including another estimator e.g.:
```python
tpot_config = {
    'sklearn.gaussian_process.GaussianProcessRegressor': {
        'kernel': {
            'sklearn.gaussian_process.kernels.DotProduct': { 
            }
        }
    },
    'sklearn.ensemble.AdaBoostRegressor': {
    }
}
```
The output (with verbosity=3) changes to:
```
_pre_test decorator: _random_mutation_operator: num_test=0 Cannot clone object '<class 'sklearn.gaussian_process.kernels.DotProduct'>' (type <class 'abc.ABCMeta'>): it does not seem to be a scikit-learn estimator as it does not implement a 'get_params' methods..
```
The DotProduct kernel isn't a sklearn estimator though it does have a get_params method, which it inherits from the base class [Kernel](https://github.com/scikit-learn/scikit-learn/blob/95d4f0841/sklearn/gaussian_process/kernels.py#L120), which itself inherits from abc.ABCMeta. This get_params method is slightly different to that use for the [BaseEstimator](https://github.com/scikit-learn/scikit-learn/blob/95d4f0841/sklearn/base.py#L173).

Would the Gaussian process kernels need to inherit from the BaseEstimator for kernel specification to work (e.g. as the [Nystroem](https://github.com/scikit-learn/scikit-learn/blob/95d4f0841/sklearn/kernel_approximation.py#L432) kernel does)?

Or is there a different solution?

**Comment by weixuanfu** [comment]
Thank you for digging into this issue.

I just made a PR #1032 and merged it into development branch of TPOT to add this kernel support. You may try the dev branch via the command below:

```shell
pip install --upgrade --no-deps --force-reinstall git+https://github.com/EpistasisLab/tpot.git@development
```

Here is a [demo](https://gist.github.com/weixuanfu/ede0772ed578a8d31e8e18afc1e6e8bf) for specifying kernel with GaussianProcessRegressor. 

It is noted that I tried to use `DotProduct` for a demo but somehow I got a error message in the end of TPOT process (` ("The kernel, DotProduct(sigma_0=1), is not returning a positive definite matrix. Try gradually increasing the 'alpha' parameter of your GaussianProcessRegressor estimator.", '1287-th leading minor of the array is not positive definite')`) so that the final model from TPOT cannot be fitted on the whole training dataset somehow. But maybe you won't see this error message for using it on another dataset.

**Comment by lukeconibear** [comment]
Thank you very much @weixuanfu for this nice addition, it's really useful.

The error with DotProduct was specific to the digits dataset, as this kernel works with my data.
