### ISSUE TITLE
Page not found in document website 

### ISSUE THREAD

**Issue by Jaimecclin** [EpistasisLab/tpot#1034]
There is a link in document website redirecting to not existing page.

## Context of the issue

I tried to contribute something but I found that a link redirecting to 404 page.

## Process to reproduce the issue

1. Go to [doc](http://epistasislab.github.io/tpot/contributing/)
2. Click the link: Update "the project unit tests" to test your code changes.

## Expected result

It should be a right page.

## Current result

404 page not found

## Possible fix

Not necessary, but fix it should be easy.

**Comment by weixuanfu** [comment]
Thank you for catching this error. The link should be `https://github.com/EpistasisLab/tpot/tree/master/tests`

**Comment by weixuanfu** [comment]
I just fixed the link. Please feel free to reopen this issue if you have any questions/issues.
