### ISSUE TITLE
TPORegressor - Documentation doesn't specify correct object

### ISSUE THREAD

**Issue by rnmourao** [EpistasisLab/tpot#1036]
## Context of the issue

There is a little mistake on [score function specification](https://epistasislab.github.io/tpot/api/#tpotregressor-score): where it is read

"The default scoring function for **TPOTClassifier** is 'mean_squared_error'."

Should be

"The default scoring function for **TPOTRegressor** is 'mean_squared_error'."

**Comment by weixuanfu** [comment]
Thank you for catching this error. I fixed it and will update docs soon. Please feel free to reopen this issue if you have more questions/issues.
