### ISSUE TITLE
cannot import name 'TPOTClassifier' from 'tpot'

### ISSUE THREAD

**Issue by zhuwater** [EpistasisLab/tpot#1046]
what's my problem?Can anybody help me?

**Comment by weixuanfu** [comment]
Could you please provide more details about this issue, like environment info? How did you install tpot? 

Maybe reinstalling tpot into another conda environment can solve this issue.

**Comment by zhuwater** [comment]
thank you!
   I installed TPOT(version 0.11.1) by pycharm of project interpreter. And,when i do 'from tpot importTPOTClassifier' and run ,the 'ImportError: cannot import name 'TPOTClassifier' from 'tpot' ' is appeared.
   then i uninstalled TPOT,and installed by pip install.The tpot is in the pip list.When i open the pycharm,it is still not work.the the 'ImportError: cannot import name 'TPOTClassifier' from 'tpot' ' is appeared again.
  my python version is 3.7.
  And i don't known why.

















--

祝工作顺利，事事顺心！
 
此致，
 
朱密元




在 2020-04-16 21:15:32，"Weixuan Fu" <notifications@github.com> 写道：

Could you please provide more details about this issue, like environment info? How did you install tpot?

Maybe reinstalling tpot into another conda environment can solve this issue.

**Comment by weixuanfu** [comment]
Could you please try to import `TPOT Classifier` a Python interactive console without pycharm? If it works, it seems the python environment of pycharm was not configured correctly. Please check this [link](https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html#) for details about setting the environment variable.

**Comment by nivort** [comment]
@zhuwater  If the file name of your script is "tpot.py", try to change it to others like 'tpottest.py'. This could be one of the reasons that lead to the problem.

**Comment by zhuwater** [comment]
yes,it's work now.thank you very very much.
















--

祝工作顺利，事事顺心！
 
此致，
 
朱密元




At 2020-04-18 18:26:12, "nivort" <notifications@github.com> wrote:

@zhuwater If the file name of your script is "tpot.py", try to change it to others like 'tpottest.py'. This could be one of the reasons that lead to the problem.
