### ISSUE TITLE
balanced Accuracy problem on constant fold

### ISSUE THREAD

**Issue by franchuterivera** [EpistasisLab/tpot#1060]
I think there is some room for improvement in the calculation of balanced accuracy in tpot. Seems like for some unlucky fold of one of my runs, all the true/predicted values of the pipeline both came to be zero.

This is a scenario tpot cannot handle well, for example:

>>> from tpot.metrics import balanced_accuracy
>>> import numpy as np
>>> from sklearn.metrics import balanced_accuracy_score
>>> balanced_accuracy_score(np.zeros(100), np.zeros(100))
1.0
>>> balanced_accuracy(np.zeros(100), np.zeros(100))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chico/work/venv_autosklearn/lib/python3.6/site-packages/tpot/metrics.py", line 61, in balanced_accuracy
    float(sum((y_true != this_class)))
ZeroDivisionError: float division by zero

Maybe, a query can be asked before dividing by zero, cause tpot just failed in this unlucky scenario. Also, is there an intuition for not moving to sklearn balanced accuracy?

**Comment by weixuanfu** [comment]
Thank you for report this bug.

Balanced Accuracy in TPOT was described in [Urbanowicz2015](https://scikit-learn.org/stable/modules/model_evaluation.html#urbanowicz2015): the average of sensitivity and specificity is computed for each class and then averaged over total number of classes. It is different with sklearn balanced accuracy.

**Comment by weixuanfu** [comment]
This issue should be fixed in TPOT v0.11.2. Please feel free to reopen this issue if there is a unsolved issue related to this one.
