### ISSUE TITLE
gp_deap does not print to log_file 

### ISSUE THREAD

**Issue by adrienhenry** [EpistasisLab/tpot#1072]
Hello,

I have found a behavior that was unexpected to me and I do not know if it should be considered as a bug.

When I set the verbosity to 2 and specify a log_file, only the pbar is printed into the file. 
The  `"Generation {0} - Current best internal CV score: {1}"` is printed to the stdout.

Replacing the following line:
https://github.com/EpistasisLab/tpot/blob/8142192e55306291226a5244a9b31e3ecd8f1bb0/tpot/gp_deap.py#L256
by 
```python
pbar.fp.write('Generation {0} - Current best internal CV score: {1}'.format(gen, high_score))
```
would do what I expect but I do not know if that would be something you are willing to implement.

**Comment by weixuanfu** [comment]
Thank you for submitting this issue. I think it should be implemented into log_file. Could you please submit a PR for this fix?

**Comment by adrienhenry** [comment]
Here https://github.com/EpistasisLab/tpot/pull/1073
