### ISSUE TITLE
New undeclared dependency on pytorch?

### ISSUE THREAD

**Issue by bollwyvl** [EpistasisLab/tpot#1075]
Congratulations on the release!It looks like as of `0.11.4`, importing `tpot` is trying to bring in `torch`.

While I see it was added to `requirements.txt`, it would need adding to `install_requires` in `setup.py`, as `pip` doesn't really look at anything else but that file (well, and `setup.cfg` and `pyproject.toml`... but i digress...)

**But**, to be frank, there's a whole raft of complexity that comes along with a hard dependency on torch, and as a downstream maintainer, and occasional instructor of using `tpot`, I'd selfishly **strongly** prefer it be hidden behind an `extra` like some of the other heavyweight dependencies (e.g. `xgboost`, `dask`) unless it's _really_ part of the core `tpot` functionality now. 

Indeed, to that end, as conda-forge only ships `pytorch-cpu`, and I generally can't recommend using `pytorch-cpu` (from conda-forge, [pytorch](https://anaconda.org/pytorch) or otherwise) for getting any real work done (other than testing), the documentation would likely need to be updated to suggest using `-c pytorch -c defaults -c conda-forge tpot pytorch` to get a useful setup... but then, I haven't been able to test that hypothesis yet! At any rate, we _would_ be able to support a hard pin, with [`run_constrained`](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run-constrained)... but that can be an unsatisfying and bewildering user experience if they didn't even _know_ `tpot` used `torch` until this patch release!

## Context of the issue

Downstream pull request:
- https://github.com/conda-forge/tpot-feedstock/pull/25#issuecomment-636078946

CI screesnshot (with link to log):
[![Screenshot from 2020-05-29 20-18-06](https://user-images.githubusercontent.com/45380/83314669-90fa5c00-a1e9-11ea-84a0-0ee3078d5a30.png)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=168375&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c&l=719
)

**Comment by weixuanfu** [comment]
Thank you for reporting this issue. We added this dependency [in installation guide](https://epistasislab.github.io/tpot/installing/#conda-forge). 

But I agree with you that installing `pytorch` in different environments is complex and maybe it should be an optional dependency.

@JDRomano2 Could you please add some suggestions about using pytorch in GPU environment on the installation guide? Also, is it possible to make it as an optional dependency?

**Comment by JDRomano2** [comment]
Since the `torch` estimators require the user to explicitly ask for them I think it makes sense to mark it as an optional dependency (and make the appropriate checks before importing the NN estimators).

I’ll make sure to push a fix shortly.

**Comment by bollwyvl** [comment]
Thanks! `0.11.5` is up on [anaconda.org](https://anaconda.org/conda-forge/tpot/files?version=0.11.5)... though it will take up to a half hour before it's generally available over CDN.
