### ISSUE TITLE
multiclass ROCAUC with TPOTClassifier?

### ISSUE THREAD

**Issue by Lamiane** [EpistasisLab/tpot#1077]
The [TPOT documentation](https://epistasislab.github.io/tpot/api/#classification) only mentions 'roc_auc' among valid  built-in scoring functions of the ROCAUC family. However, it cannot be used for multiclass classification.

## Context of the issue

Since TPOT makes use of sklearn.metrics.SCORERS it should be possible to use multiclass ROCAUC options, namely: roc_auc_ovr, roc_auc_ovo, roc_auc_ovr_weighted, and roc_auc_ovo_weighted.

Indeed, the following code suggests that it works:

```python
from sklearn.datasets import load_iris
import sklearn.metrics
from tpot import TPOTClassifier

data = load_iris()
x = data['data']
y = data['target']

model = TPOTClassifier(max_time_mins=2, scoring='roc_auc_ovr_weighted')
model.fit(x, y)

tpot_score = model.score(x, y)

preds = model.predict_proba(x)
sklearn_score = sklearn.metrics.roc_auc_score(y, preds, multi_class='ovr', average='weighted')
print(tpot_score==sklearn_score)
```
```output: True```

## Question
Are multiclass ROCAUC metrics valid to use with TPOT and just not mentioned in the documentation or are they not valid and should not be used?

## Possible fix
Adding roc_auc_ovr, roc_auc_ovo, roc_auc_ovr_weighted, and roc_auc_ovo_weighted to docs or warning not to use them

**Comment by weixuanfu** [comment]
Thank you for reporting this issue. We will refine the docs.

**Comment by Lamiane** [comment]
Thank you for such a quick reply!

**Comment by weixuanfu** [comment]
The docs was just updated. Please let us know if there is any other issue.

**Comment by Lamiane** [comment]
Thank you! I think the docs are OK now and the issue can be closed.
