### ISSUE TITLE
Visulization

### ISSUE THREAD

**Issue by JDface** [EpistasisLab/tpot#1089]
Can you please show some example using charts, Thank you for doing so.

**Comment by weixuanfu** [comment]
What example? Could you please provide more details about the question/issue? Please feel free to reopen this issue with details.

**Comment by JDface** [comment]
for e.g. image shown below, I am new in AI and understand faster from images\pictures.
![exm](https://user-images.githubusercontent.com/11360095/86521034-1b4d6580-be11-11ea-9002-ec861d220ab8.png)

**Comment by weixuanfu** [comment]
Sorry we don't have a image/chart like this.
