### ISSUE TITLE
Docs search is not working on https://epistasislab.github.io/tpot/

### ISSUE THREAD

**Issue by Anselmoo** [EpistasisLab/tpot#1091]
The search engine on [https://epistasislab.github.io/tpot/](https://epistasislab.github.io/tpot/) is not working, so I have to use google or Bing to find `tpot`-references.

## Context of the issue

Documentary: If I want to look for reference snippet and docs the [official page](https://epistasislab.github.io/tpot/) doesn't allow me to search for results.

## Process to reproduce the issue

1. Looking for *regression*  with reference page [https://epistasislab.github.io/tpot/api/](https://epistasislab.github.io/tpot/api/)
2. No results via: [https://epistasislab.github.io/tpot/search.html?q=regression](https://epistasislab.github.io/tpot/search.html?q=regression)
3.  [Google](https://www.google.com/search?safe=active&rlz=1C1GCEU_deLI906LI906&sxsrf=ALeKk01xx17opjCOkiPSK6aSBIBAPBv10A%3A1594630015675&ei=fx8MX5HYKKaZk74PxoOe4Ao&q=tpot+regressor&oq=tpot+reg&gs_lcp=CgZwc3ktYWIQAxgAMgIIADICCAAyAggAMgIIADICCAAyBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeOgQIABBHOgQIIxAnOgcIABAUEIcCUJoJWPwWYOQqaABwAngAgAFYiAGEApIBATOYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab) get [reference](https://epistasislab.github.io/tpot/api/) as second result in seconds

## Expected result

 [https://epistasislab.github.io/tpot/search.html?q=regression](https://epistasislab.github.io/tpot/search.html?q=regression) brings me to  [https://epistasislab.github.io/tpot/api/](https://epistasislab.github.io/tpot/api/)

## Current result

[Frozen search page](https://epistasislab.github.io/tpot/search.html?q=regression)

**Comment by weixuanfu** [comment]
Thank you for reporting this issue. This issue is caused by incompatibility of TPOT docs with a older version of `mkdocs` (v1.0.1). I fixed MarkDown docs in #1092 PR and now the webpage was updated.  Please check it.

**Comment by Anselmoo** [comment]
@weixuanfu Thank you very much! It's working excellent!
