### ISSUE TITLE
RunTimeError: Data not formatted properly. 

### ISSUE THREAD

**Issue by MathiasHolmstrom** [EpistasisLab/tpot#1103]
I am receiving an error when trying to use the TPOTClassifier. I spent the past hour trying to search for similar issues. However, nothing so far has worked. 

My original datasource is a dataframe and when printing the X.head(5), this is the output:

>        avg_time_weighted_total_kills
> 10340                      23.731062
> 10353                      25.640752
> 10394                      23.662248
> 10396                      22.907101
> 10243                      30.461168

(so just one feature for now)

Originally I used tpot.fit(X,y) directly (from the dataframe). When that didn't work I tried the ravel approach (which was suggested in a previous issue), however that also didn't solve the issue. 

```
y = df[target]
X = df[features]
tpot = TPOTClassifier(generations=1,population_size=1,verbosity=2)
tpot.fit(pd.np.array(X), pd.np.array(y).ravel())

```

Error message:

> Traceback (most recent call last):
>   File "C:\Users\Mathias\AppData\Local\Programs\Python\Python37\lib\site-packages\tpot\base.py", line 725, in fit
>     per_generation_function=self._check_periodic_pipeline
>   File "C:\Users\Mathias\AppData\Local\Programs\Python\Python37\lib\site-packages\tpot\gp_deap.py", line 271, in eaMuPlusLambda
>     per_generation_function(gen)
>   File "C:\Users\Mathias\AppData\Local\Programs\Python\Python37\lib\site-packages\tpot\base.py", line 1021, in _check_periodic_pipeline
>     self._update_top_pipeline()
>   File "C:\Users\Mathias\AppData\Local\Programs\Python\Python37\lib\site-packages\tpot\base.py", line 807, in _update_top_pipeline
>     raise RuntimeError('There was an error in the TPOT optimization '
> RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly. If you enabled PyTorch estimators, please check the data requirements in the online documentation: https://epistasislab.github.io/tpot/using/
> 
> During handling of the above exception, another exception occurred:

**Comment by weixuanfu** [comment]
Could you please print out the shape of X, y?

**Comment by MathiasHolmstrom** [comment]
Yes X is (23000,1) and y is (23000,)

**Comment by weixuanfu** [comment]
Hmm only one feature, please check this related [question](https://stackoverflow.com/questions/17232078/is-that-make-sense-to-construct-a-learning-model-using-only-one-feature) for ML analysis.  

But I tested the demo below and this issue is not found. Could you share your data and code with me for a test?

```python
from tpot import TPOTClassifier
import numpy as np
X = np.random.random((23000,1))
y = np.random.randint(2, size=23000)

tpot = TPOTClassifier(generations=2,population_size=2,verbosity=2,random_state=42)

print(X.shape, y.shape)
tpot.fit(X, y)
```

**Comment by MathiasHolmstrom** [comment]
I had the same issue with increased feature count on this dataset. 

How should I go about sharing the file. Can I save the dataframe in one of the supported formats or is there an email where I can send it as pickle?

**Comment by weixuanfu** [comment]
Please find my email under my [Github profile](https://github.com/weixuanfu).

Please send over the dataset (or partial dataset) as csv/tsv file (please note which one is target in your email) and python scripts you used.
