### ISSUE TITLE
Genetic Optimization details

### ISSUE THREAD

**Issue by hanshupe** [EpistasisLab/tpot#1104]
I have a few questions regarding the parameters of the genetic algorithm which are not answered in the doc:

1) What if mutation_rate and crossover_rate don't sum up to 1, is the rest filled up with new random genoms?
2) What exactly is the offsping_size doing?
3) Which mutation operators are applied: for example if there is a parameter to optimize between 0-100, is it mutated randomly or by multiplying the current solution with a random factor (e.g. 0.8-1.2)?

Background to my questions is: my optimization gets stuck in local minima quite fast: it converges too fast, different random seeds leed to quite different optimization results after it converges.

**Comment by weixuanfu** [comment]
> I have a few questions regarding the parameters of the genetic algorithm which are not answered in the doc:
> 
>     1. What if mutation_rate and crossover_rate don't sum up to 1, is the rest filled up with new random genoms?

If the sum is less than 1, then GP process can randomly reproduce/copy pipelines from parental generation to its offspring generation. The reproduction rate is 1-mutation_rate-crossover_rate. (see [here](https://github.com/EpistasisLab/tpot/blob/1c009c669190a024671a2d810f90fc097d6610d5/tpot/gp_deap.py#L122-L125))

>     2. What exactly is the offsping_size doing?

`offspring_size` is the number of pipelines generated from parental generation. Please check the [eaMuPlusLambda](https://deap.readthedocs.io/en/0.7-a1/algorithms.html) for more details. 

>     3. Which mutation operators are applied: for example if there is a parameter to optimize between 0-100, is it mutated randomly or by multiplying the current solution with a random factor (e.g. 0.8-1.2)?

Please check this related [issue](https://github.com/EpistasisLab/tpot/issues/318)
> 
> Background to my questions is: my optimization gets stuck in local minima quite fast: it converges too fast, different random seeds leed to quite different optimization results after it converges.
