### ISSUE TITLE
(Re-)Opening a Gitter or Slack Group for Tpot

### ISSUE THREAD

**Issue by Anselmoo** [EpistasisLab/tpot#1124]
Having a chat/communication -platform like (`Gitter` or `Slack`) to support answering questions by the tpot-developer and the community for the community.

## Context of the issue

In terms of general or usage-question questions like:

-  _usefule learning rates_, _problems with overfitting_
- _experience with different CV-methods_
- _..._

a chatting platform like `Gitter` or `Slack` could a good way to increase exchange of experience vice versa avoiding overuse the [issues-section](https://github.com/EpistasisLab/tpot/issues)

## Process to reproduce the issue

In terms of the closed the issues, it looks like that previously this group already existed:
[Issue:106](https://github.com/EpistasisLab/tpot/pull/106)

**Comment by weixuanfu** [comment]
Thank you for the suggestion. We tried to use Gitter before but it was very quiet for a whole, which is why we stopped using it. I think we can this issues section of the repo for questions and users can easily search them.

**Comment by Anselmoo** [comment]
@weixuanfu thx, sounds cool
