### ISSUE TITLE
use_dask returning error when running on Google Colaboratory

### ISSUE THREAD

**Issue by JuanE33** [EpistasisLab/tpot#1130]
I have been trying to train some models on big datasets using dask and google colab but haven't been able to. If this could get fixed it would be nice to train models faster. I have even tried to replicate the example given in https://examples.dask.org/machine-learning/tpot.html 

This is the code I'm using and the error I'm getting (from examples.dask example):

!pip install tpot
import tpot
from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

from dask.distributed import Client
client = Client(n_workers=4, threads_per_worker=1)

digits = load_digits()

X_train, X_test, y_train, y_test = train_test_split(
    digits.data,
    digits.target,
    train_size=0.05,
    test_size=0.95,
)

tp = TPOTClassifier(
    generations=2,
    population_size=10,
    cv=2,
    n_jobs=-1,
    random_state=0,
    verbosity=0,
    config_dict=tpot.config.classifier_config_dict_light,
    use_dask=True,
)

tp.fit(X_train, y_train)

Error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tpot/gp_deap.py in _wrapped_cross_val_score(sklearn_pipeline, features, target, cv, scoring_function, sample_weight, groups, use_dask)
    412         try:
--> 413             import dask_ml.model_selection  # noqa
    414             import dask  # noqa

ModuleNotFoundError: No module named 'dask_ml'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
9 frames
ImportError: 'use_dask' requires the optional dask and dask-ml depedencies.
No module named 'dask_ml'

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tpot/base.py in _update_top_pipeline(self)
    827             # If user passes CTRL+C in initial generation, self._pareto_front (halloffame) shoule be not updated yet.
    828             # need raise RuntimeError because no pipeline has been optimized
--> 829             raise RuntimeError('A pipeline has not yet been optimized. Please call fit() first.')
    830 
    831     def _summary_of_best_pipeline(self, features, target):

RuntimeError: A pipeline has not yet been optimized. Please call fit() first.

If anyone could please help me out please, it would help me a lot!

**Comment by JuanE33** [comment]
!pip install dask_ml solved this issue. However, when running this code on the real dataset, I'm getting another error:

!pip install tpot
!pip install dask_ml
!pip install dask
!pip install dask-ml

import tpot
from tpot import TPOTRegressor
import pandas as pd
import os
import joblib
from sklearn.model_selection import train_test_split

from dask.distributed import Client
client = Client(n_workers=25, threads_per_worker=2)

from google.colab import drive 
drive.mount('/content/gdrive')
%cd /content/gdrive/My\ Drive/Colab Notebooks

df = pd.read_csv('example.csv', index_col = 0)

x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], train_size=0.8,
                                                    test_size=0.2, random_state=5)

tpot_model = TPOTRegressor(generations = 3, population_size = 50, cv=5, random_state=7, verbosity=2, scoring='neg_mean_absolute_error',
                               periodic_checkpoint_folder=os.getcwd() + '/', n_jobs = -1, use_dask = True)

with joblib.parallel_backend("dask"):
    tpot_model.fit(x_train, y_train)

This is the error:
---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tpot/gp_deap.py in _wrapped_cross_val_score(sklearn_pipeline, features, target, cv, scoring_function, sample_weight, groups, use_dask)
    412         try:
--> 413             import dask_ml.model_selection  # noqa
    414             import dask  # noqa

14 frames
ContextualVersionConflict: (scikit-learn 0.22.2.post1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('scikit-learn>=0.23'), {'dask-ml'})

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
ImportError: 'use_dask' requires the optional dask and dask-ml depedencies.
(scikit-learn 0.22.2.post1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('scikit-learn>=0.23'), {'dask-ml'})

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tpot/base.py in _update_top_pipeline(self)
    827             # If user passes CTRL+C in initial generation, self._pareto_front (halloffame) shoule be not updated yet.
    828             # need raise RuntimeError because no pipeline has been optimized
--> 829             raise RuntimeError('A pipeline has not yet been optimized. Please call fit() first.')
    830 
    831     def _summary_of_best_pipeline(self, features, target):

RuntimeError: A pipeline has not yet been optimized. Please call fit() first.

**Comment by weixuanfu** [comment]
We will refine the installation guide on this [link](https://epistasislab.github.io/tpot/installing/) for support dask-ml v1.7, which require scikit-learn >= 0.23 and distributed > 2.*

So you also need update distributed and scikit-learn for using dask in colab, please check this [demo](https://colab.research.google.com/gist/weixuanfu/7e58b6120929a10a53f034cfb2608e85/tpot_dask_check_colab.ipynb). It is noted that you may need restart runtime (not reset) after those `pip install` commends.
