### ISSUE TITLE
Generating synthetic data for avoiding overfitting

### ISSUE THREAD

**Issue by Anselmoo** [EpistasisLab/tpot#1131]
Question
---

1. Are any plans started to generate synthetic data during the cycle for avoiding overfitting?
2. Or can `tpot` be connected to external libraries like: [imbalanced-learn](https://imbalanced-learn.readthedocs.io/en/stable/index.html)

**Comment by weixuanfu** [comment]
Thank you for your suggestion. But in the near future, we don't have a plan of generating synthetic data in TPOT.

You may use some transformers/estimators in imbalanced-learn with a [custom configuration](https://epistasislab.github.io/tpot/using/#customizing-tpots-operators-and-parameters) in TPOT if they support scikit-learn API.

**Comment by Anselmoo** [comment]
> Thank you for your suggestion. But in the near future, we don't have a plan of generating synthetic data in TPOT.
> 
> You may use some transformers/estimators in imbalanced-learn with a [custom configuration](https://epistasislab.github.io/tpot/using/#customizing-tpots-operators-and-parameters) in TPOT if they support scikit-learn API.

@weixuanfu is there a possibility to include a `scikit` [learning-curve](https://scikit-learn.org/stable/modules/learning_curve.html) in this module?

**Comment by weixuanfu** [comment]
For now, you can easily make a learning-curve with `fitted_pipeline_` attribute.
