### ISSUE TITLE
Cannot use n_jobs in tpot.TPOTRegressor(), please help!

### ISSUE THREAD

**Issue by CCCCCaO** [EpistasisLab/tpot#1132]
## Cannot use the `n_jobs` parameters in `tpot.TPOTRegressor()`

Hello! When I use the `n_jobs` in `tpot.TPOTRegressor()`, there is a `TypeError`, i don't know why, please help me and thank you very much!!!

## Process to reproduce the issue

```python
from tpot import TPOTRegressor
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

housing = load_boston()
X_train, X_test, y_train, y_test = train_test_split(housing.data, housing.target,
                                                    train_size=0.75, test_size=0.25, random_state=42)

tpot = TPOTRegressor(generations=5, population_size=50, n_jobs=2, verbosity=3, random_state=42)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
tpot.export('tpot_boston_pipeline.py')
```

## Current result

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-f96e049aa767> in <module>
      7                                                     train_size=0.75, test_size=0.25, random_state=42)
      8 
----> 9 tpot = TPOTRegressor(generations=5, population_size=50, n_jobs=2, verbosity=3, random_state=42)
     10 tpot.fit(X_train, y_train)
     11 print(tpot.score(X_test, y_test))

TypeError: __init__() got an unexpected keyword argument 'n_jobs'
```

## Possible fix

when I use `help(TPOTRegressor())` to find the help document, the doc shows that there's no `n_jobs` parameters... is this not updated or still under development?

**Comment by weixuanfu** [comment]
Hmm, it is strange. It should work. Please check [the demo in Colab](https://colab.research.google.com/gist/weixuanfu/8352982107f46406ef69d940e1fccf4c/tpot_reg_n_jobs.ipynb) and also make sure there is no python scripts named `tpot.py` in your work directory.

**Comment by CCCCCaO** [comment]
> Hmm, it is strange. It should work. Please check [the demo in Colab](https://colab.research.google.com/gist/weixuanfu/8352982107f46406ef69d940e1fccf4c/tpot_reg_n_jobs.ipynb) and also make sure there is no python scripts named `tpot.py` in your work directory.

Ah, this is caused by the TPOT version. The version is **0.11.5** on Colab while the one in my development image is just **0.6.8**... Thank you!!!
