### ISSUE TITLE
Is it possible to use only XGBoost to search the parameters?

### ISSUE THREAD

**Issue by KleinXin** [EpistasisLab/tpot#1133]
I am using TPOT version 0.11.5 and XGBoost version 1.2.0

When I set tpot as it shows in guide 

tpot_config = {
    'sklearn.naive_bayes.GaussianNB': {
    }}

The trainning works fine and GaussianNB model is used. 

However, if I changed the tpot_config to XGBoost just like the code below

tpot_config = {
    'xgboost.XGBClassifier': {
    }}

it gives error as shown below

![image](https://user-images.githubusercontent.com/13084622/97282013-22ddc200-1879-11eb-85fa-aa4861dd5f33.png)

I think it should not have problem with the data because the same data is used for both GaussianNB and XGBoost.

Anyone can help?

thx!

**Comment by weixuanfu** [comment]
Hmm could you please make a demo to reproduce this issue? I tested it in Colab (see [this notebook](https://colab.research.google.com/gist/weixuanfu/d9303d3f1e654e572cecbb56d700de6f/issue1133.ipynb)) but no error shown up. 

BTW, you can update TPOT to 0.11.6 for clearer error messages in this situation.

**Comment by KleinXin** [comment]
> Hmm could you please make a demo to reproduce this issue? I tested it in Colab (see [this notebook](https://colab.research.google.com/gist/weixuanfu/d9303d3f1e654e572cecbb56d700de6f/issue1133.ipynb)) but no error shown up.
> 
> BTW, you can update TPOT to 0.11.6 for clearer error messages in this situation.

After upgrading tpot to 0.11.6, the same error is reported. Maybe it is really the problem of the data. Now I am using npy format data, I will try to change it to csv format.

**Comment by KleinXin** [comment]
> Hmm could you please make a demo to reproduce this issue? I tested it in Colab (see [this notebook](https://colab.research.google.com/gist/weixuanfu/d9303d3f1e654e572cecbb56d700de6f/issue1133.ipynb)) but no error shown up.
> 
> BTW, you can update TPOT to 0.11.6 for clearer error messages in this situation.

The problem is that the trainning time is too limited. After two hours trainning, the score is reported.
