### ISSUE TITLE
Suggestion: Add LightGBM and Catboost

### ISSUE THREAD

**Issue by apavlo89** [EpistasisLab/tpot#1152]
TPOT is fantastic but it feels like I'd be pretty complete if it added Microsoft's LightGBM and Catboost! Any plans for adding it in the future?

**Comment by weixuanfu** [comment]
Thank you for this suggestion. 

Since TPOT already supports xgboost, we don't have plan to add similar algorithms,
like lightGBM or CatBoos, into TPOT's default configuration.  Please check #808 for a workaround.

**Comment by apavlo89** [comment]
Great, thanks, I've now added LightGBM and CatBoost into TPOT. I have to say that for my multiclass classification problem LightGBM ended up giving me a F1_macro score that was significantly better than XGBoost
