### ISSUE TITLE
HistGradientBoostingClassifier

### ISSUE THREAD

**Issue by lesshaste** [EpistasisLab/tpot#1160]
Does TPOT support HistGradientBoostingClassifier? It can be hugely faster, amongst other advantages.

**Comment by weixuanfu** [comment]
Thank you for sharing this idea. TPOT does not support HistGradientBoostingClassifier so far but may easily include it using `config_dict` (see [this link](https://epistasislab.github.io/tpot/using/#customizing-tpots-operators-and-parameters)) on a customized configuration based on [Built-in TPOT configurations](https://epistasislab.github.io/tpot/using/#built-in-tpot-configurations).

**Comment by lesshaste** [comment]
Thank you.
