### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.cross_validation'

### ISSUE THREAD

**Issue by andrianamin** [EpistasisLab/tpot#1167]
hi guys,
I have issue on:
pip install sklearn.cross_validation

it has no this module

python: 3.8.6
windows 10

read your comments and not useful, can you help to fix it ?

_Originally posted by @aminanderian in https://github.com/EpistasisLab/tpot/issues/314#issuecomment-764479457_

**Comment by andrianamin** [comment]
I tried on colab and had this issue again

**Comment by weixuanfu** [comment]
Try `pip install scikit-learn` instead

**Comment by JDRomano2** [comment]
Closing issue - if `pip install scikit-learn` did not resolve the problem please add a follow-up comment.
