### ISSUE TITLE
TPOTClassifier fails when cv is PredefinedSplit from sklearn.model_selection, and n_jobs is greater than 1. But runs fine when n_jobs=1. 

### ISSUE THREAD

**Issue by HarshithMjh** [EpistasisLab/tpot#1168]

**Comment by weixuanfu** [comment]
Please provide a example to reproduce this issue.

**Comment by HarshithMjh** [comment]
![TPOT doc](https://user-images.githubusercontent.com/42462113/105396248-ab37ed00-5c45-11eb-970b-3b364828cd81.JPG)

This issue is not occurring every time. Just now I read the highlighted statement. I am using a very large dataset. So, I think, I faced the issue. Hence, closing this
