### ISSUE TITLE
Your examples throw RuntimeError

### ISSUE THREAD

**Issue by gkourogiorgas** [EpistasisLab/tpot#1173]
I ran your examples with digits and boston housing data and i got the same error:

`RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly. If you enabled PyTorch estimators, please check the data requirements in the online documentation: https://epistasislab.github.io/tpot/using/`

Environment is anaconda with python 3.8.6 and all dependency requirements met (created yesterday with most recent versions)
`tpot 0.11.6.post3
scikit-learn 0.24.1
pandas 1.2.1
numpy 1.20.0
etc.
`

**Comment by weixuanfu** [comment]
Please use tpot 0.11.7 with scikit-learn >= 0.24.

**Comment by gkourogiorgas** [comment]
In conda it is 0.11.6
https://anaconda.org/conda-forge/tpot
So i should pip install it correct?

**Comment by weixuanfu** [comment]
Yes, please use pip install instead.
