### ISSUE TITLE
TPOT feasture set selector 

### ISSUE THREAD

**Issue by rayshmahilal55** [EpistasisLab/tpot#1179]
I understand FeatureSetSelector is a special new operator in TPOT. This operator enables feature selection based on priori expert knowledge and I am able to send the subset to the code to select the features. But at the first place, how subset csv file is created? can user create a dummy csv file with the following. 

Subset | Size | Features
-- | -- | --

could you please help me in understanding on how did you decide on the subsets to provide to FeatureSetSelector?

**Comment by JDRomano2** [comment]
The subset(s) should be designed manually based on your understanding of the dataset and the task you are trying to accomplish. Briefly, each feature set should roughly correspond to a group of features that are somehow related. The example given in the TPOT documentation is a good one:

> For example, in RNA-seq gene expression analysis, this operator can be used to select one or more gene (feature) set(s) based on GO (Gene Ontology) terms

Here, the sets are groups of genes that have related functions. You, as the user, need to use expert knowledge to decide what those groups of genes are. 

Does this make sense?

**Comment by rayshmahilal55** [comment]
Yes it makes sense. But after using fit(X,y), it returns the best pipeline but how to get the best features from the result. I tried using tpot.get_support() but it throws error. Is there any chances to know the best features selected for the model.
