### ISSUE TITLE
TPOT cuML 

### ISSUE THREAD

**Issue by rayshmahilal55** [EpistasisLab/tpot#1181]
I am trying to execute the code for TPOT cuML in windows by using blastingSQL but still it is not working. I understand that it doesn't work in windows so is there any chance for TPOT cuML code to work in google colab?

**Comment by beckernick** [comment]
We are working on an updated RAPIDS installer now that Colab has upgraded to Python 3.7. When that is available, TPOT cuML should "just work" on Colab if you have both packages available. Please follow https://github.com/rapidsai/cudf/issues/7472#issuecomment-789324827 for updates.

**Comment by rayshmahilal55** [comment]
TPOT is really amazing. Thank you for your response.

**Comment by JDRomano2** [comment]
@beckernick thank you for the update! Very glad to have support from the cuML/cuDF team!

@rayshmahilal55 I'm going to close this issue but encourage you to check the link provided above for updates that should fix this. If that does not end up resolving the issue please reopen this.
