### ISSUE TITLE
 Error: Input data is not in a valid format. Please confirm that the input data is scikit-learn compatible. For example, the features must be a 2-D array and target labels must be a 1-D array.

### ISSUE THREAD

**Issue by sofiavlachou28** [EpistasisLab/tpot#1234]
Hello to everyone!! :)

I am new to Python and I am getting this error when running TPOT:   
```
File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\tpot\base.py", line 1393, in _check_dataset
    "Error: Input data is not in a valid format. Please confirm "
ValueError: Error: Input data is not in a valid format. Please confirm that the input data is scikit-learn compatible. For example, the features must be a 2-D array and target labels must be a 1-D array.
```

I tried to search for this error, could not find much useful resources. Also this [Issue ](https://github.com/EpistasisLab/tpot/issues/478) is not very helpful for me. Sorry for reopening the issue.

I cant guess where the error occurs. 

Μy dataset consists of 4 columns: ["Frequency","Comments", "Likes", "Nwords"]. 
I use the same dataset for Classification, and it has no problem. 
Here is an example of the first rows of my csv: 
```
Frequency;comments;likes;nwords;sentiment
10;4290;148663;150;cheerfulness
34;1464;173373;428;cheerfulness
14;720;81778;179;cheerfulness
20;649;756445;252;cheerfulness
```

**Here is my code:** 
```
# dependencies
from pandas import read_csv
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import RepeatedStratifiedKFold
from tpot import TPOTClassifier


# load dataset
dataframe = read_csv("posts.csv", header=None)
# split into input and output elements
data = dataframe.values
X, y = data[:, :-1], data[:, -1]
# minimally prepare dataset
X = X.astype('float32')
y = LabelEncoder().fit_transform(y.astype('str'))

# define model evaluation
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# define search
model = TPOTClassifier(generations=5, population_size=50, cv=cv, scoring='accuracy', verbosity=2, random_state=1, n_jobs=-1)
# perform the search
model.fit(X, y)
# export the best model
model.export('tpot_posts_best_model.py')
```
Can anyone help me?? :)

Thank you in advance !!

Sofia

**Comment by Alexwenner0** [comment]
Ran into this same error on  `X_train, X_test, y_test, y_train = train_test_split(normalized_matrix, normalized_target,
                                                     train_size=0.75, test_size=0.25, random_state=42)`

The order of returns in the documentation is incorrect. Swapping y_test & y_train variable names in the assignment did the trick for me. Thought I would share! See below:

`X_train, X_test, y_train, y_test`
