### ISSUE TITLE
"A pipeline has not yet been optimized. Please call fit()" issue when using sklearn.model_selection.StratifiedKFold as 'cv'

### ISSUE THREAD

**Issue by teddy4445** [EpistasisLab/tpot#1260]
When using the TPOTRegressor object, with the method "fit" such that the during the constraction of the object we provide a 
"sklearn.model_selection.StratifiedKFold" object to the "cv" argument an error occurs stating "A pipeline has not yet been optimized. Please call fit()". 

## Process to reproduce the issue

I used the following code:
`
from tpot import TPOTRegressor
from sklearn.model_selection import StratifiedKFold

model = TPOTRegressor(generations=100,
                              population_size=100,
                              cv=StratifiedKFold(n_splits=5),
                              scoring="neg_mean_absolute_error",
                              verbosity=2,
                              n_jobs=-1)
model.fit(x_train, y_train)
`

## Expected result

A trained TPOT model 

## Current result

An exception that states "A pipeline has not yet been optimized. Please call fit()".

**Comment by lahdjirayhan** [comment]
TPOT raises an error because scikit-learn refuse to fit a regression model using StratifiedKFold as cross-validation method. 

StratifiedKFold is supposed to be used for classification, not regression, so this behavior is not really a bug.

The traceback goes something like this.
```
Traceback (most recent call last):
...
...
...
ValueError: Supported target types are: ('binary', 'multiclass'). Got 'continuous' instead.

The above exception was a direct cause of the following exception:

Traceback (most recent call last):
...
...
...
ValueError: Supported target types are: ('binary', 'multiclass'). Got 'continuous' instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
...
...
RuntimeError: A pipeline has not yet been optimized. Please call fit() first.
```
