### ISSUE TITLE
Coefficient of Logistic Regression Using TPOT

### ISSUE THREAD

**Issue by manbau10** [EpistasisLab/tpot#1269]
I built a model using Logistic regression in TPOT classifier. I used `model.fitted_pipeline_.steps[-1][1].coef_` to get the coefficients. However, the output returns 23 coefficient values, whereas the features are only 10.

Can someone help on this, please?

**Comment by perib** [comment]
What does the rest of the pipeline look like? Sometimes transformers, feature unions, or stackingestimators increase the number of features.
