### ISSUE TITLE
How to apply groupKfold in classification

### ISSUE THREAD

**Issue by talhaanwarch** [EpistasisLab/tpot#1279]
Hi. I am trying to do groupkfold cross validation when applying TPOTClassifier.
This is the data
```
X_train=np.random.rand(100,5)
y_train=np.concatenate((np.ones(50),np.zeros(50)))
groups=np.concatenate((np.zeros(25),np.ones(25),np.ones(50)*2,np.ones(50)*3))
```
This is how i applied classifier
```
pipeline_optimizer = TPOTClassifier(generations=5, population_size=20, cv=GroupKFold(5),
                                    random_state=42, verbosity=2)
pipeline_optimizer.fit(X_train, y_train,groups=groups)
```
But this is giving error
```
RuntimeError: A pipeline has not yet been optimized. Please call fit() first.
```

**Comment by niklastoe** [comment]
There are two issues:

1. The list `groups` is too long, i.e. `len(X_train) == 100` but `len(groups) == 150`. Change it to e.g. `groups=np.concatenate((np.zeros(25),np.ones(25),np.ones(25)*2,np.ones(25)*3))`
2. There are 4 groups but you attempt to do a 5-fold group split. That's not possible. Do a 4-fold split (or less).

The error message unfortunatly isn't helpful here.
