### ISSUE TITLE
It raises AttributeError

### ISSUE THREAD

**Issue by abdullahkavakli** [EpistasisLab/tpot#1295]
In numpy 1.24.2 (Python 3.9.16), it raises AttributeError when importing the module. If you want to get same error just run this:
```python
from tpot import TPOTClassifier
```
One fix was suggested here: https://github.com/EpistasisLab/tpot/pull/1292
Full error is down below: 

AttributeError: module 'numpy' has no attribute 'float'. `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here. The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by thecasual** [comment]
I am getting the same error

**Comment by abdullahkavakli** [comment]
@thecasual for temporarily solution, u can change the source code in ur files

**Comment by perib** [comment]
fixed with #1280
