### ISSUE TITLE
Doc pages do not have release notes for 0.12

### ISSUE THREAD

**Issue by PGijsbers** [EpistasisLab/tpot#1302]
Congrats on the 0.12 release :) when visiting http://epistasislab.github.io/tpot/releases/ there is no mention of the release, however.
The notes from https://github.com/EpistasisLab/tpot/releases/tag/v0.12.0 should probably be added to those release notes as well.

**Comment by jay-m-dev** [comment]
Thank you PGijsbers!
We have updated the release page.
