### ISSUE TITLE
How can I be part of the project to develop new modules?

### ISSUE THREAD

**Issue by JoelUser** [EpistasisLab/tpot#1323]
I am interested in how to be part of the project, I am a master's student and I would like to learn how to add new functions to TPOT, but for that I would like to learn to know the code inside. How can I start, is there a guide because the code itself is too big to understand. Thanks for your time

**Comment by perib** [comment]
We have shifted development towards TPOT2 (found here https://github.com/EpistasisLab/tpot2). I wrote a quick description about it in this issue #1322 .

Hopefully the new version is easier to understand. We welcome any feedback on what we have so far! If you think that something could be better organized, clearer, or better implemented, feel free to let us know by opening an issue or pull request. 

 The [Tutorials folder](https://github.com/EpistasisLab/tpot2/tree/main/Tutorial) is a good place to start to get a sense of basic features/functionality. Then the [BaseEvolver](https://github.com/EpistasisLab/tpot2/blob/main/tpot2/evolvers/base_evolver.py#L24) contains all the logic for the evolution of individuals. And the [estimator class](https://github.com/EpistasisLab/tpot2/blob/main/tpot2/tpot_estimator/estimator.py) basically wraps everything in an sklearn estimator format. 

Feel free to contact me with specific questions

**Comment by JoelUser** [comment]
I would like to resolve some particular questions, but I would like to have an email to have a more personal conversation.
My email is: joel.frank.hq@gmail.com
