### ISSUE TITLE
Unable to install pip ARM64 Mac

### ISSUE THREAD

**Issue by aayest** [EpistasisLab/tpot#1334]
(base) aa@Alejandros-MacBook-Pro ~ % pip install deap
Collecting deap
  Using cached deap-1.4.1.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in ./anaconda3/lib/python3.11/site-packages (from deap) (1.23.5)
Building wheels for collected packages: deap
  Building wheel for deap (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [133 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.1-arm64-cpython-311
      creating build/lib.macosx-11.1-arm64-cpython-311/deap
      copying deap/cma.py -> build/lib.macosx-11.1-arm64-cpython-311/deap
      copying deap/algorithms.py -> build/lib.macosx-11.1-arm64-cpython-311/deap
      copying deap/gp.py -> build/lib.macosx-11.1-arm64-cpython-311/deap
      copying deap/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/deap
      copying deap/creator.py -> build/lib.macosx-11.1-arm64-cpython-311/deap
      copying deap/base.py -> build/lib.macosx-11.1-arm64-cpython-311/deap
      creating build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/emo.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/constraint.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/support.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/mutation.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/indicator.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/crossover.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/selection.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/init.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/migration.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      creating build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks
      copying deap/benchmarks/binary.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks
      copying deap/benchmarks/gp.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks
      copying deap/benchmarks/tools.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks
      copying deap/benchmarks/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks
      copying deap/benchmarks/movingpeaks.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks
      creating build/lib.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume
      copying deap/tools/_hypervolume/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume
      copying deap/tools/_hypervolume/pyhv.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume
      running build_ext
      building 'deap.tools._hypervolume.hv' extension
      creating build/temp.macosx-11.1-arm64-cpython-311
      creating build/temp.macosx-11.1-arm64-cpython-311/deap
      creating build/temp.macosx-11.1-arm64-cpython-311/deap/tools
      creating build/temp.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/aa/anaconda3/include -arch arm64 -fPIC -O2 -isystem /Users/aa/anaconda3/include -arch arm64 -I/Users/aa/anaconda3/include/python3.11 -c deap/tools/_hypervolume/_hv.c -o build/temp.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/_hv.o
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/aa/anaconda3/include -arch arm64 -fPIC -O2 -isystem /Users/aa/anaconda3/include -arch arm64 -I/Users/aa/anaconda3/include/python3.11 -c deap/tools/_hypervolume/hv.cpp -o build/temp.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/hv.o
      clang++ -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/aa/anaconda3/lib -L/Users/aa/anaconda3/lib -Wl,-rpath,/Users/aa/anaconda3/lib -L/Users/aa/anaconda3/lib build/temp.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/_hv.o build/temp.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/hv.o -o build/lib.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/hv.cpython-311-darwin.so
      ld: warning: duplicate -rpath '/Users/aa/anaconda3/lib' ignored
      /Users/aa/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
      
              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.
      
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      
      !!
        self.initialize_options()
      installing to build/bdist.macosx-11.1-arm64/wheel
      running install
      running install_lib
      creating build/bdist.macosx-11.1-arm64
      creating build/bdist.macosx-11.1-arm64/wheel
      creating build/bdist.macosx-11.1-arm64/wheel/deap
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/cma.py -> build/bdist.macosx-11.1-arm64/wheel/deap
      creating build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/emo.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/constraint.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/support.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/mutation.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/indicator.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/__init__.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      creating build/bdist.macosx-11.1-arm64/wheel/deap/tools/_hypervolume
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/__init__.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools/_hypervolume
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/hv.cpython-311-darwin.so -> build/bdist.macosx-11.1-arm64/wheel/deap/tools/_hypervolume
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/pyhv.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools/_hypervolume
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/crossover.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/selection.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/init.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/migration.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/algorithms.py -> build/bdist.macosx-11.1-arm64/wheel/deap
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/gp.py -> build/bdist.macosx-11.1-arm64/wheel/deap
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/__init__.py -> build/bdist.macosx-11.1-arm64/wheel/deap
      creating build/bdist.macosx-11.1-arm64/wheel/deap/benchmarks
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks/binary.py -> build/bdist.macosx-11.1-arm64/wheel/deap/benchmarks
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks/gp.py -> build/bdist.macosx-11.1-arm64/wheel/deap/benchmarks
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks/tools.py -> build/bdist.macosx-11.1-arm64/wheel/deap/benchmarks
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks/__init__.py -> build/bdist.macosx-11.1-arm64/wheel/deap/benchmarks
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks/movingpeaks.py -> build/bdist.macosx-11.1-arm64/wheel/deap/benchmarks
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/creator.py -> build/bdist.macosx-11.1-arm64/wheel/deap
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/base.py -> build/bdist.macosx-11.1-arm64/wheel/deap
      running install_egg_info
      running egg_info
      writing deap.egg-info/PKG-INFO
      writing dependency_links to deap.egg-info/dependency_links.txt
      writing requirements to deap.egg-info/requires.txt
      writing top-level names to deap.egg-info/top_level.txt
      reading manifest file 'deap.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.hpp' under directory 'deap'
      warning: no files found matching '*.h' under directory 'examples'
      no previously-included directories found matching 'doc/_build'
      warning: no previously-included files matching '.DS_Store' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      adding license file 'LICENSE.txt'
      writing manifest file 'deap.egg-info/SOURCES.txt'
      Copying deap.egg-info to build/bdist.macosx-11.1-arm64/wheel/deap-1.4.1-py3.11.egg-info
      running install_scripts
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/js/ftcwjzw169b5lwlcwmwrnv640000gn/T/pip-install-obf3wnaw/deap_d7b30e29af9d48e1a9e1d64e52231964/setup.py", line 93, in <module>
          run_setup(True)
        File "/private/var/folders/js/ftcwjzw169b5lwlcwmwrnv640000gn/T/pip-install-obf3wnaw/deap_d7b30e29af9d48e1a9e1d64e52231964/setup.py", line 63, in run_setup
          setup(name='deap',
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 328, in run
          impl_tag, abi_tag, plat_tag = self.get_tag()
                                        ^^^^^^^^^^^^^^
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
          assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
                 ^^^^^^^^^^^^^^^^^^^^^
      AssertionError: would build wheel with unsupported tag ('cp311', 'cp311', 'macosx_11_1_arm64')
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for deap
  Running setup.py clean for deap
Failed to build deap
ERROR: Could not build wheels for deap, which is required to install pyproject.toml-based projects

**Comment by perib** [comment]
I do not have a mac with the new processors, but I'll ask people on the team who do to test this out. 

In the meantime you could try the next version of TPOT, TPOT2 which can be found here: https://github.com/EpistasisLab/tpot2

This version does not use the deap package and has been working for people on our team with newer Macs.

**Comment by perib** [comment]
We were able to install this on a Mac with the new processor. 

I would recommend trying to install Deap/tpot using conda rather than pip.

**Comment by aayest** [comment]
I wonder who did you make this work?

Last login: Thu Dec  7 20:09:33 on ttys000
(base) ***@***.*** ~ % conda install tpot
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - tpot

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


(base) ***@***.*** ~ % pip install tpot
Collecting tpot
  Using cached TPOT-0.12.1-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: numpy>=1.16.3 in ./anaconda3/lib/python3.11/site-packages (from tpot) (1.23.5)
Requirement already satisfied: scipy>=1.3.1 in ./anaconda3/lib/python3.11/site-packages (from tpot) (1.11.1)
Requirement already satisfied: scikit-learn>=0.22.0 in ./anaconda3/lib/python3.11/site-packages (from tpot) (1.3.0)
Collecting deap>=1.2 (from tpot)
  Using cached deap-1.4.1.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
Collecting update-checker>=0.16 (from tpot)
  Using cached update_checker-0.18.0-py3-none-any.whl (7.0 kB)
Requirement already satisfied: tqdm>=4.36.1 in ./anaconda3/lib/python3.11/site-packages (from tpot) (4.65.0)
Collecting stopit>=1.1.1 (from tpot)
  Using cached stopit-1.1.2-py3-none-any.whl
Requirement already satisfied: pandas>=0.24.2 in ./anaconda3/lib/python3.11/site-packages (from tpot) (2.0.3)
Requirement already satisfied: joblib>=0.13.2 in ./anaconda3/lib/python3.11/site-packages (from tpot) (1.2.0)
Requirement already satisfied: xgboost>=1.1.0 in ./anaconda3/lib/python3.11/site-packages (from tpot) (1.7.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./anaconda3/lib/python3.11/site-packages (from pandas>=0.24.2->tpot) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./anaconda3/lib/python3.11/site-packages (from pandas>=0.24.2->tpot) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in ./anaconda3/lib/python3.11/site-packages (from pandas>=0.24.2->tpot) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./anaconda3/lib/python3.11/site-packages (from scikit-learn>=0.22.0->tpot) (2.2.0)
Requirement already satisfied: requests>=2.3.0 in ./anaconda3/lib/python3.11/site-packages (from update-checker>=0.16->tpot) (2.31.0)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=0.24.2->tpot) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./anaconda3/lib/python3.11/site-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in ./anaconda3/lib/python3.11/site-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./anaconda3/lib/python3.11/site-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.11/site-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (2023.11.17)
Using cached TPOT-0.12.1-py3-none-any.whl (87 kB)
Building wheels for collected packages: deap
  Building wheel for deap (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [133 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.1-arm64-cpython-311
      creating build/lib.macosx-11.1-arm64-cpython-311/deap
      copying deap/cma.py -> build/lib.macosx-11.1-arm64-cpython-311/deap
      copying deap/algorithms.py -> build/lib.macosx-11.1-arm64-cpython-311/deap
      copying deap/gp.py -> build/lib.macosx-11.1-arm64-cpython-311/deap
      copying deap/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/deap
      copying deap/creator.py -> build/lib.macosx-11.1-arm64-cpython-311/deap
      copying deap/base.py -> build/lib.macosx-11.1-arm64-cpython-311/deap
      creating build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/emo.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/constraint.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/support.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/mutation.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/indicator.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/crossover.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/selection.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/init.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      copying deap/tools/migration.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools
      creating build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks
      copying deap/benchmarks/binary.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks
      copying deap/benchmarks/gp.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks
      copying deap/benchmarks/tools.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks
      copying deap/benchmarks/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks
      copying deap/benchmarks/movingpeaks.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks
      creating build/lib.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume
      copying deap/tools/_hypervolume/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume
      copying deap/tools/_hypervolume/pyhv.py -> build/lib.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume
      running build_ext
      building 'deap.tools._hypervolume.hv' extension
      creating build/temp.macosx-11.1-arm64-cpython-311
      creating build/temp.macosx-11.1-arm64-cpython-311/deap
      creating build/temp.macosx-11.1-arm64-cpython-311/deap/tools
      creating build/temp.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/aa/anaconda3/include -arch arm64 -fPIC -O2 -isystem /Users/aa/anaconda3/include -arch arm64 -I/Users/aa/anaconda3/include/python3.11 -c deap/tools/_hypervolume/_hv.c -o build/temp.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/_hv.o
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/aa/anaconda3/include -arch arm64 -fPIC -O2 -isystem /Users/aa/anaconda3/include -arch arm64 -I/Users/aa/anaconda3/include/python3.11 -c deap/tools/_hypervolume/hv.cpp -o build/temp.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/hv.o
      clang++ -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/aa/anaconda3/lib -L/Users/aa/anaconda3/lib -Wl,-rpath,/Users/aa/anaconda3/lib -L/Users/aa/anaconda3/lib build/temp.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/_hv.o build/temp.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/hv.o -o build/lib.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/hv.cpython-311-darwin.so
      ld: warning: duplicate -rpath '/Users/aa/anaconda3/lib' ignored
      /Users/aa/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
      
              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.
      
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      
      !!
        self.initialize_options()
      installing to build/bdist.macosx-11.1-arm64/wheel
      running install
      running install_lib
      creating build/bdist.macosx-11.1-arm64
      creating build/bdist.macosx-11.1-arm64/wheel
      creating build/bdist.macosx-11.1-arm64/wheel/deap
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/cma.py -> build/bdist.macosx-11.1-arm64/wheel/deap
      creating build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/emo.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/constraint.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/support.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/mutation.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/indicator.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/__init__.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      creating build/bdist.macosx-11.1-arm64/wheel/deap/tools/_hypervolume
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/__init__.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools/_hypervolume
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/hv.cpython-311-darwin.so -> build/bdist.macosx-11.1-arm64/wheel/deap/tools/_hypervolume
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/_hypervolume/pyhv.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools/_hypervolume
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/crossover.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/selection.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/init.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/tools/migration.py -> build/bdist.macosx-11.1-arm64/wheel/deap/tools
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/algorithms.py -> build/bdist.macosx-11.1-arm64/wheel/deap
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/gp.py -> build/bdist.macosx-11.1-arm64/wheel/deap
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/__init__.py -> build/bdist.macosx-11.1-arm64/wheel/deap
      creating build/bdist.macosx-11.1-arm64/wheel/deap/benchmarks
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks/binary.py -> build/bdist.macosx-11.1-arm64/wheel/deap/benchmarks
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks/gp.py -> build/bdist.macosx-11.1-arm64/wheel/deap/benchmarks
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks/tools.py -> build/bdist.macosx-11.1-arm64/wheel/deap/benchmarks
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks/__init__.py -> build/bdist.macosx-11.1-arm64/wheel/deap/benchmarks
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/benchmarks/movingpeaks.py -> build/bdist.macosx-11.1-arm64/wheel/deap/benchmarks
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/creator.py -> build/bdist.macosx-11.1-arm64/wheel/deap
      copying build/lib.macosx-11.1-arm64-cpython-311/deap/base.py -> build/bdist.macosx-11.1-arm64/wheel/deap
      running install_egg_info
      running egg_info
      writing deap.egg-info/PKG-INFO
      writing dependency_links to deap.egg-info/dependency_links.txt
      writing requirements to deap.egg-info/requires.txt
      writing top-level names to deap.egg-info/top_level.txt
      reading manifest file 'deap.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.hpp' under directory 'deap'
      warning: no files found matching '*.h' under directory 'examples'
      no previously-included directories found matching 'doc/_build'
      warning: no previously-included files matching '.DS_Store' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      adding license file 'LICENSE.txt'
      writing manifest file 'deap.egg-info/SOURCES.txt'
      Copying deap.egg-info to build/bdist.macosx-11.1-arm64/wheel/deap-1.4.1-py3.11.egg-info
      running install_scripts
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/js/ftcwjzw169b5lwlcwmwrnv640000gn/T/pip-install-e452kuqm/deap_166390cb0d4c47a2baf2fe5a6e973c89/setup.py", line 93, in <module>
          run_setup(True)
        File "/private/var/folders/js/ftcwjzw169b5lwlcwmwrnv640000gn/T/pip-install-e452kuqm/deap_166390cb0d4c47a2baf2fe5a6e973c89/setup.py", line 63, in run_setup
          setup(name='deap',
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 328, in run
          impl_tag, abi_tag, plat_tag = self.get_tag()
                                        ^^^^^^^^^^^^^^
        File "/Users/aa/anaconda3/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
          assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
                 ^^^^^^^^^^^^^^^^^^^^^
      AssertionError: would build wheel with unsupported tag ('cp311', 'cp311', 'macosx_11_1_arm64')
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for deap
  Running setup.py clean for deap
Failed to build deap
ERROR: Could not build wheels for deap, which is required to install pyproject.toml-based projects
(base) ***@***.*** ~ % 

Are you sure you are using an ARM Mac?

(base) ***@***.*** ~ % uname -a
Darwin Alejandros-MacBook-Pro.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 arm64

Thanks,
AA
__
Alejandro Ayestaran
***@***.***

**Comment by perib** [comment]
to install via conda, you need to include the conda-forge channel.

Here is the command:

`conda install -c conda-forge tpot`

**Comment by aayest** [comment]
Okay, that worked !

Thanks Pedro.
AA
__
Alejandro Ayestaran
***@***.***
