### ISSUE TITLE
Add TPOT to Conda Forge

### ISSUE THREAD

**Issue by rhiever** [EpistasisLab/tpot#165]
@tonyfast, I wanted to get this conversation rolling, so I figured I'd start an issue for it.

With what you know about TPOT, how do you advise we get it added to Conda Forge?

**Comment by tonyfast** [comment]
@bollwyvl do you have some resources to get us started?

**Comment by bollwyvl** [comment]
Welp. Basically we have to track down all the pypi-only deps (and deps of deps) we'll need first.... bundling is bad practice.

DEAP has been built before, so should be easy. XGBoost might be trickier. Hopefully, it's gcc deps aren't that bad.

I prefer to get all the tests running for each lib. If this has pypi deps, that's okay.

Finally we can write the actual tpot recipe.

Hopefully, we can bring them all along in one pr to staged-recipes.... i did one with like six, which was too many. Either way, we'll end up with a number of feedstocks.

I am happy to start the process, having now done it a couple of times! I'll get some wifi on my flight, hopefully have something going soon!

**Comment by rhiever** [comment]
In v0.4 (coming soon), we've dropped XGBoost as a hard dependency. So that won't be an issue soon. That's good news about DEAP.

**Comment by bollwyvl** [comment]
I started here:
- https://github.com/bollwyvl/staged-recipes/tree/tpot


### deap
I am trying to get its compiled stuff building (hypervolume), starting on OSX (as it's what I've got locally, and often causes the most problems... well, aside from windows).

The tests distributed with the current pypi version are broken... so for the time being I'm building against `master`. It would be nice if we could work with them to get a release out in concert with tpot 0.4... seems a bit overdue!

### xgboost
> we've dropped XGBoost as a hard dependency

Will it use it if available? Does it make tpot better/faster/stronger? If so, it might be worth it to go ahead and bet it built. There are a number of builds of it out on [anaconda.org](https://anaconda.org/search?q=xgboost), so we'll have some places to start.

**Comment by rhiever** [comment]
The DEAP devs seem to have the project in an odd state where they've written the code in Python 2.7 and use `2to3` to convert it to a Python 3-compatible version when it's installed on a Python 3 distribution. Not sure why they do that, really.

We have #154 to make XGBoost an optional dependency, but it likely won't be coming out in v0.4.

**Comment by bollwyvl** [comment]
> use 2to3 to convert it to a Python 3-compatible version when it's installed on a Python 3 distribution

Heh, that part works, at least. But the tests are just straight up busted.

**Comment by bollwyvl** [comment]
Sorry for the delay: got confused by the future state of DEAP on master, which had a c extension, etc. Turns out, in its current form, `1.0.2.post2`, DEAP is pretty straightforward, so I imagine it will work the first time! I've done a bit more research about xgboost: doable, but maybe not pretty.

**Comment by bollwyvl** [comment]
So we've gotten this merged (some time ago) over on:

https://github.com/conda-forge/tpot-feedstock

Currently seeing some test fails in the rebuild of [0.9.5](https://github.com/conda-forge/tpot-feedstock/pull/11) that updates to point at EpistasisLab, perhaps due to some drift in the dependencies:
https://travis-ci.org/conda-forge/tpot-feedstock/jobs/438036423#L1101

I'm going to skip the offending tests:
```
nosetests tests --exclude test_StackingEstimator_4 --exclude test_score_3 --exclude test_sample_weight_func
```

But it might be worth taking a look!

**Comment by raybellwaves** [comment]
What's the status on this?
Looking at https://anaconda.org/conda-forge/tpot it seems like a viable option.
Should I update the docs (https://epistasislab.github.io/tpot/installing/)?

**Comment by bollwyvl** [comment]
Sure, go ahead! We've been shipping from cf for several years at this
point, and have multiple maintainers, so I'd say it's as good as any a
source! If you have any additional concerns, please raise them in the
feedstock!

https://github.com/conda-forge/tpot-feedstock

**Comment by raybellwaves** [comment]
@bollwyvl Will do. Welcome to close this as i'm moving the convo to #1005
