### ISSUE TITLE
Export TPOT pipelines to Orange file format

### ISSUE THREAD

**Issue by rhiever** [EpistasisLab/tpot#51]
[Orange](http://orange.biolab.si/) has a pretty nice interface for building sklearn pipelines in a GUI.

![image](https://cloud.githubusercontent.com/assets/1719223/11642314/4e581870-9d0b-11e5-84eb-d50f2a023a3f.png)

It'd be great to have a function that exports TPOT pipelines into a file format that can be opened with Orange.

I've contacted the Orange devs and they said that it should be relatively straightforward to accomplish this _as long as Orange has each TPOT pipeline operator already implemented as an Orange widget_.

I'd imagine a good first step would be to thoroughly explore the Orange software and see what widgets/pipeline operators they already have implemented.

---

Here's an example Orange file:

``` xml
<?xml version='1.0' encoding='utf-8'?>
<scheme description="" title="" version="2.0">
    <nodes>
        <node id="0" name="File" position="(150, 150)" project_name="Orange" qualified_name="Orange.widgets.data.owfile.OWFile" title="File" version="" />
        <node id="1" name="Data Info" position="(319.0, 77.0)" project_name="Orange" qualified_name="Orange.widgets.data.owdatainfo.OWDataInfo" title="Data Info" version="" />
        <node id="2" name="Test &amp; Score" position="(318.0, 209.0)" project_name="Orange" qualified_name="Orange.widgets.evaluate.owtestlearners.OWTestLearners" title="Test &amp; Score" version="" />
        <node id="3" name="Logistic Regression" position="(162.0, 324.0)" project_name="Orange" qualified_name="Orange.widgets.classify.owlogisticregression.OWLogisticRegression" title="Logistic Regression" version="" />
    </nodes>
    <links>
        <link enabled="true" id="0" sink_channel="Data" sink_node_id="1" source_channel="Data" source_node_id="0" />
        <link enabled="true" id="1" sink_channel="Data" sink_node_id="2" source_channel="Data" source_node_id="0" />
        <link enabled="true" id="2" sink_channel="Learner" sink_node_id="2" source_channel="Learner" source_node_id="3" />
    </links>
</scheme>
```

**Comment by brylie** [comment]
@rhiever really cool idea. See also #137, as the ideas are pretty closely related.

**Comment by brylie** [comment]
Is this closed as "won't fix"? Just curious.

**Comment by weixuanfu** [comment]
Yes, this is not in our dev plan.
