### ISSUE TITLE
Nested cross validation

### ISSUE THREAD

**Issue by crawles** [EpistasisLab/tpot#554]
Utilizing [nested cross validation](https://sebastianraschka.com/faq/docs/evaluate-a-model.html) would give a less biased view of the best (i.e. chosen) pipeline performance as then the framework is not using the test folds for pipeline selection and pipeline evaluation. It shouldn't affect the search optimization process for the optimal pipeline/parameters, but it would give a better estimate of the final pipeline's performance. 

The downside is, for 5 fold cross validation, this would result in 5x computational cost (25 iterations) as a result from the inner and outer loop. Not sure if it would be worth the large computational increase. This is also more of an issue for smaller datasets as well. 

I just wanted to raise this issue and bring it to light.

This [paper](http://jmlr.org/papers/volume11/cawley10a/cawley10a.pdf) gives an overview of the subject.

**Comment by rhiever** [comment]
Thank you for raising this issue, @crawles. We have been considering nested CV since the early inception of TPOT, however as you mentioned, the computational cost is much higher. For that reason, we've avoided nested CV because AutoML tools are already slow by using CV.

Perhaps a formal evaluation of TPOT with and without nested CV is in order. It could be good to see if nested CV would lead to different pipelines, or if it doesn't matter at all in AutoML. Thoughts, @weixuanfu @teaearlgraycold?

**Comment by weixuanfu** [comment]
[A comparison in scikit-learn doc](http://scikit-learn.org/stable/auto_examples/model_selection/plot_nested_cross_validation_iris.html)

**Comment by weixuanfu** [comment]
From the [link](http://scikit-learn.org/stable/tutorial/statistical_inference/model_selection.html#grid-search-and-cross-validated-estimators), tpot uses `cross_val_score` for nested CV, right?

**Comment by danthedaniel** [comment]
Regardless of its effects on bias, it should probably be an optional feature.

**Comment by rhiever** [comment]
How would nested CV even be implemented in TPOT? After thinking about it for a bit, to implement nested CV we would need to do the following:

1) initially split the training data into k training folds

2) start up *k* GP populations, where each population corresponds to a training fold group

3) TPOT runs like regular on each training fold group, using the 10-fold CV score on the training fold to select the best pipeline(s)

4) after all *k* populations are finished evolving, use the holdout fold for each population to report the "true" best pipeline score to pick the overall best pipeline

It sounds that implementing nested CV in TPOT would be convoluted and much more expensive than the current TPOT process.

**Comment by crawles** [comment]
@rhiever that's exactly how I would envision it. It would be adding an outer cv loop over TPOT.

Something tricky about the approach is in step 4, there could very possibly be k different best pipelines chosen from each run of TPOT. This may be nice though because it would give you a sense of the stability of the chosen model– e.g., if in fact k different model/hyperparameters are chosen and very different it would tell you TPOT hasn't converged. 

You could return all the unique models from the outer cv or if there are less than k models chosen you could do a majority vote as the best model.

And agreed, it would be much more computationally expensive.

**Comment by rhiever** [comment]
After thinking about it some more, an outer CV loop can already be obtained for TPOT by passing TPOT as the `clf` in the sklearn `cross_val_score` function. Essentially achieves the same as steps 1-4 in my comment above, although I don't think we would be able to inspect the best pipelines at the end as wisely suggested by @crawles.

**Comment by crawles** [comment]
Good point using `cross_val_score`

**Comment by rhiever** [comment]
Closing this issue. Please feel free to re-open or file a new issue if you have any further comments.
