### ISSUE TITLE
How to optimize for the AUC

### ISSUE THREAD

**Issue by lesshaste** [EpistasisLab/tpot#559]
Taking the simple MNIST digit recognition as an example, how would you optimize for the AUC using TPOT? In my case my data will be imbalanced so this is the best measure.

## Context of the issue

I would like to use TPOT to find a good classifier for an imbalanced data set. How can I get TPOT to optimize for the AUC?

**Comment by weixuanfu** [comment]
You can pass in ['roc_auc'](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html#sklearn.metrics.roc_auc_score) to the `scoring` parameter in `TPOTClassifier` for using AUC. More metrics can be found in this [link](http://scikit-learn.org/stable/modules/model_evaluation.html). I will update [TPOT documentation](https://rhiever.github.io/tpot/using/#scoring-functions) for adding more details about metrics.

**Comment by rhiever** [comment]
@weixuanfu, the scoring functions are documented in the [TPOT API](https://rhiever.github.io/tpot/api/).

**Comment by weixuanfu** [comment]
@rhiever I saw that, but I think maybe the [sklearn link](http://scikit-learn.org/stable/modules/model_evaluation.html) could be a better reference for TPOT documentation about scoring function
