### ISSUE TITLE
Does `tpot` support large data set such as billion instances and million features

### ISSUE THREAD

**Issue by formath** [EpistasisLab/tpot#567]

**Comment by weixuanfu** [comment]
It might be extremely slow to run TPOT in such a big dataset. For the case, I highly suggest to:

1. Set`n_jobs=1` for TPOT object and make sure there are enough RAM to avoid memory issue;
2. Use [`TPOT light`](http://rhiever.github.io/tpot/using/#built-in-tpot-configurations) configuration;
3. Apply [MDR](https://en.m.wikipedia.org/wiki/Multifactor_dimensionality_reduction) or other features selection/dimension reduction algorithms for reducing feature numbers before using TPOT.

@rhiever

**Comment by rhiever** [comment]
As TPOT is based on scikit-learn, it supports large-scale ML about as well as scikit-learn does (i.e., not great). My recommendation is to look into ML packages based on TensorFlow and/or that have GPU support to scale ML to that size of data.
