### ISSUE TITLE
Fix support for sparse matrices

### ISSUE THREAD

**Issue by rhiever** [EpistasisLab/tpot#568]
Add a check [here](https://github.com/rhiever/tpot/blob/4549a6fe1c7f54d2634500b24dfc473f88a4548c/tpot/base.py#L500) for whether `features` is a sparse matrix. If `features` is a sparse matrix, do not apply imputation.

Add a unit test that generates a small random matrix with values 0, 1, and 2. Apply our OHE to it, then make sure TPOT properly handles it as input.

Also, remove `axis=0` on [this line](https://github.com/rhiever/tpot/blob/4549a6fe1c7f54d2634500b24dfc473f88a4548c/tpot/base.py#L917) -- this doesn't break sparse matrix support, but it's not necessary.

**Comment by jinwangjoshua** [comment]
really important
