### ISSUE TITLE
Scoring: Use also the current fitted/tested estimator as first param?

### ISSUE THREAD

**Issue by Damian89** [EpistasisLab/tpot#579]
Hi guys,

it may be a good Idea to add the estimator as the first parameter of your own scoring function. Take a look at GridSearchCV where a custom scoring function has the params (clf, x_test, y_true).

Currently I'm able to create a custom callable for tpot with two params: 
def my_scorer(X, y):

What do you think? Is there currently a way to use the estimator within my own scoring function?

Best regards,

Damian

**Comment by rhiever** [comment]
Hi @Damian89, can you please provide a code example of what this would look like if you were to pass such as a custom scoring function directly to sklearn's `cross_val_score` function? Essentially, we pass the contents of TPOT's `scoring` parameter directly to the `cross_val_score` function. Thus if it's possible to pass such a function to `cross_val_score`, then it's possible to pass it to TPOT's `scoring` parameter.

**Comment by Damian89** [comment]
I can give you one of my current examples (written today, working perfectly with keras and sklearns GridSearchCV:

```Python
grid = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    n_jobs=-1,
    cv=ShuffleSplit(n_splits=1,test_size=1, random_state=42),
    scoring=my_scorer`
)
```

There's my custom function "my_scorer":

```Python
def my_scorer(clf, X, y):
    y_predicted_probability = clf.predict_proba(X_validation)
    # Calculation with other (global) data
    # Check probability against known y_validation, calculating logloss...
    return some_new_float
```

As you can see in my case I dont need X andy from the cross validation dataset, I have my own X_validation which currently is a global array. Thats fine.
What I need TPOT to do is to use the current classifier/model and test it against my own global validation set (calculating some metrics and also doing some heavywork writing and comparing files created using the current clf and based on this comparision results the clf is weighted)

Maybe theres another way to accomplish my goal, I didnt test croll_val_score but it looks like it also possible to use a custom callable with the following params:
scorer(estimator, X, y)
See: [http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html](url)

**Comment by rhiever** [comment]
It looks like this could be supported if we changed how TPOT takes custom functions as input. Currently we assume that all functions being passed to `scoring` will have only `y_true` and `y_pred` as the parameters: [link](https://github.com/rhiever/tpot/blob/ac7f18cd3f33cc4b5e8318132a2ed22bd4d31122/tpot/base.py#L306)

but that whole functionality passes the user-provided scoring function to the `make_scorer` function, which makes a function with the signature `my_scorer(clf, X, y)`.

Thus, we should change the processing of the `scoring` input to allow a function with the signature `my_scorer(clf, X, y)` as well. I'll change this issue to an enhancement issue and endeavor to have this change out in the next release.

Sorry for the long time to response. I didn't get a notification about this issue for some reason.

**Comment by rhiever** [comment]
@Damian89, check the [development branch of TPOT](https://github.com/rhiever/tpot/tree/development). It now has support for a scoring function as you described.

**Comment by Damian89** [comment]
Hmm...
I'm running the current 0.9.1 (installed via pip using developement branch) and have the following code:

```
tpot = TPOTClassifier(
    generations=5,
    population_size=4,
    verbosity=2,
    n_jobs=-1,
    random_state=42,
    periodic_checkpoint_folder=workfolder + "top_classifiers",
    scoring=my_scorer
)
```

my_scorer is defined as:

```
def my_scorer(clf,X,y):
   ... code
   return a_float_value
```

This is the way it works flawless with GridSearchCV:

```
model = RandomizedSearchCV(
    ensemble.GradientBoostingClassifier(random_state=42),
    param_distributions=param_dist,
    scoring=my_scorer,
    n_jobs=-1,
)
```

Seems not to work with tpot, all I get is the following error:

> /usr/local/lib/python3.5/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
>   "This module will be removed in 0.20.", DeprecationWarning)
> /home/damian/Projekte (Python)/NMR-Projekt/src/dev/tpot/base.py:362: DeprecationWarning: Scoring function <function my_scorer at 0x7f63f608eea0> looks like it is a metric function rather than a scikit-learn scorer. This scoring type was deprecated in version TPOT 0.9.1 and will be removed in version 0.11. Please update your custom scoring function.
>   'Please update your custom scoring function.'.format(scoring), DeprecationWarning)
> Traceback (most recent call last):
>   File "/home/damian/Projekte (Python)/NMR-Projekt/src/dev/tpot/base.py", line 617, in fit
>     per_generation_function=self._check_periodic_pipeline
>   File "/home/damian/Projekte (Python)/NMR-Projekt/src/dev/tpot/gp_deap.py", line 245, in eaMuPlusLambda
>     per_generation_function()
>   File "/home/damian/Projekte (Python)/NMR-Projekt/src/dev/tpot/base.py", line 904, in _check_periodic_pipeline
>     self._update_top_pipeline()
>   File "/home/damian/Projekte (Python)/NMR-Projekt/src/dev/tpot/base.py", line 696, in _update_top_pipeline
>     raise RuntimeError('There was an error in the TPOT optimization '
> RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/damian/Projekte (Python)/NMR-Projekt/modelselect-tpot.py", line 206, in <module>
>     tpot.fit(X_train, y_train)
>   File "/home/damian/Projekte (Python)/NMR-Projekt/src/dev/tpot/base.py", line 649, in fit
>     raise e
>   File "/home/damian/Projekte (Python)/NMR-Projekt/src/dev/tpot/base.py", line 640, in fit
>     self._update_top_pipeline()
>   File "/home/damian/Projekte (Python)/NMR-Projekt/src/dev/tpot/base.py", line 696, in _update_top_pipeline
>     raise RuntimeError('There was an error in the TPOT optimization '
> RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly.
> 
> Process finished with exit code 1


Do you have any ideas?

**Comment by weixuanfu** [comment]
OK, I think this is because the scoring function is not a instance of [`_BaseScorer`](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/metrics/scorer.py#L46), which can be easily built with [`make_scorer`](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.make_scorer.html)

I think I need refine [this line](https://github.com/rhiever/tpot/blob/development/tpot/base.py#L352) for letting TPOT to tell whether it is a scoring function with estimator as first argument instead.

**Comment by weixuanfu** [comment]
@Damian89 I just submitted the PR #607 for this fix. You may try to install the branch with the commend below for a test:

```
pip install --upgrade --no-deps --force-reinstall git+https://github.com/weixuanfu/tpot.git@scoring_api
```

**Comment by Damian89** [comment]
Awesome! It works.

**Comment by rhiever** [comment]
Merged into dev branch now. Release coming soon.
