### ISSUE TITLE
CV score differs from manually calculated score

### ISSUE THREAD

**Issue by saddy001** [EpistasisLab/tpot#583]
Hi,
Currently I'm evaluating a TPOT classifier with a single CV split like the following:
```
model = TPOTClassifier(
    generations=10, population_size=30, cv=[(train_split, valid_split)], verbosity=2,
    scoring='precision_macro', n_jobs=-1, config_dict='tpot_config_minimal.py')
model.fit(train_matrix, target)
pred = model.predict(train_matrix[valid_split])
print(f'valid mean precision score: {prc(target[valid_split], pred, average="macro"):.2f}')
```

With prc() being the precision_score of sklearn and multilabel targets.

I'm getting the following output:
```
Generation 1 - Current best internal CV score: 0.6930933010212913                                                                                                                                                                       
Generation 2 - Current best internal CV score: 0.6930933010212913                                                                                                                                                                       
Generation 3 - Current best internal CV score: 0.6930933010212913                                                                                                                                                                       
Generation 4 - Current best internal CV score: 0.6930933010212913                                                                                                                                                                       
Generation 5 - Current best internal CV score: 0.6930933010212913                                                                                                                                                                       
Generation 6 - Current best internal CV score: 0.6930933010212913                                                                                                                                                                       
Generation 7 - Current best internal CV score: 0.6933956716066808                                                                                                                                                                       
Generation 8 - Current best internal CV score: 0.7018802797710965                                                                                                                                                                       
Generation 9 - Current best internal CV score: 0.7018802797710965                                                                                                                                                                       
Generation 10 - Current best internal CV score: 0.7018802797710965                                                                                                                                                                      
Best pipeline: KNeighborsClassifier(KNeighborsClassifier(input_matrix, n_neighbors=23, p=2, weights=distance), n_neighbors=63, p=2, weights=uniform)
valid mean precision score: 0.99
```

I would have expected the score .99 to be equal to the last best CV score (.7). 
Am I doing something wrong? Or may the internal CV score use a different metrics than 'precision_macro'?
I hope it is reproducible with arbitrary data. 

Nice framework by the way.

**Comment by saddy001** [comment]
Sorry, somehow the markdown seems to be broken...

**Comment by saddy001** [comment]
PS: I assume, that TPOT doesn't re-fit on the whole set (train and valid) after CV. If it does, that would explain the differing scores.

**Comment by weixuanfu** [comment]
Yes, TPOT refit on the whole set after CV. Another possible reason of the difference is that the pipelines used in CV has the  fixed `random_state` of 42 but `TPOT.fitted_pipeline_`  after optimization process doesn’t

**Comment by rhiever** [comment]
Looking at your code, there seems to be a small issue in it. It looks like you provide the entire dataset for training:

```Python
model.fit(train_matrix, target)
```

then validate on a subset of that dataset:

```Python
pred = model.predict(train_matrix[valid_split])
print(f'valid mean precision score: {prc(target[valid_split], pred, average="macro"):.2f}')
```

After choosing the best pipeline(s), TPOT trains the best pipeline(s) on the training data that was provided to `fit`. Thus, if you've provided the entire dataset to TPOT in `fit`, the best pipeline has already trained on a validation data as well.

You will need to subset `train_matrix` and `target` in the `fit` call above such that you are passing only the training subset to TPOT.

**Comment by saddy001** [comment]
I see, this is what I meant with my comment. I think it would be helpful to mention this in the docs to TPOT.fit().

**Comment by rhiever** [comment]
It is standard procedure in ML to explicitly make a training set that is non-overlapping with the holdout set. We provide [a few examples](http://rhiever.github.io/tpot/examples/) in the docs that use the recommended `train_test_split` function to accomplish that. Hope that helps!

**Comment by saddy001** [comment]
Thanks, I agree that this is a standard procedure, but whether the model is re-fit after CV depends on the implementation. For example sklearn has a parameter "refit" in GridSearchCV() that controls this behavior.

**Comment by rhiever** [comment]
Oh, I see what's going on. We coded TPOT with the assumption that only training data would be passed to `fit`, and that the holdout data would only be seen by TPOT through the `predict` and `score` functions.

We hadn't considered this use case because using such a setup is highly prone to overfitting in our experience. We found early on that using a single train/test split during the optimization process is overfitting-prone, and thus adopted a k-fold CV procedure instead, which helped quite a bit.

Off the top of my head, I'm not sure of an elegant way to handle this use case. It would require some hard-coded logic to handle the single train/test split use case.

**Comment by saddy001** [comment]
Well I'm not using a single split in production but only for testing purposes for the same reasons. Although it would be more comfortable to have a parameter for re-fitting, I'm fine with TPOT handling it this way. All I wanted to say was that the user should be informed about how TPOT handles the data in the fit-function and that the documentation may be the right place for this.

**Comment by rhiever** [comment]
Fair enough. I've filed #589 so we have it on record that we should add that note for the next release. Sorry for the misunderstanding and thank you for the feedback! Please feel free to re-open this issue if you have further comments or questions.
