### ISSUE TITLE
Add a TPOT time series analysis example to the docs

### ISSUE THREAD

**Issue by rhiever** [EpistasisLab/tpot#584]
We should add an example to the docs of TPOT being applied to a time series problem. That could be a helpful starting point for people interested in time series analysis.

(from #582)

**Comment by hristog** [comment]
Hi @rhiever. I would like to work on this, please.

**Comment by weixuanfu** [comment]
@hristog thank you. Please submit a PR for this example.

**Comment by hristog** [comment]
Just a heads-up from me. I still intend to submit a PR regarding the time-series example request, and hopefully (subject to time availability) you'll have the opportunity to review it and provide feedback soon enough.

I like to do things in a ground-up manner and, naturally, I've made sure to attempt to familiarize myself with the project and, specifically, the documentation part, before embarking on contributing with an example.

As part of my acclimation, I've issued #600.

**Comment by weixuanfu** [comment]
I close this issue because the PR #600 was merged. Thank you!
