### ISSUE TITLE
Keeping track of more statistics of individuals

### ISSUE THREAD

**Issue by bartdp1** [EpistasisLab/tpot#585]
TPOT recently got my interest, and i must say i really like it, both from conceptual as well as performance point of view.  To do some in depth analyses on the inner workings and performance of the algorithm, it would be great to have some more statistics on the individuals that TPOT examines along the way. These could for example be added to the '_evaluated_individuals_' attribute, where currently the number of components and the internal cross validation score is available.
For example, interesting things to have available would be:
- Generation of occurrence
- Cumulative number of crossover operations applied to the individual (meaning the number of operations applied to the individual and its predecessors)
- Cumulative number of mutation operations applied to the individual, maybe split per type of mutation
- (List of) String representation(s) of predecessor(s)
And maybe more.
 
For all of the mentioned statistics i think it would be sufficient to know them at the moment a pipeline is encountered for the first time, ignoring when a pipeline might be found again in a later generation.

Although i am not extremely skilled in Python, i want to make an effort (and try) to implement this myself, so i dove into the structure of TPOT and DEAP a bit. I was thinking about maintaining and updating the statistics in the individual objects themselves as attributes, updating them with crossover, mutation and precedence operations, and write them to the '_evaluated_individuals_' dict upon evaluation of the individuals. This would result in the '_evaluated_individuals_' begin similar to what it is currently, just with an expanded statistics tuple.

I'm curious about what you think of the idea, and about the proposed implementation.

**Comment by rhiever** [comment]
Thank you for your interest in TPOT, @bartdp1. This is an interesting feature that could be useful to TPOT power users and researchers. My fear for this feature is that it would have considerable overhead for the non-research version of TPOT, both in terms of memory/computation and in terms of code integration.

For example, to track the list of predecessors, we would need to store an additional object in TPOT that tracks the ancestry of every individual, which can grow quite large. Then to store the ancestry for one individual, we would need to traverse down that ancestry tree and store a list of strings for every evaluated individual.

If this feature is proposed for a research version of TPOT for a research project, I don't think I would have these reservations.

Perhaps @weixuanfu can add some thoughts about the feature?

**Comment by bartdp1** [comment]
@rhiever Thanks for your comment. I think it would only be necessary to keep the string representation of the direct predecessor (or predecessors in case of a mating operation) for each individuals. Users can then choose to build the complete 'family tree' themselves after running TPOT using the direct predecessor links. As for the statistics regarding mutation and mating operations, these could be increased incrementally when then the operations occur (e.g. taking the current number of mutations and adding 1). Personally, i don't think that this should significantly increase the computation/memory required to run the algorithm, as opposed to the current creation of   'evaluated_individuals_'.

**Comment by rhiever** [comment]
I'd be happy to review a PR to the `development` branch with the proposed changes, and we can evaluate the overhead from there.

One note on implementation: Probably better to change the values stored in `evaluated_individuals_` from a tuple to a dictionary. That change will make it easier to query specific values from the `evaluated_individuals_` dictionary.

**Comment by bartdp1** [comment]
I will make an attempt and report on the progress :).
