### ISSUE TITLE
Add note to docs that TPOT refits the best pipeline(s) on the full training set

### ISSUE THREAD

**Issue by rhiever** [EpistasisLab/tpot#589]
From discussions in #583, we should add a note to the docs that TPOT refits the best pipeline(s) on the full training set. This behavior may affect some users' pipelines, especially if they're using a single train/test split as the `cv` procedure.

**Comment by matthewwritter** [comment]
I'm a TPOT user, though new to contributing to OSS. This seems like a manageable way to dip my toe in. Could I give it a shot?

**Comment by weixuanfu** [comment]
@matthewwritter thank you. Please submit your contribution via a PR based on development branch.

**Comment by saddy001** [comment]
sklearn has a nice introductory section about how to contribute. I think it is similar for TPOT:
http://scikit-learn.org/stable/developers/contributing.html#contributing-code

**Comment by weixuanfu** [comment]
Yep, it is similar, check this [link](http://rhiever.github.io/tpot/contributing/) for more details.

**Comment by rhiever** [comment]
@matthewwritter, we'd be happy for you to contribute a PR for this issue. I will change the issue status to indicate that you've taken on this PR. Please check out the [contributor's documentation](http://rhiever.github.io/tpot/contributing/) (linked by @weixuanfu above), which provides details on how to contribute to our project. Feel free to ask any questions you have here.

**Comment by rhiever** [comment]
In terms of *where* to add this note in the docs, I think we should add it to:

- [ ] `base.py` [fit function](https://github.com/rhiever/tpot/blob/911ece728b77f4ef5cb6192f5002060916ea332f/tpot/base.py#L455) docstrings
- [ ] The [API docs](https://github.com/rhiever/tpot/blob/master/docs_sources/api.md) for the `fit` function (both TPOTClassifier and TPOTRegressor)
- [ ] The [Using docs](https://github.com/rhiever/tpot/blob/master/docs_sources/using.md) under the `TPOT with code` section

When you send the PR, please send it to the `master` branch. This is a rare exception where we will merge the PR directly to the `master` branch because it is a documentation change that we can roll out immediately.

**Comment by matthewwritter** [comment]
OK, will do! I also read the scikit-learn contributor documentation, which suggest submitting a [WIP] PR immediately, but since this is so simple I'll just wait until I've made all the changes
