### ISSUE TITLE
In Python, how to predict Y (1) if 0 or not (2)if not 0 then what value

### ISSUE THREAD

**Issue by gaochen219** [EpistasisLab/tpot#598]
I want to use 24 Xs to predict Y. Assume we’ll use all 24 Xs (don’t worry about feature selection) and use all records.

Y is a continuous variable but half of my records are zero (total is 40k). These ZEROs are meaningful. 
Goal is to know: When I have new 24 Xs data coming in, what is the Y?
I’m thinking about two steps:
1.	Determine if Y is 0 or not. Using RandomForestClassifier or Logistic Regression?
2.	If Y is not 0, using RandomForestRegressor to predict Y’s value?

Is it possible to do the two-step model? How to implement - if Y is not 0, go to the next model? Thank you very much!

![image](https://user-images.githubusercontent.com/32340511/31482353-cf9a9856-aedc-11e7-9ba5-52238bc1b445.png)

**Comment by rhiever** [comment]
This sounds like a good question for StackOverflow and/or [CrossValidated](https://stats.stackexchange.com/), as it's not necessarily TPOT-specific. It's difficult to provide specific advice as we don't know the precise details of your problem, but your approach sounds like a reasonable step toward solving the problem.

**Comment by gaochen219** [comment]
Thank you @rhiever .You're right, I put it under TPOT-specific by mistake.

**Comment by rhiever** [comment]
@gaochen219, please feel free to drop a link to the SO/CrossValidated thread if you ended up posting it there. In the meantime, I will close this issue.
