### ISSUE TITLE
Doubt with implemented mutation operator

### ISSUE THREAD

**Issue by unaigarciarena** [EpistasisLab/tpot#603]
Hello everyone,

I have been studying the mutation function specifically implemented for TPOT (mutNodeReplacement, line 301 in gp_deap.py), and I'm not sure if there is a little mistake, or if I haven't fully understood how it works.

## Context of the issue

I think that, in case the random generator selects a primitive from the pipeline rather than a terminal, the for loop found immediately after checking that it is not the last primitive in the pipeline (line 331) tries to find the next primitive and put it in 'rindex', as the comment previous to the loop explains.

Assuming that is correct, I think that the for loop goes over all the nodes in the tree, and updates 'rindex' every time it finds a Primitive. Finally, we find in 'rindex' the index of the last Primitive in the list, this is, the Primitive in the second to last depth level in the tree.

Again if this is correct, this results in the mutation operator deleting all the Primitives between the randomly selected one, and the last one (neither of them included).

## Process to reproduce the issue

Generating the following random pipeline (I have deleted the parameters for simplicity):
KNeighborsClassifier(StandardScaler(StandardScaler(KNeighborsClassifier(input_matrix))))

## Expected result

Where I intuitively think the operator should provide:
GaussianNB(StandardScaler(StandardScaler(KNeighborsClassifier(input_matrix))))

## Current result

What it returns is:
GaussianNB(KNeighborsClassifier(input_matrix))

## Possible fix

If my intuition is correct, I think a simple 'break' statement inside the if conditional, when 'rindex' is updated should be enough (line 334).

Keep up with the nice work!

**Comment by weixuanfu** [comment]
Thank you for reporting this issue. I think it should be a bug. I will working on fixing it and add an unit test for this issue. @rhiever

**Comment by rhiever** [comment]
Should be fixed on the dev branch now. Release coming soon.
