### ISSUE TITLE
How to access stratified folds inside cv?

### ISSUE THREAD

**Issue by QuantumDamage** [EpistasisLab/tpot#611]
Hi,
i wrote my custom scoring function which sums profits and loses based on prediction:

```
def my_max_profit(y_true, y_pred):
    return np.sum(array[(y_true == 0) & (y_pred == 0)][:,6]*0.081) + \
           np.sum(array[(y_true == 1) & (y_pred == 0)][:,6]* -1)
```

It works nice but its needs access to whole array, so it will not work as scoring for fold inside tpot cross validation. Is there a way to access current fold inside cv and use it instead whole array?

Or maybe other way to approach this problem?

**Comment by rhiever** [comment]
When you say that it needs access to the entire array, do you mean that it needs access to the feature matrix `X` as well? Or do you mean that you don't want to perform k-fold CV and instead evaluate each pipeline only once on the entire training set?

**Comment by QuantumDamage** [comment]
I was thinking about accessing feature matrix X used in fold.
