### ISSUE TITLE
Multi-class issue when running TPOT

### ISSUE THREAD

**Issue by alexgcsa** [EpistasisLab/tpot#613]
Hi,

I've been trying to run TPOT on multi-class datasets (such as car and vehicle), but it always outputs the same error for this kind of dataset:

"RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly."

Thanks!

**Comment by weixuanfu** [comment]
Hmm, what is this issue about? @alexgcsa

**Comment by weixuanfu** [comment]
Could you please share the codes/dataset for reproducing this issue?

**Comment by alexgcsa** [comment]
These are the datasets:

(car) https://www.dropbox.com/sh/o8l4uyy9mlyepsp/AABz6jlkAs1EGYccQ_Kp43Lra?dl=0

(vehicle) https://www.dropbox.com/sh/zt0xgxk8kersqun/AACv_CISMObJfMLLRsCp07Lra?dl=0


For the dataset 'car', I used the One Hot Encoder to create the new features (nominal to binary) and the Label Encoder to the define the class. 

For the dataset 'vehicle', I only used the Label Encoder, because the features were already numerical.

**Comment by alexgcsa** [comment]
I'm facing this problem only when the dataset has more than two classes. When the problem is from binary classification, this doesn't happen.

**Comment by weixuanfu** [comment]
I have a quick test on car training dataset via CLI mode of TPOT using the command below:
```
tpot .\car-Training0.csv -target class -is "," -g 5 -p 30 -v 2

TPOT settings:
CHECKPOINT_FOLDER   =     None
CONFIG_FILE         =     None
CROSSOVER_RATE      =     0.1
EARLY_STOP          =     None
GENERATIONS         =     5
INPUT_FILE          =     .\car-Training0.csv
INPUT_SEPARATOR     =     ,
MAX_EVAL_MINS       =     5
MAX_TIME_MINS       =     None
MUTATION_RATE       =     0.9
NUM_CV_FOLDS        =     5
NUM_JOBS            =     1
OFFSPRING_SIZE      =     30
OUTPUT_FILE         =
POPULATION_SIZE     =     30
RANDOM_STATE        =     None
SCORING_FN          =     accuracy
SUBSAMPLE           =     1.0
TARGET_NAME         =     class
TPOT_MODE           =     classification
VERBOSITY           =     2

Warning: xgboost.XGBClassifier is not available and will not be used by TPOT.
Generation 1 - Current best internal CV score: 0.9802534630120838
Generation 2 - Current best internal CV score: 0.9828470380194518
Generation 3 - Current best internal CV score: 0.9828470380194518
Generation 4 - Current best internal CV score: 0.9845711759504864
Generation 5 - Current best internal CV score: 0.9845711759504864

Best pipeline: GradientBoostingClassifier(input_matrix, learning_rate=0.5, max_depth=4, max_features=0.95, min_samples_leaf=8, min_samples_split=11, n_estimators=100, subsample=0.85)

Training score: 0.9845711759504864
Holdout score: 0.9845758354755784
```
TPOT works fine. 

I suspected that the issue maybe related to the way of formatting `y`. Please try the demo below for formatting dataset. 

```
import pandas as pd
tpot_data = pd.read_csv('PATH/TO/DATA/FILE', sep=',', dtype=np.float64)
features = tpot_data.drop('class', axis=1).values
classes = tpot_data['class'].values
```

**Comment by alexgcsa** [comment]
Thanks, it worked!
