### ISSUE TITLE
Failure to periodically save pipeline if the directory doesn't exist

### ISSUE THREAD

**Issue by mlapierre** [EpistasisLab/tpot#616]
If the periodic_checkpoint_folder doesn't exist an error is thrown

## Context of the issue

In the spirit of automation, it would be nice if the periodic_checkpoint_folder were created for us if it doesn't exist. At the moment an error is thrown and no checkpoints are saved.

## Process to reproduce the issue

Create a TPOT instance with a nonexistent folder as the periodic_checkpoint_folder

## Expected result

The folder is automatically created

## Current result

An error occurs:

> Failed saving periodic pipeline, exception:
> [Errno 2] No such file or directory: './checkpoints\\pipeline_2017.11.06_06-05-10.py'

## Possible fix

Before:
https://github.com/rhiever/tpot/blob/a303f1e9b209a7d0625c9e6017169a7e3c9bf4d1/tpot/base.py#L864

Include something like:
```python
    try:
        os.makedirs(self.periodic_checkpoint_folder)
    except OSError as e:
        if e.errno == errno.EEXIST and os.path.isdir(self.periodic_checkpoint_folder):
            pass
```

If this would be useful I'm happy to submit a PR.

**Comment by rhiever** [comment]
@mlapierre, we'd be happy to review and merge a PR for this enhancement to the periodic checkpoint folder feature.

**Comment by weixuanfu** [comment]
@mlapierre I closed this PR since the PR already merged to dev branch! Thank you!
