### ISSUE TITLE
_pre_test decorator

### ISSUE THREAD

**Issue by korcky** [EpistasisLab/tpot#619]
## Context of the issue

My models used complex data to fit and to predict. TPOT gets not exactly this data, it gets something like 'map' of my data. Because of this any raw generic data doesn't  work in my models.

## Questions

1. Could this `_pre_test` be off?
2. I receive warnings like this during fit:
  * `_pre_test decorator: _generate: num_test=0 all the input arrays must have same number of dimensions`
  * `_pre_test decorator: _random_mutation_operator: num_test=0 all the input arrays must have same number of dimensions`
I have worrying about second warning (with `_random_mutation_operator`): could this somehow affect on TPOT results?

**Comment by weixuanfu** [comment]
Hmm, `_pre_test` decorator can not be turned off in current version of TPOT. We added this decorator for preventing TPOT from generating invalid parameter combination by evaluating each pipeline on a small test dataset.

**Comment by weixuanfu** [comment]
We may need better way to replace `_pre_test` decorator.

**Comment by rhiever** [comment]
Can you please provide us with more details on the shape of your data? Are you using custom ML algorithms as well?

**Comment by korcky** [comment]
Yep, I'm using custom ML algorithms.
Right now TPOT's fit (if gets `cv=5`) receive from me: 
  * `X`: `ndarray` with shape `(5, 6)`
  * `y`: `ndarray` with shape `(5,)`
And, if I understand correctly, when fit method used my data it fits on 4 items and predicts 5th (that's what exactly what i want right now, because predict method of my model always return only one value). And looks like it works for me right now.

**Comment by weixuanfu** [comment]
I close this issue. Please feel free to re-open the issue if you have any more questions
