### ISSUE TITLE
RuntimeError in the TPOT optimization

### ISSUE THREAD

**Issue by rwexler** [EpistasisLab/tpot#625]
I am trying to use TPOT to generate an optimized pipeline for the safe driver prediction challenge on Kaggle (https://www.kaggle.com/c/porto-seguro-safe-driver-prediction). I was able to successfully complete the optimization process once for 5 generations and a population of 20. All subsequent attempts, however, to increase the either the number of generations or the size of the population have caused a runtime error

`raise RuntimeError('There was an error in the TPOT optimization '`

## Context of the issue

For my successful run, I used the following code

`tpot = TPOTClassifier(generations = 5, population_size = 20, verbosity = 2, scoring = GiniScore)`

I then tried to double the number of generations but received the following error

`/global/common/edison/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "/global/homes/r/rwexler/.local/edison/3.6-anaconda-4.4/lib/python3.6/site-packages/tpot/base.py", line 630, in fit
    per_generation_function=self._check_periodic_pipeline
  File "/global/homes/r/rwexler/.local/edison/3.6-anaconda-4.4/lib/python3.6/site-packages/tpot/gp_deap.py", line 244, in eaMuPlusLambda
    per_generation_function()
  File "/global/homes/r/rwexler/.local/edison/3.6-anaconda-4.4/lib/python3.6/site-packages/tpot/base.py", line 917, in _check_periodic_pipeline
    self._update_top_pipeline()
  File "/global/homes/r/rwexler/.local/edison/3.6-anaconda-4.4/lib/python3.6/site-packages/tpot/base.py", line 709, in _update_top_pipeline
    raise RuntimeError('There was an error in the TPOT optimization '
RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 40, in <module>
    tpot.fit(X_train, y_train)
  File "/global/homes/r/rwexler/.local/edison/3.6-anaconda-4.4/lib/python3.6/site-packages/tpot/base.py", line 662, in fit
    raise e
  File "/global/homes/r/rwexler/.local/edison/3.6-anaconda-4.4/lib/python3.6/site-packages/tpot/base.py", line 653, in fit
    self._update_top_pipeline()
  File "/global/homes/r/rwexler/.local/edison/3.6-anaconda-4.4/lib/python3.6/site-packages/tpot/base.py", line 709, in _update_top_pipeline
    raise RuntimeError('There was an error in the TPOT optimization '
RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly.`

Thanks in advance for your help!

-Rob

**Comment by weixuanfu** [comment]
Hmm, it seems that no valid pipeline (or pipeline is too time-consuming to get a valid fitness score) is generated in the initial generation, which is very weird. I have a quick look on the dataset in Kaggle, maybe each pipeline need more resources to evaluate since the dataset is very huge.  Please make sure there is enough free memory and maybe reset `max_eval_time_mins` to 10 or increase `population_size` to 50 or higher would let TPOT randomly generate a valid pipeline in initial generation. 

But without a fixed `random_state`, we could not reproduce the issue in our environment. If these possible solutions do not help, could you please provide codes with `random_state` parameter, versions of TPOT and its dependencies, python version and system information for let us to reproduce the issue?

**Comment by rwexler** [comment]
Hi Weixuan,

Thanks for your reply.

The size of the training and testing data is 0.115852544 GB and 0.172006681
GB, respectively. Do you think that data sets of these sizes would be too
large for TPOT?

I'm not sure if free memory is the issue given the size of the data set and
the fact that I am using two nodes of a supercomputer each with 64 GB of
memory.

In the calculation that completed, I did not set random_state. In the
calculation that failed, however, I used `random_state = 42`. I have
attached a copy of the script that failed.

Thanks again for your help!

---------------------------------------------
Robert B. Wexler
PhD Candidate in Chemistry
University of Pennsylvania, 2018
rwexler@sas.upenn.edu
(215) 801-8741
---------------------------------------------

**Comment by weixuanfu** [comment]
Hi @rwexler 

I found that it should be caused by a bug when introducing the new scoring API in TPOT 0.9.1 (related issue #579, PR #594 #607).

I just made a PR #626 for fixing this issue. You may try the fixed branch by install TPOT:
```
pip install --upgrade --no-deps --force-reinstall git+https://github.com/weixuanfu/tpot.git@scoring_api_bug
```
And then you need change `GiniScore(y_actual, y_pred):` to `GiniScore(y_true, y_pred):` in your codes.

Or, you can still use the current TPOT 0.9.1 and add these codes below to your scripts:
```
from sklearn.metrics.scorer import make_scorer
GiniScore_scorer = make_scorer(GiniScore, greater_is_better=True)

tpot = TPOTClassifier(generations = 10, population_size = 20, verbosity = 2, scoring = GiniScore_scorer, random_state = 42)
```
Sorry about the inconvenience.

**Comment by rwexler** [comment]
Thank you for solving this so promptly.

I will use the currently of TPOT for now but will also test the new
installation later. I'll let you know how these go.

-Rob

---------------------------------------------
Robert B. Wexler
PhD Candidate in Chemistry
University of Pennsylvania, 2018
rwexler@sas.upenn.edu
(215) 801-8741
---------------------------------------------

**Comment by weixuanfu** [comment]
I closed this issue since the fix was merged to dev branch.
