### ISSUE TITLE
Failing unit tests on development branch

### ISSUE THREAD

**Issue by PGijsbers** [EpistasisLab/tpot#630]
I noticed three unit tests failing on a clean development branch.
Specifically, they are unit tests ` test_init_default_scoring_[2/3/4]`.
To reproduce the issue, I think it should be enough to run the unit tests on the development branch.

The issue lies with the assertion of the number of warnings `assert len(w) == 1` (or similar, depending on unit test).
I correctly get the deprecation warning (in `test_init_default_scoring_2`), however I also get additional warnings from DEAP.
In `test_init_default_scoring_2`, the following warnings are issued:
* DeprecationWarning('Scoring function <function balanced_accuracy at 0x0000023E3AE7A950> looks like it is a metric function rather than a scikit-learn scorer. This scoring type was deprecated in version TPOT 0.9.1 and will be removed in version 0.11. Please update your custom scoring function.',)
* RuntimeWarning("A class named \'FitnessMulti\' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.",)
* RuntimeWarning("A class named \'Individual\' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.",)

In the other two tests, only the latter two warnings are raised.

I think the fix for `test_init_default_scoring_2` should be that unit test only makes sure a deprecation warning with the right message is given, and ignore any others ([example](https://github.com/PG-TUe/tpot/blob/minor-fixes/tests/tpot_tests.py#L145-L154)).
For the others, I'm not sure if it should ignore all warnings, or just check that it gives no warning that contains "scorer" in the message?

I further noticed two more unit tests giving errors, but I posted a question on this in #624, because I thought they might be related - either way, they are very different tests from these.

**Comment by weixuanfu** [comment]
@PG-TUe please check the related issue #623. Downgrade your deal version to 1.0.2 should avoid these errors. I also made a patch in #624 .

**Comment by PGijsbers** [comment]
Downgrading to 1.0.2.post2 fixed the issue :)
