### ISSUE TITLE
Cannot install TPOT after installing Anaconda 5.0.1

### ISSUE THREAD

**Issue by ijeffking** [EpistasisLab/tpot#633]
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - tpot -> deap >=1.0 -> python 3.4*
Use "conda info <package>" to see the dependencies for each package.
## Context of the issue

[provide more detailed introduction to the issue itself and why it is relevant]

[the remaining entries are only necessary if you are reporting a bug]

## Process to reproduce the issue

[ordered list the process to finding and recreating the issue, example below]

1. User creates TPOT instance
2. User calls TPOT `fit()` function with training data
3. TPOT crashes with a `KeyError` after 5 generations

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you currently experience from this process, and thereby explain the bug]

## Possible fix

[not necessary, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by weixuanfu** [comment]
Could you please provide more details about your running environment, like versions of TPOT and all the dependencies, OS and python version?

My guess about the issue is related to deap. Maybe you need uninstall deap and then reinstall it.

On Nov 25, 2017, at 2:31 PM, ijeffking <notifications@github.com<mailto:notifications@github.com>> wrote:


UnsatisfiableError: The following specifications were found to be in conflict:

  *   python 3.6*
  *   tpot -> deap >=1.0 -> python 3.4*
Use "conda info " to see the dependencies for each package.

Context of the issue

[provide more detailed introduction to the issue itself and why it is relevant]

[the remaining entries are only necessary if you are reporting a bug]

Process to reproduce the issue

[ordered list the process to finding and recreating the issue, example below]

  1.  User creates TPOT instance
  2.  User calls TPOT fit() function with training data
  3.  TPOT crashes with a KeyError after 5 generations

Expected result

[describe what you would expect to have resulted from this process]

Current result

[describe what you currently experience from this process, and thereby explain the bug]

Possible fix

[not necessary, but suggest fixes or reasons for the bug]

name of issue screenshot

[if relevant, include a screenshot]

**Comment by ijeffking** [comment]
Hello,

Appreciate the prompt Response.

I am using Windows 10.

I had Anaconda installed on my PC and had been using TPOT without any Problems.I had followed the Installation iinstructions.
Yesterday I had been Learning CNN with Keras and then the Problem started. I downloaded tensorflow and since then various issues cropped up.

So I decided to uninstall the old Anaconda and reinstall the new Version of Anaconda Version 1.6.9
Then I installed all the libraries required for Data Science like scikit-learn, keras, Theano,tensorflow,…
BUT  I just cannot get to install tpot 
In the Anaconda the files are available but everytime I try to install them I get the Unsatisfiableerror. Tpot 0.6.4 and deap 1.0.2 are available but cannot be installed.
UnsatisfiableError: The following specifications were found to be in conflict: 

* python 3.6* 
* tpot -> deap >=1.0 -> python 3.4* 
Use "conda info " to see the dependencies for each package. 

What do you suggest ?
You have said uninstall deap. But when I do uninstall it says PackageNOTFound error. Package missing from the environment. 

I really liked using TPOT. A prompt response would be highly appreciated.

Best,
Jeff

Sent from Mail for Windows 10

**Comment by ijeffking** [comment]
Hello,

I just observed that I have 2 folders of deap

C:\Users\ijeff\Anaconda3\pkgs\ deap-1.0.2.post2-py34_0

C:\Users\ijeff\Anaconda3\pkgs\deap-1.0.2.post2-py34_0\Lib\site-packages

One of them seems to be the extra that could be the cause of the problem but I do not know which one

Your help is solicited and would be highly appreciated.

Best,
Jeff

Sent from Mail for Windows 10

**Comment by weixuanfu** [comment]
Sorry, I cannot access my PC right now. Just two quick possible solutions:

How about force reinstall deap?

pip install --force-reinstall deap==1.0.2.post2

Or rebuilding a new fresh environment in conda should works.

Check this link for more details: https://conda.io/docs/user-guide/tasks/manage-environments.html

From my iPhone

On Nov 25, 2017, at 6:17 PM, ijeffking <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,

I just observed that I have 2 folders of deap

C:\Users\ijeff\Anaconda3\pkgs\ deap-1.0.2.post2-py34_0

C:\Users\ijeff\Anaconda3\pkgs\deap-1.0.2.post2-py34_0\Lib\site-packages

One of them seems to be the extra that could be the cause of the problem but I do not know which one

Your help is solicited and would be highly appreciated.

Best,
Jeff

Sent from Mail for Windows 10

**Comment by ijeffking** [comment]
Thank you for the prompt response.
After I tried the force reinstall deap I got the following error

Collecting deap==1.0.2.post2
Exception:
Traceback (most recent call last):
  File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\index.py", line 811, in get_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\index.py", line 731, in __init__
    namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'

A question regarding rebuilding a new fresh environment:
- How do I access the files for example TPOT, deap,…which would be in the new environment?
- I mean, while using Jupyter notebook do I have to import the files using a special command as these files are not in the root environment.
- Also what if I am going to use modules which are in the root environment and tpot in the new environment ? 
- Do I install python3.4 in the new environment? And then install deap and tpot ?
Awaiting your response.

Best,
Jeff

Sent from Mail for Windows 10

**Comment by weixuanfu** [comment]
Building a new running environment won’t affect your files’ path and Python3.4 is not necessary. Please check the link I sent over before for more details.

For deap installation, maybe you need submit another issue in deap’s GitHub repo for a better solution. I am not sure why your root environment is messed up with deap in the old anaconda environment.

Weixuan

From my iPhone

On Nov 26, 2017, at 12:23 AM, ijeffking <notifications@github.com<mailto:notifications@github.com>> wrote:

Thank you for the prompt response.
After I tried the force reinstall deap I got the following error

Collecting deap==1.0.2.post2
Exception:
Traceback (most recent call last):
File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
status = self.run(options, args)
File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
wb.build(autobuilding=True)
File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
self.requirement_set.prepare_files(self.finder)
File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
ignore_dependencies=self.ignore_dependencies))
File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
require_hashes
File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
self.link<http://self.link> = finder.find_requirement(self, upgrade)
File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\index.py", line 465, in find_requirement
all_candidates = self.find_all_candidates(req.name)
File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\index.py", line 423, in find_all_candidates
for page in self._get_pages(url_locations, project_name):
File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\index.py", line 568, in _get_pages
page = self._get_page(location)
File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\index.py", line 683, in _get_page
return HTMLPage.get_page(link, session=self.session)
File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\index.py", line 811, in get_page
inst = cls(resp.content, resp.url, resp.headers)
File "C:\Users\ijeff\Anaconda3\lib\site-packages\pip\index.py", line 731, in __init__
namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'

A question regarding rebuilding a new fresh environment:
- How do I access the files for example TPOT, deap,…which would be in the new environment?
- I mean, while using Jupyter notebook do I have to import the files using a special command as these files are not in the root environment.
- Also what if I am going to use modules which are in the root environment and tpot in the new environment ?
- Do I install python3.4 in the new environment? And then install deap and tpot ?
Awaiting your response.

Best,
Jeff

Sent from Mail for Windows 10

**Comment by ijeffking** [comment]
Hello,

I created a new environment myenv and installed tpot, deap and other dependencies.

But while running the tpot Code I got back the following error:
ModuleNotFoundError Traceback (most recent call last) <ipython-input-3-3cdf56f70941> in <module>() ----> 1 from tpot import TPOTClassifier 2 from sklearn.datasets import load_digits 3 from sklearn.model_selection import train_test_split 4 5 digits = load_digits() ModuleNotFoundError: No module named 'tpot'

Do I have to specify anything ? 

Best,
Jeff

Sent from Mail for Windows 10

**Comment by ijeffking** [comment]
Hello,

I created a new environment and now tpot works. Great! Thank you very much for your Support.
But I get the following errors…Unfortunately the tpot cannot be updated for whatever reason.

I have Python 3.6.3 in root and Python3.5.4 in myenv where tpot and other related modules are. 
As a result it is not performing at Optimum Levels.
What do you suggest?

Version 0.6.4 of tpot is outdated. Version 0.9.1 was released Friday November 10, 2017.
GP Progress:   1%|▋                                                              | 3/300 [00:01<05:42,  1.15s/pipeline]C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)
GP Progress:  10%|██████▏                                                       | 30/300 [00:18<04:05,  1.10pipeline/s]C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)
C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)
GP Progress:  15%|█████████▌                                                    | 46/300 [00:27<02:36,  1.62pipeline/s]C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)
                                                                                                                       
Generation 1 - Current best internal CV score: 9.097548191320314
GP Progress:  26%|████████████████                                              | 78/300 [01:27<05:51,  1.58s/pipeline]C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)
GP Progress:  28%|█████████████████▎                                            | 84/300 [01:42<08:08,  2.26s/pipeline]C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)
GP Progress:  29%|██████████████████▏                                           | 88/300 [01:56<09:46,  2.77s/pipeline]C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)
                                                                                                                       
Generation 2 - Current best internal CV score: 9.097548191320314
GP Progress:  39%|███████████████████████▉                                     | 118/300 [02:57<04:43,  1.56s/pipeline]C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)
GP Progress:  46%|████████████████████████████                                 | 138/300 [03:41<04:33,  1.69s/pipeline]C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)
GP Progress:  47%|████████████████████████████▍                                | 140/300 [03:44<03:47,  1.42s/pipeline]C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)
                                                                                                                       
Generation 3 - Current best internal CV score: 8.883995323472124
                                                                                                                       
Generation 4 - Current best internal CV score: 8.846148613723344
GP Progress:  75%|█████████████████████████████████████████████▉               | 226/300 [06:47<04:51,  3.93s/pipeline]C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)
GP Progress:  79%|████████████████████████████████████████████████▏            | 237/300 [07:09<02:14,  2.14s/pipeline]C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)
                                                                                                                       
Generation 5 - Current best internal CV score: 8.846148613723344
                                                                                                                       

Best pipeline: ExtraTreesRegressor(input_matrix, 0.67000000000000004)
C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
14.2713730312

A prompt response would be appreciated

Best,
Jeff

Sent from Mail for Windows 10

**Comment by eyadsibai** [comment]
the tpot version in conda-forge channel is old

**Comment by ijeffking** [comment]
So what do you suggest?
How to upgrade the tpot?

Sent from Mail for Windows 10

**Comment by weixuanfu** [comment]
Try the command below:

```
conda uninstall tpot
# or pip uninstall tpot
pip install --upgrade tpot 
```

**Comment by ijeffking** [comment]
I got the following error after successful installation of tpot 0.9.1

# Import required libraries
from tpot import TPOTClassifier
from sklearn.model_selection import train_test_split
import pandas as pd 
import numpy as np

C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\deap\tools\_hypervolume\pyhv.py:33: ImportWarning: Falling back to the python version of hypervolume module. Expect this to be very slow. "module. Expect this to be very slow.", ImportWarning)

ImportError Traceback (most recent call last) <ipython-input-1-6e78dc33889f> in <module>() 1 # Import required libraries ----> 2 from tpot import TPOTClassifier 3 from sklearn.model_selection import train_test_split 4 import pandas as pd 5 import numpy as np ~\Anaconda3\envs\myenv\lib\site-packages\tpot\__init__.py in <module>() 25 26 from ._version import __version__ ---> 27 from .tpot import TPOTClassifier, TPOTRegressor 28 from .driver import main ~\Anaconda3\envs\myenv\lib\site-packages\tpot\tpot.py in <module>() 24 """ 25 ---> 26 from .base import TPOTBase 27 from .config.classifier import classifier_config_dict 28 from .config.regressor import regressor_config_dict ~\Anaconda3\envs\myenv\lib\site-packages\tpot\base.py in <module>() 77 # https://github.com/ContinuumIO/anaconda-issues/issues/905 78 if sys.platform.startswith('win'): ---> 79 import win32api 80 81 try: ImportError: No module named 'win32api'

Sent from Mail for Windows 10

**Comment by weixuanfu** [comment]
Try `conda install pywin32`
Please check https://rhiever.github.io/tpot/installing/ for more details.

**Comment by ijeffking** [comment]
Yessssssss!!!!!
Finally it is fixed.
Thank you soooooooo much.

I just wanted to ask you why I got this warning message although I have sklearn 0.19.1 installed…
I use   from sklearn import model_selection. I have not ued cross_validation at all in my Code.

C:\Users\ijeff\Anaconda3\envs\myenv\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20. "This module will be removed in 0.20.", DeprecationWarning)

Any suggestions?
Once again Thank you for your help and appreciate your patience and support.

Best,
Jeff

Sent from Mail for Windows 10

**Comment by weixuanfu** [comment]
No problem. I think this warning is from the old version of xgboost. You may need rebuild xgboost from source codes to update xgboost.

**Comment by ijeffking** [comment]
Appreciate the response.

I have py-xgboost in myenv and when I try to uninstall it first it says „Cannot uninstall requirement py-xgboost, not installed“

When I tried to upgrade directly I got the following error…
(myenv) C:\Users\ijeff>pip install --upgrade xgboost
Collecting xgboost
  Using cached xgboost-0.6a2.tar.gz
No files/directories in C:\Users\ijeff\AppData\Local\Temp\pip-build-kq_wznta\xgboost\pip-egg-info (from PKG-INFO)

Conda list showed 
py-xgboost                0.60            py35np112h24854b6_0

What do you suggest?

Best,
Jeff

Sent from Mail for Windows 10

**Comment by weixuanfu** [comment]
The latest version of xgboost cannot be installed with pip. You need rebuild it from source codes. Check the link http://xgboost.readthedocs.io/en/latest/build.html for more details. It is not easy to install xgboost in Windows, so I think you need file a issue in xgboost repo for better solution.

**Comment by ijeffking** [comment]
Oh Okay
It looks very complicated. I will leave it and just continue with the Version of xgboost I have at the Moment.

Nonetheless Thank you so much

Best 
Jeff

Sent from Mail for Windows 10
