### ISSUE TITLE
Error in my TPOT "PATH/TO/DATA/FILE"

### ISSUE THREAD

**Issue by kanekalla** [EpistasisLab/tpot#635]
using TPOT to predict using it in virtual env 

Error 1: 
/home/kishore/.virtualenvs/celegans/lib/python3.6/site-packages/ipykernel_launcher.py:10: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
Remove the CWD from sys.path while we load stuff.

# TPOT initiation and calling 

tpot = TPOTClassifier(generations=5, population_size=20, verbosity=2)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
tpot.export('tpot_pipeline.py')

# Error : 
output file tpot pipeline file has 

import numpy as np
import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import Normalizer

# NOTE: Make sure that the class is labeled 'target' in the data file
tpot_data = pd.read_csv('PATH/TO/DATA/FILE', sep='COLUMN_SEPARATOR', dtype=np.float64)
features = tpot_data.drop('target', axis=1).values
training_features, testing_features, training_target, testing_target = \
            train_test_split(features, tpot_data['target'].values, random_state=42)

# Score on the training set was:0.9687834870443567
exported_pipeline = make_pipeline(
    Normalizer(norm="l2"),
    ExtraTreesClassifier(bootstrap=False, criterion="entropy", max_features=0.8500000000000001, min_samples_leaf=1, min_samples_split=3, n_estimators=100)
)
exported_pipeline.fit(training_features, training_target)
results = exported_pipeline.predict(testing_features)
# when I run this I get that there is no file
FileNotFoundError: [Errno 2] No such file or directory: 'PATH/TO/DATA/FILE'

Do I need to add the location of  PATH/TO/FILE ?

**Comment by weixuanfu** [comment]
Yes, you need edit the location of `PATH/TO/FILE`.

**Comment by bassmaamn** [comment]
When I run it I get this Error: ValueError: could not convert string to float
Any idea please ?

**Comment by weixuanfu** [comment]
Could you please provide more details about this error?

**Comment by rhiever** [comment]
@bassmaamn, what does your dataset look like? Does it have string data in it?

**Comment by bassmaamn** [comment]
The data set is titanic-train.csv 
After exporting the python file and changing " PATH/TO/DATA/FILE " with the path to titanic-train.csv file, I have this error:
Error: ValueError: could not convert string to float

**Comment by rhiever** [comment]
Do you mean [this titanic-train.csv](https://github.com/EpistasisLab/tpot/blob/master/tutorials/data/titanic_train.csv)? If so, please refer to [this notebook](https://github.com/EpistasisLab/tpot/blob/master/tutorials/Titanic_Kaggle.ipynb) for an example of how to preprocess that dataset so it can be used with TPOT.

**Comment by bassmaamn** [comment]
I have already went through it. Can you tell me which file exactly should I give to the tpot_titanic_pipeline.py ?

**Comment by rhiever** [comment]
The custom data preprocessing procedure needs to be added to the exported code in this case. Follow the steps under the "Make predictions on the submission data" section to see how the data from `titanic_test.csv` is preprocessed before being passed to TPOT. You should also be able to take the code from that section and use it to preprocess the data then use it in the exported pipeline.

**Comment by devarshigoswami** [comment]
After preprocessing the data in the Titanic_Kaggle.ipynb notebook, the preprocessed 'titanic_new'  is a numpy ndarray , right? It oubviously cannot be exported as a CSV.
So what do i put in place of ' PATH/TO/FILE.' ?

**Comment by weixuanfu** [comment]
`titanic_new` is converted and prepossessed from a panda DataFrame `titanic` (see `In [14]`) and then convert to np.ndarray. You may change the steps for converting `titanic_new` back to panda.DataFrame with adding names of columns and then it can be easily exported as a CSV file.

**Comment by MushyamMahesh** [comment]
FileNotFoundError: [Errno 2] No such file or directory: './tpot_output/tpot_iris_pipeline_0.py'

while testing default iris data. any solution?
