### ISSUE TITLE
2 Error messages

### ISSUE THREAD

**Issue by danelee2601** [EpistasisLab/tpot#638]
1. 1st issue 
C:\python36\Lib\importlib\_bootstrap.py:205: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
![image](https://user-images.githubusercontent.com/34414758/33815214-0de17f60-de73-11e7-9b40-bba72f55efd5.png)

2. 2nd issue
C:\python36\Lib\importlib\_bootstrap_external.py:426: ImportWarning: Not importing directory C:\python36\lib\site-packages\mpl_toolkits: missing __init___warnings.warn(msg.format(portions[0]), ImportWarning)
![image](https://user-images.githubusercontent.com/34414758/33815222-18d92f4e-de73-11e7-9bcc-a5548e0122ea.png)

![image](https://user-images.githubusercontent.com/34414758/33815230-20f842e6-de73-11e7-97e6-31a7b7af49b1.png)

# I ran 'boston' example. And both my lab's computer and my personal laptop showed these two error messages.
P.S. I ran the example with 'n_jobs=-1'

![image](https://user-images.githubusercontent.com/34414758/33815267-638bd758-de73-11e7-978d-98c766056e51.png)

**Comment by weixuanfu** [comment]
Hmm, I am not sure where these error messages came from. It seems something wrong with environment settings or missing module. More detailed stdout or stderr will be helpful. Could you rebuild a conda environment (check [this link](https://conda.io/docs/user-guide/tasks/manage-environments.html)) and install TPOT there via [the guide](http://rhiever.github.io/tpot/installing/).

**Comment by danelee2601** [comment]
Oh, hey, I found the solution and what the problem was. 
Actually, aside from the above two error messages, there was one more, which was 

/usr/local/lib/python2.7/dist-packages/deap/tools/_hypervolume/pyhv.py:33: ImportWarning: Falling back to the python version of hypervolume module. Expect this to be very slow.
  "module. Expect this to be very slow.", ImportWarning)

- And I thought it was not a big deal, but it caused the following error messages mentioned above in the previous writing.

- That deap lib related error messaged occured coz I installed that with command 'conda install deap' <- which turned out to have caused errors. 
And the solution was to install deap with command 'conda install -c conda-forge deap' (ref. https://anaconda.org/conda-forge/deap). It was the right way to install deap and since then, the error deap -related message no longer showed and neither did both of the error messaged mentioned here above.


#####################################
Issue discussion as to "_hypervolume/pyhv.py:33: ImportWarning: Falling back to the python version of hypervolume module. Expect this to be very slow. " 
- https://github.com/DEAP/deap/issues/240


Now without any error messages, TPOT perfectly runs well!!

**Comment by danelee2601** [comment]
And another thing about using 'xgboost'  that I figured out was that people must use python 64 bit. Otherwise, they will never ever be able to use xgboost although they think they've installed perfectly. I used to use python 32 bit installed with anaconda and had spend a lot of time till I figured out that I had to use python 64 bits to use xgboost.

**Comment by weixuanfu** [comment]
Thank you for sharing the solutions here. I just recalled that the issue should be from the latest version of deap. The deap in conda is not the latest one.

**Comment by carterrees** [comment]
I am running into the same issue as @danelee2601 Running 3.6 on Windows 10. Have reinstalled deap using pip install --upgrade --upgrade-strategy "eager" --force-reinstall --ignore-installed --compile --process-dependency-links --no-binary :all: deap with no luck. Also followed the instructions from the Deap issue #240 link provided above which included installing and putting mingw64 on my PATH. tpot runs just fine with the n_jobs default though.
