### ISSUE TITLE
Customize tpot.fit() function

### ISSUE THREAD

**Issue by Shaista1** [EpistasisLab/tpot#643]
Hello everyone,

I was wondering if anyone has worked on this subject. I will soon go about and try to test this out but before that I thought I'd ask for past experience.

I was thinking that make a customize fit function of tpot.  

Since I am a beginner, I would welcome any thoughts from more experienced users on how to properly make this change and use it.

Thank you in advance.

Best regards,
Shaista

**Comment by weixuanfu** [comment]
[This line](https://github.com/rhiever/tpot/blob/v0.9/tpot/base.py#L455) is about the fit() function in tpot. You may tweak a customized fit() function from there.
