### ISSUE TITLE
Can it support multi label?

### ISSUE THREAD

**Issue by berisfu** [EpistasisLab/tpot#644]
for example，if Label is location(Longitude,Latitude),can I feed the location directly to the fit()?

**Comment by rhiever** [comment]
Please see [these related issues](https://github.com/rhiever/tpot/issues?utf8=%E2%9C%93&q=is%3Aissue+multi+label) and let us know if they don't address your question. TPOT doesn't support multi label classification out of the box, but it might be possible to create a [custom TPOT configuration](http://rhiever.github.io/tpot/using/#customizing-tpots-operators-and-parameters) to accomplish that.

**Comment by berisfu** [comment]
My task is to predict the geolocation. so the training data label is geolocation(Longitude,Latitude). I think custom TPO configuration can not work for me.

**Comment by weixuanfu** [comment]
I close this issue. Please feel free to re-open the issue (or comment further) if you have any more questions
