### ISSUE TITLE
TPOTRegressor doesn't seem to use xgboost

### ISSUE THREAD

**Issue by GlobalMin** [EpistasisLab/tpot#652]
When running TPOTClassifier xgboost is very commonly in the pipeline but for a regression problem I keep seeing GradientBoostingRegressor. In theory it's possibly that this outperforms xgboost but I am very skeptical. How can I debug that xgboost regression is being checked? Any way to debug this or explain this choice?

**Comment by weixuanfu** [comment]
Hmm, it is interesting. Please check [TPOT API for regression](http://rhiever.github.io/tpot/api/#regression). You may check the `evaluated_individuals_` attribute to find out if xgboost regression has been evaluated in the optimization process.

**Comment by GlobalMin** [comment]
Thank you. Here is how I'm setting up the process after importing all the packages and loading the data set.

```
pipeline_optimizer = TPOTRegressor(generations=50, population_size=15, cv=5,n_jobs=-1,
       random_state=42, verbosity=3,max_eval_time_mins=2000,scoring='neg_mean_absolute_error')
model = pipeline_optimizer.fit(x_train2,y_train2)
```

How would I grab the `evaluated_individuals_` from the pipeline_optimizer.fit()?

**Comment by weixuanfu** [comment]
`pipeline_optimizer.evaluated_individuals_` it is a python dictionary.

BTW, we could just use `pipeline_optimizer.fit(x_train2,y_train2)` instead of `model = pipeline_optimizer.fit(x_train2,y_train2)`

**Comment by GlobalMin** [comment]
I restricted the max eval time of each pipeline using `max_eval_time_mins=` and the XGBRegressor function seems to pop up now sometimes, although TPOT is still favoring GradientBoostingRegressor. So there isn't any bug here but it's an interesting observation as I thought XGBoost has been shown to outperform the naive version of gradient boosting both in time and performance. Thank you for the help.

**Comment by lesshaste** [comment]
Did you ever get to the bottom of what is going on? I also find the same thing which looks suspicious to me.
