### ISSUE TITLE
Using TPOT classifier output to create new entries (not an issue, more of a question)

### ISSUE THREAD

**Issue by pliablepixels** [EpistasisLab/tpot#653]
Hi, I've successfully used TPOT Classifier to arrive at a model that does a great job of classification (Y given A,B,C,D)

It's final choice was:
```
Best pipeline: ExtraTreesClassifier(RFE(input_matrix, criterion=gini, max_features=0.15, n_estimators=100, step=0.6), bootstrap=False, criterion=gini, max_features=0.9, min_samples_leaf=4, min_samples_split=18, n_estimators=100)
0.85090088753
```

That's much better than what I did manually, including a DNN model, so thats great.

Is it at all possible to use this generated pipeline (or saved  fitted_pipeline_ model, which I saved using pickle) to now create new values of A,B,C,D that will result in Y=1?

Any advice is very useful. Thanks again for this great library.

**Comment by weixuanfu** [comment]
Good to hear that TPOT works well for you. I am a little confused about your question here. Could you please explain more what is "new values of A, B, C, D". Is it new dataset? If so, you may need refit TPOT on new dataset for best pipeline. I think there is no best pipeline for all the data.

**Comment by pliablepixels** [comment]
My apologies for the confusing phrasing. Yes, I am referring to being able to generate "new" positive classification items (They don't exist).

A concrete example: (the example is made up)

I've been given a dataset that has 10,000 rows of 'car color, car model, state, driver age' (X) and a classification of each row (Y) that is "hasAccident" which is 1 or 0.

Using TPOT, I came up with a great classifier.

Now I'd like to be able to generate _new_ combinations of 'car color, car model, state, driver age' that might result in hasAccident=1.  The question therefore is "generate a new tuple that will have a high chance if accident=1" as opposed to "given a new tuple, tell me what is the likelihood of having an accident"

Thank you.

**Comment by bartdp1** [comment]
@pliablepixels possibly the most naive way to do this is to simply generate a random feature matrix (e.g. random combinations what you refer to as A,B,C,D, given the possible values for ABCD), predict using your fitted pipeline, and keep all samples for which the predicted value is 1. 

Any other way would require knowledge of the decision making process within the pipeline, which would be difficult for the pipeline which was selected in your case.

Another options, somewhat unrelated to TPOT, would be to use a simpler model, for which the decision making process is easier to investigate. See for example: http://scikit-learn.org/stable/modules/tree.html#classification

**Comment by pliablepixels** [comment]
@bartdp1 thank you. I think the naive way is the best way for now - I'm going to close this out. Thank you for the reconfirmation.
