### ISSUE TITLE
every generation with the same results

### ISSUE THREAD

**Issue by myjz** [EpistasisLab/tpot#654]
hello，tpot is  so  great idea, i like it so much, however when i use it with my own data and 
tpot_config = {
    'sklearn.ensemble.AdaBoostClassifier': {
        'algorithm':['SAMME'],
        'n_estimators':[50,100,200,300,400],
        'learning_rate':[0.1,0.3,0.5,0.8,1.2]             
    },
}
 like this ,every generation from 1 to 100 with the same results, ls that normal? or why does it behave like this? i would appreciate for your reply,thank you very much!

**Comment by weixuanfu** [comment]
What is your population size? I think the reason should be that the search space is limited with that configuration dictionary.
