### ISSUE TITLE
Issue with subsample parameter of XGBoost classifier in the pipeline string

### ISSUE THREAD

**Issue by bartdp1** [EpistasisLab/tpot#661]
From the _evaluated_invividuals dict i get the following pipeline:
```
'XGBClassifier(RobustScaler(LogisticRegression(input_matrix, LogisticRegression__C=0.01, LogisticRegression__dual=False, LogisticRegression__penalty=l1)), XGBClassifier__learning_rate=0.1, XGBClassifier__max_depth=5, XGBClassifier__min_child_weight=6, XGBClassifier__n_estimators=100, XGBClassifier__nthread=1, XGBClassifier__subsample=0.9500000000000001)'
```

When parsing this string to an (unfitted) pipeline object using:
`creator.Individual.from_string(str, tpot._pset)` i get a syntax error.:

```
  File "C:\Anaconda\lib\site-packages\deap\gp.py", line 133, in from_string
    token = eval(token)
  File "<string>", line 1
    XGBClassifier__subsample=0.9500000000000001
```

I have been able to track this issue down to the fact that 
'XGBClassifier__subsample=0.9500000000000001' is not in the tpot._pset.mappings,, 
'XGBClassifier__subsample=0.95' is.

Any idea on how this issue arises, and how we can permanently fix this?

**Comment by weixuanfu** [comment]
Hmm, somehow it works in my environment. Check the ipython log below:


```
Python 3.5.3 |Anaconda custom (64-bit)| (default, Mar  6 2017, 11:58:13)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from tpot import TPOTClassifier

In [2]: from deap import creator

In [3]: tpot_str = 'XGBClassifier(RobustScaler(LogisticRegression(input_matrix, LogisticRegression__C=0.01, LogisticRegr
   ...: ession__dual=False, LogisticRegression__penalty=l1)), XGBClassifier__learning_rate=0.1, XGBClassifier__max_depth
   ...: =5, XGBClassifier__min_child_weight=6, XGBClassifier__n_estimators=100, XGBClassifier__nthread=1, XGBClassifier_
   ...: _subsample=0.9500000000000001)'

In [4]: tpot = TPOTClassifier()

In [5]: deap_ind = creator.Individual.from_string(tpot_str, tpot._pset)

In [6]: deap_ind
Out[6]:
[<deap.gp.Primitive at 0x7eff18b639f8>,
 <deap.gp.Primitive at 0x7eff18b636d8>,
 <deap.gp.Primitive at 0x7eff18b63138>,
 <deap.gp.Terminal at 0x7eff18b5ba20>,
 <deap.gp.Terminal at 0x7eff18b80120>,
 <deap.gp.Terminal at 0x7eff18b803f0>,
 <deap.gp.Terminal at 0x7eff18b80438>,
 <deap.gp.Terminal at 0x7eff18b8bdc8>,
 <deap.gp.Terminal at 0x7eff18b8bfc0>,
 <deap.gp.Terminal at 0x7eff184e5318>,
 <deap.gp.Terminal at 0x7eff184e5750>,
 <deap.gp.Terminal at 0x7eff184e5798>,
 <deap.gp.Terminal at 0x7eff184e5cf0>]

In [7]: print(deap_ind)
XGBClassifier(RobustScaler(LogisticRegression(input_matrix, LogisticRegression__C=0.01, LogisticRegression__dual=False, LogisticRegression__penalty=l1)), XGBClassifier__learning_rate=0.1, XGBClassifier__max_depth=5, XGBClassifier__min_child_weight=6, XGBClassifier__n_estimators=100, XGBClassifier__nthread=1, XGBClassifier__subsample=0.9500000000000001)
```

**Comment by weixuanfu** [comment]
The 0.9500000000000001 is caused by [this line](https://github.com/EpistasisLab/tpot/blob/v0.9/tpot/config/classifier.py#L71). The `np.arange(0.05, 1.01, 0.05)[-2]` is `0.9500000000000001`

**Comment by bartdp1** [comment]
Could the reason be that i am running python 3.6.2?

**Comment by weixuanfu** [comment]
Hmm, right, I just build a Python 3.6.2 environment and this issue can be reproduced. Also using `XGBClassifier__subsample=0.95` indeed works, but I don't how the pipeline generated from TPOT has `XGBClassifier__subsample=0.9500000000000001` with python 3.6.2. Is this pipeline generated in another python environment? And another weird thing is `np.arange(0.05, 1.01, 0.05)[-2]` in python3.6.2 is `0.95000000000000007` instead.

**Comment by weixuanfu** [comment]
`str(np.arange(0.0, 1.01, 0.05)[-2])` (which is used by TPOT in this [line](https://github.com/EpistasisLab/tpot/blob/v0.9/tpot/base.py#L436)) is `0.95`  in python 3.6.2 but `0.9500000000000001` in my python 3.5.3 environment.

**Comment by bartdp1** [comment]
The pipeline is indeed generated on another environment (3.5.3), which is the cloud environment i use to run the optimization (I pickle the evaluated individuals dict to investigate on my local machine). This seems some kind of floating point precision issue. Would it be somehow possible to set a package wide precision of some sorts?

**Comment by weixuanfu** [comment]
I just updated `numpy` from 1.12.1 to 1.13.3 in the python 3.5.3 env and now `str(np.arange(0.0, 1.01, 0.05)[-2])` is `0.95`. So I think updating numpy via `conda update numpy` should solve this issue.

**Comment by bartdp1** [comment]
Perfect, thanks for your swift investigation. Anything i can do on this issue? Otherwise, i think we can close it :)

**Comment by weixuanfu** [comment]
Cool, closed
