### ISSUE TITLE
sklearn\cross_validation.py:41: DeprecationWarning

### ISSUE THREAD

**Issue by aspiringguru** [EpistasisLab/tpot#663]
deprecation warning from
pipeline_optimizer = TPOTClassifier()

python3Anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

from tpot import TPOTClassifier
pipeline_optimizer = TPOTClassifier()

just installed using the instructions here.
https://epistasislab.github.io/tpot/installing/

using anaconda3 install on windows 10.

Just checked I had updated the packages as per the install instructions. Any suggestions?

**Comment by weixuanfu** [comment]
The warning message is from importing the old version of xgboost (0.6) in TPOT and this warning message won't effect optimization of TPOT. If you want to avoild this warning message, the latest version  of xgboost (0.7) need to be installed in the environment. But the latest version cannot be installed via conda in Windows. You may the [official installation guide](http://xgboost.readthedocs.io/en/latest/build.html) for building xgboost in Windows.
