### ISSUE TITLE
Is there refit to all data when .score is called?

### ISSUE THREAD

**Issue by ogencoglu** [EpistasisLab/tpot#673]
Is there anything similar to scikit-learn GridSearchCV, refit = True?

Meaning that, when k-fold CV is performed, is all of the data fitted one final time before giving a score on an unseen data.

`tpot.score(X_test, y_test)`

**Comment by weixuanfu** [comment]
For now, tpot don't have this `refit` function. But there is a workaround for it via the codes below:

```
best_pipeline = tpot.fitted_pipeline_
best_pipeline.fit(X_test, y_test)
best_pipeline.score(X_test, y_test)
```
