### ISSUE TITLE
Questions on specific details of the GP algorithm

### ISSUE THREAD

**Issue by bartdp1** [EpistasisLab/tpot#674]
Currently i am going to the literature on TPOT, and there are some unclarities in what i read w.r.t. what i find in the code. The main question i have here is a about the selection of individuals that proceed to the next generation. In the code i see that new population is selected from both the old population and the offspring. In the [paper](http://proceedings.mlr.press/v64/olson_tpot_2016.pdf) i found, if i understand correctly it is said that the selection is of the new population is done only from the offspring.

It would be really helpful if you could shed some light on these choices. Are these developments in the recent versions? Are there more major changes in the inner workings of TPOT w.r.t. what is written in the latest papers on TPOT? Thanks a lot in advance :) .

**Comment by weixuanfu** [comment]
Yes, the selection way in the paper is included in TPOT version 0.3-0.6 but we changed it to the  [mu + lambda evolutionary algorithm](http://deap.readthedocs.io/en/master/api/algo.html#deap.algorithms.eaMuPlusLambda) in TPOT 0.7 which was documented in the [release log](https://github.com/EpistasisLab/tpot/releases)

**Comment by bartdp1** [comment]
Thanks! Will close this now. Might reopen if i have further questions

**Comment by bartdp1** [comment]
Sorry for reopening, but is there any literature on the effects of this change on the performance of TPOT yet available?

**Comment by weixuanfu** [comment]
Sorry, we don't any literature so far about the effects of this change in TPOT. But definitely, the mu + lambda algorithm is more advanced algorithm. @rhiever

**Comment by bartdp1** [comment]
Thank @weixuanfu! :)

**Comment by bartdp1** [comment]
@weixuanfu going trough the crossover operator i see two things:
- Two pipelines need a shares primitive in order to be eligible for crossover
- Only one of the two resulting pipelines in a crossover is kept as offspring.
Could you briefly shed some light on these choices?
(PS: hope you don't mind that i abuse this issue a bit for some short questions, please let me know if you think this should be done otherwise :))

**Comment by weixuanfu** [comment]
Yes, that is exactly how crossover operator in GP algorithm in TPOT. We tweaked codes based on [varOr in deap](http://deap.readthedocs.io/en/master/api/algo.html?highlight=varOr#deap.algorithms.varOr). `varOr` should only keep one child from a crossover since the percentage of offspring due to crossover should be equal to the probability of mating two individuals.

**Comment by bartdp1** [comment]
Thanks, that explains the second point. Why should they have a primitive in common in order to be eligible for crossover?

**Comment by weixuanfu** [comment]
We had a lot discussions about this. Please check the related issue #503 and PR #506.

**Comment by bartdp1** [comment]
Thanks again @weixuanfu!
