### ISSUE TITLE
tpotRegressor is giving large negative value

### ISSUE THREAD

**Issue by rishabhjain09** [EpistasisLab/tpot#675]
for regression tpotRegressor is giving large negative value  , whereas if you try tpotclassifier for regression problem it gives a value in range from 0 to 1 , why so ?

**Comment by weixuanfu** [comment]
Related issue #425 #612 

Please check [TPOT API](https://github.com/EpistasisLab/tpot/issues/612), the scoring function is `accuracy` for TPOTClassifier, which is in range from 0 to 1. But it is `neg_mean_squared_error` for TPOTRegressor that stands for negated value of mean squared error. Please check [this link](http://scikit-learn.org/stable/modules/model_evaluation.html#common-cases-predefined-values) for more details

**Comment by weixuanfu** [comment]
I close this issue. Please feel free to re-open the issue if you have any more questions
