### ISSUE TITLE
Is there a way to limit the maximum number of estimators?

### ISSUE THREAD

**Issue by tehlinger** [EpistasisLab/tpot#686]
I understand that it is possible to limit the type of estimators TPOT with config files.
I wonder if it is possible to limit the total number of estimators returned in the pipeline at the end.

Thank you very much,

**Comment by rhiever** [comment]
You can choose a pipeline off the Pareto front (accessed via `tpot_obj.pareto_front_fitted_pipelines_`, see the [TPOT API](https://epistasislab.github.io/tpot/api/)) that has lower complexity than the highest-accuracy pipeline. TPOT uses multi-objective optimization to maximize the tradeoffs between predictive ability and pipeline complexity.

I believe @weixuanfu is also working on a primitive grammar for TPOT that would support this issue.

**Comment by tehlinger** [comment]
Thank you very much!

**Comment by IamAVB** [comment]
I know pareto front in general. Where Can I find materials to read how pareto front is used in TPOT exactly?
