### ISSUE TITLE
unable to call tpot into python script 

### ISSUE THREAD

**Issue by alokgogate** [EpistasisLab/tpot#687]
Hello, 
when I try running tpot classifier as a python script file then I am unable to import tpot.classifier however I am able to run tpot classifier in a jupyter notebook? Any clue as to why this may be the case?
thanks

**Comment by weixuanfu** [comment]
Sounds like a python environment issue. Please make sure the python scripts are running with python in jupyter notebook

**Comment by alokgogate** [comment]
The python environment is the same I have checked that...

**Comment by weixuanfu** [comment]
Can you please provide more details information? Like stdout/stderr?

**Comment by alokgogate** [comment]
Traceback (most recent call last):
  File "tpot_1.py", line 6, in <module>
    from tpot.builtins import StackingEstimator
  File "code/scripts/python/tpot.py", line 6, in <module>
    from tpot import TPOTClassifier
ImportError: cannot import name 'TPOTClassifier'

**Comment by weixuanfu** [comment]
I know this issue now. You just need simply rename the file `code/scripts/python/tpot.py`, which cause conflicts when importing tpot.

**Comment by alokgogate** [comment]
Thanks @weixuanfu that solved it!
