### ISSUE TITLE
Hope tpot support LightGBM.

### ISSUE THREAD

**Issue by Chianghung** [EpistasisLab/tpot#688]
AS the title, advise tpot to support LightGBM and provide one option to specify some algorithms.
Thanks very much.

**Comment by weixuanfu** [comment]
You could try to customize operators within TPOT with LightBGM’s scikit-learn API. Please check [the link](https://epistasislab.github.io/tpot/using/#customizing-tpots-operators-and-parameters) for more details.

**Comment by ballcap231** [comment]
> You could try to customize operators within TPOT with LightBGM’s scikit-learn API. Please check [the link](https://epistasislab.github.io/tpot/using/#customizing-tpots-operators-and-parameters) for more details.

Could you give an example?
I'm confused how one would use lightgbm if it's not provided as an option in TPOT's config dict for operators:
https://github.com/EpistasisLab/tpot/blob/master/tpot/config/regressor.py

**Comment by weixuanfu** [comment]
@ballcap231 please check the example in issue #808
