### ISSUE TITLE
What does TPOT use for optimizing the models? Does it use Grid Search or something related to genetic programming?

### ISSUE THREAD

**Issue by TheBrownViking20** [EpistasisLab/tpot#689]
So, I created a notebook on kaggle demonstrating the use of tpot. So far the response has been good.
[Click here to view](https://www.kaggle.com/thebrownviking20/tpot-a-great-tool-to-automate-your-ml-workflow)

However, a fellow kaggler thought/assumed that tpot uses Grid Search to optimize the models. Is it true or does genetic programming has some role in optimization of models? Or does tpot use both?

**Comment by weixuanfu** [comment]
Thank you for the notebook of using TPOT. TPOT only uses genetic programming for optimization.

**Comment by rhiever** [comment]
Thank you for putting that great kernel together, @TheBrownViking20! I answered your question directly on the kernel.

**Comment by TheBrownViking20** [comment]
@rhiever Yeah, just saw that. Thanks. By the way, you guys are doing some awesome work here. Keep up the good work.
