### ISSUE TITLE
Score from pipeline_optimizer is different than score in exported pipeline

### ISSUE THREAD

**Issue by scolemann** [EpistasisLab/tpot#691]
Hi,

I've noticed that the score in the pipeline_optimizer.score(testing_features, testing_target)), which I print upon completion, is different than the score in the tpot_exported_pipeline.py where it says "# Score on the training set was x"

It seems the number that I print from pipeline_optimizer is always lower than the one listed in the file.  I expected them to be the same.  Can you explain the difference?

Thanks!

**Comment by weixuanfu** [comment]
Hmm, that score should be average CV score used in optimization process. I
agree that it is a little confusing in export codes. Thank you for
reporting this issue.I will make a PR for refining export function.
