### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory 

### ISSUE THREAD

**Issue by JYLFamily** [EpistasisLab/tpot#696]
Hi Tpot Team:

  File "/data/finupcard_python/anaconda3/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/data/finupcard_python/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 26, in __init__
    self._launch(process_obj)
  File "/data/finupcard_python/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

parameter
TPOTClassifier(
            scoring="roc_auc",
            n_jobs=-1,
            verbosity=2
        )

in linux server.

Thank you~

**Comment by szaydel** [comment]
This looks like a problem at a much lower layer. The system on which this was running could have been critically low on available resources at the time this happened. Is there any way to track down whether there were any memory shortfalls when this error occurred? You got back an OSError, which Python got back from the system, and this really has nothing to do with the package.

**Comment by JYLFamily** [comment]
It will not appear error if I set generations=1 and population_size=1 .

**Comment by szaydel** [comment]
What is likely going on is, the higher these values, the more memory is demanded from a system. You should consider finding means to measure available memory before and during these runs, and as you change these values observe how memory usage changes. My guess is, at some point your system simply refuses to allocate more. If you get an `OSError` in Python, you are getting it from the underlying system. This may of course be limited to the space of an individual process. There may be a constraint in place on how much memory any unpriv'd process can alloc before it is denied, or could well just be a system limitation. At any rate, the starting point is figuring out if you are running out of memory.

**Comment by weixuanfu** [comment]
Please try n_jobs = 8 or other number lower than your CPU cores to reduce memory usage.

**Comment by JYLFamily** [comment]
I will try it. Thank you @szaydel and @weixuanfu .

**Comment by xialeizhou** [comment]
same error! n_jobs = 1 on OSX,  pls help me~~~
