### ISSUE TITLE
how to constrain models further

### ISSUE THREAD

**Issue by zsurnz** [EpistasisLab/tpot#697]
Hi, I am interested in ML as a complement to physically-based models to predict some molecular properties from relatively small datasets (~100-1000 data points). For now I started using TPOT from command-line only and would need advice regarding how to lay focus on simple models (beyond the TPOT light config) and apply stringent validation criteria in this context.
I have in particular two questions :
* TPOT options allow me to select the number of folds in cross-validations. However I can find no way of selecting a number of repetitions with different splits, as done with -reps options using waffles: http://csce.uark.edu/~mgashler/waffles/command/learn.html. 
* Regarding -maxeval: it is stated that this option required an integer. However, I already get quite advanced pipelines with -maxeval 1. Set a floating point value < 1 for this option does not prevent TPOT to run, however I wonder if there is a reason why it should be an integer.

**Comment by weixuanfu** [comment]
`maxeval` can be any positive float. We will update document for this issue.

For integer inputs of cv parameter in command-line, if the estimator is a classifier and y is either binary or multiclass, [StratifiedKFold](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html) is used. In all other cases, [KFold](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html#sklearn.model_selection.KFold) is used. For more advanced usage of `cv` parameter, please check `cv` parameter in [TPOT API](https://epistasislab.github.io/tpot/api/) to customize CV with an object to be used as a cross-validation generator or an iterable yielding train/test splits.

**Comment by zsurnz** [comment]
Thank you, following your links I found that RepeatedKFold is what I was looking for. I will use TPOT from Python then as the API seems much more feature-rich.
