### ISSUE TITLE
StackingEstimator Interpretation of Exported Pipeline

### ISSUE THREAD

**Issue by cpereir1** [EpistasisLab/tpot#698]
Hi!
I am ran the TPOT classifier as follows:

pipeline_optimizer = tpot.TPOTClassifier(warm_start=True, periodic_checkpoint_folder="C:\Users\...",
                                         verbosity=3, max_eval_time_mins=20, config_dict='TPOT light')

On a training set of shape 1871, 18.

I obtained the following exported pipeline:

exported_pipeline = make_pipeline(
    make_union(
        StackingEstimator(estimator=make_pipeline(
            SelectPercentile(score_func=f_classif, percentile=42),
            StackingEstimator(estimator=KNeighborsClassifier(n_neighbors=35, p=1, weights="uniform")),
            GaussianNB()
        )),
        FunctionTransformer(copy)
    ),
    DecisionTreeClassifier(criterion="gini", max_depth=5, min_samples_leaf=1, min_samples_split=13)
)

I am having doubts regarding what is the flow that is suggested.
My interpretation is:
1. Percentile features are calculated
2. kNN classification occurs
3. Both results are added as features to the dataset
4. GaussianNB classifier is applied to the complete dataset

Is this correct?

Thanks for your help!

BR

**Comment by weixuanfu** [comment]
[StackingEstimator](https://github.com/EpistasisLab/tpot/blob/e0c526b543fd8175d67105f08711dc4a9d82aeb0/tpot/builtins/stacking_estimator.py) is a meta-transformer for adding predictions and/or class probabilities as synthetic feature(s). Your interpretation is correct for the part below:

```
make_pipeline(
SelectPercentile(score_func=f_classif, percentile=42),
StackingEstimator(estimator=KNeighborsClassifier(n_neighbors=35, p=1, weights="uniform")),
GaussianNB()
)
```
After the predictions in this part should be added to input X as synthetic features and then pass to DecisionTreeClassifier.

**Comment by cpereir1** [comment]
Thanks for the reply!

Can you explain further why should the results be passes to a decision
tree? I miss to locate that indication on the output.

Thanks a lot!

BR,
Carmina

**Comment by cpereir1** [comment]
Thanks weixuanfu for your reply!
