### ISSUE TITLE
Why Genetic Programming is still used instead of latest heuristic methods

### ISSUE THREAD

**Issue by earthat** [EpistasisLab/tpot#707]
Hi, I opened the issue as I am working on the research issues in machine learning to get the optimal set of parameters in a classifier along with optimal selection of features etc. 

## Genetic Programming is Old

I found that there are many other heuristic optimization algorithms which perform better than GA as it stuck into local optima and may not give the optimal solution, also converging time is higher. 

My question: is there any specific reason to use GP in your development rather than other methods.

**Comment by weixuanfu** [comment]
Please check comments in the related issues #335

**Comment by earthat** [comment]
@weixuanfu I suppose that issue is not for what I asked. I am looking for any particular reason to use GP to optimize the model

**Comment by weixuanfu** [comment]
We found GP worked better in most of our benchmarks, mostly included in pmlb (which is mentioned by @rhiever in that related issue).

**Comment by rhiever** [comment]
Two more reasons for using GP (and population-based EC in general) are:

1) GP and EC allow for flexible solution representations, which means TPOT pipelines can vary in size and complexity during the optimization process. Not all optimization algorithms easily support this feature, which has become integral to TPOT.

2) Population-based optimizers allow us to use Pareto optimization, which optimizes solutions across multiple criteria simultaneously. In TPOT, the optimizer maximizes prediction accuracy while minimizing pipeline complexity, and at the end provides the Pareto front showing the discovered optimal trade-off between those criteria. Most other optimization techniques do not offer this feature.

So yes, GP and EC are old ideas, but so is gradient descent. New doesn't imply better, and in fact old ideas are often more refined (see: deep learning).
