### ISSUE TITLE
Feature selection using TPOT

### ISSUE THREAD

**Issue by IamAVB** [EpistasisLab/tpot#710]
Hi All,
     My aim is to use Genetic Programming for feature selection. For this is I am using TPOT by giving the just one classification model and some known hyper parameter values as input through config_dict along with MDR type which uses different sklearn feature selection operators to create populations in different generations. I am using  the classification accuracy as feature set fitness value. Will TPOT be used this way to do feature selection (by GP)? Correct my thought process if I am wrong.

Thanks

**Comment by weixuanfu** [comment]
You could try to check the example in the [link](https://epistasislab.github.io/scikit-rebate/using/#acquiring-feature-importance-scores) to get importance scores from MultiSURF or other relief-based feature selection algorithms in the optimized pipeline from TPOT if the pipeline is a simply linear pipeline. I answered this question in details via replying your email.

**Comment by weixuanfu** [comment]
I closed this issue because it has the same name with #706
