### ISSUE TITLE
Issue in Documentation Page

### ISSUE THREAD

**Issue by samratp-zz** [EpistasisLab/tpot#714]
The documentation in "Using TPOT" -> "Scoring Functions" ([http://epistasislab.github.io/tpot/using/](http://epistasislab.github.io/tpot/using/)) is broken because of a missing tag in the HTML code.

The below code in line 483 should be enclosed in class "Python"

code class="Python" 

from tpot import TPOTClassifier

**Comment by weixuanfu** [comment]
Thank you for catching this. I will fix it soon.

**Comment by weixuanfu** [comment]
The issue was fixed and fixes were pushed to master branch. Thanks again.
