### ISSUE TITLE
How about scaling?

### ISSUE THREAD

**Issue by AGTGreg** [EpistasisLab/tpot#716]
Hello, I'm new here and I would like to make a question about scaling. 

In the documentation, non of the examples scale the features before fitting them to the TPOTClassifier.

```python
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
                                                    train_size=0.75, test_size=0.25)

tpot = TPOTClassifier(generations=5, population_size=20, verbosity=2)
# No scaling before fitting?
"""
scaler = preprocessing.StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
"""
tpot.fit(X_train, y_train)
```

So does this mean that when I fit my own data in TPOTClassifier I don't have to scale the features just like I would normally do with any other Classifier?
Does TPOT do the scaling on its own?

Thank you in advance.

**Comment by weixuanfu** [comment]
TPOT has this [StandardScaler](https://github.com/EpistasisLab/tpot/blob/master/tpot/config/classifier.py#L158) as well as other data transformer in the default configuration and uses GP to check if the data need data transformation in pipeline.

**Comment by AGTGreg** [comment]
Thank you!
