### ISSUE TITLE
optimize based on specific criterion

### ISSUE THREAD

**Issue by terry07** [EpistasisLab/tpot#720]
Could we use TPOT framework for optimizing a dataset with other metric, such as precision or recall?
Thanks for your time and your great contribution.

**Comment by weixuanfu** [comment]
Please check `scoring` parameter in [TPOT API](https://epistasislab.github.io/tpot/api/)

> scoring: string or callable, optional (default='accuracy')
> Function used to evaluate the quality of a given pipeline for the classification problem. The following built-in scoring functions can be used: 
> 
> 'accuracy', 'adjusted_rand_score', 'average_precision', 'balanced_accuracy', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'neg_log_loss','precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc' 
> 
> If you would like to use a custom scorer, you can pass the callable object/function with signature scorer(estimator, X, y). 
> 
> If you would like to use a metric function, you can pass the callable function to this parameter with the signature score_func(y_true, y_pred). TPOT assumes that any function with "error" or "loss" in the function name is meant to be minimized, whereas any other functions will be maximized. This scoring type was deprecated in version 0.9.1 and will be removed in version 0.11. 
> 
> See the section on scoring functions for more details.

**Comment by terry07** [comment]
@weixuanfu great news, thanks for this answer.
