### ISSUE TITLE
control the scrutinized learners that are tuned

### ISSUE THREAD

**Issue by terry07** [EpistasisLab/tpot#721]
Running some examples with TPOT tool, i get that the best classifiers/regressors could be other than DTs.
Could i restrict the spectrum of the learners that are taken into consideration during an optimization step?

Thanks in advance.

**Comment by joseortiz3** [comment]
[The documentation](https://epistasislab.github.io/tpot/using/#customizing-tpots-operators-and-parameters) might guide you.

**Comment by terry07** [comment]
@joseortiz3 thank you.
