### ISSUE TITLE
Is it posible to exclude certain algorithms in a TPOTRegressor or TPOTClassifier?

### ISSUE THREAD

**Issue by sgaseretto** [EpistasisLab/tpot#722]
How can I specify in a TPOTRegressor or TPOTClassifier to exclude certain algorithms? Let's say, for example, to not generate a pipeline that uses Random Forest or something like that. Is it possible to do this, similarly to what can be done with the TPOT's operators and parameters customization.

**Comment by adrose** [comment]
yes, you'll want to modify the corresponding config directory to remove the desired modeling technique.

The standard dictionaries can be found here: https://github.com/EpistasisLab/tpot/tree/master/tpot/config

**Comment by sgaseretto** [comment]
Thanks for the fast response! So basically I can define a tpot_config with all the classifiers and selectors that I want to try and pass it to the TPOTClassifier and than optimize it. Thanks for the clarification
