### ISSUE TITLE
Is it possible to disable StackingEstimator and CombineDFs ?

### ISSUE THREAD

**Issue by lesshaste** [EpistasisLab/tpot#726]
It was suggest on gitter that I ask here.

Is it currently possible  to disable StackingEstimator and CombineDFs ?

**Comment by rhiever** [comment]
cc @weixuanfu

**Comment by weixuanfu** [comment]
@lesshaste sorry for overlooking this issue. For now, there is no official way to disable both operators.

One of my dev branch of TPOT called [noCDF_noStacking](https://github.com/weixuanfu/tpot/tree/noCDF_noStacking) has a option named `simple_pipeline`, which can disable both `StackingEstimator` and `CombineDFs` if `simple_pipeline=True` (e.g. `TPOTClassifier(simple_pipeline=True)`). But it is noted that this dev branch is not fully tested yet. If you want to try TPOT without `StackingEstimator` and `FeatureUnion`, you may install this branch in your test environment via the command below:

```
pip install --upgrade --no-deps --force-reinstall git+https://github.com/weixuanfu/tpot.git@noCDF_noStacking
```
