### ISSUE TITLE
Does cv option do anything when given a custom generator?

### ISSUE THREAD

**Issue by sohrabtowfighi** [EpistasisLab/tpot#727]
I am examining the results of my output which make me question whether TPOT is actually using the type of cross validation I specified using the 'cv' parameter. Please hear me out.

I am running a classification problem with the TPOTClassifier and I have set its 'cv' option to 'cv=LeaveOneOut()' so as to run leave one out cross validation internally. During the execution, my terminal read 'Generation 15 - Current best internal CV score: 0.7281553398058253'. I have set TPOT to periodically generate output and the output file reads' 
    
    training_features, testing_features, training_target, testing_target = \
    train_test_split(features, tpot_data['target'].values, random_state=42)

    # Score on the training set was:0.7281553398058253
    exported_pipeline = make_pipeline(
        FeatureAgglomeration(affinity="l1", linkage="average"),
        DecisionTreeClassifier(criterion="gini", max_depth=10, min_samples_leaf=5, min_samples_split=11)
    )

Please notice that the output pipeline uses a train_test_split with default values, not a LeaveOneOut splitter. I am not familiar with TPOT internals so this issue is probably naive. Is it expected behaviour for the pipeline file generated by TPOT to use a train_test_split object, even though I specified cv=LeaveOneOut()?

**Comment by sohrabtowfighi** [comment]
I find that in tpot/tpot/export_utils.py
 the periodically generated output file is based off a template string which has train_test_split statically defined, but the score is taken from the pipeline.

Could someone point me to where TPOT would assign the cross validation scheme, and close this issue?

**Comment by rhiever** [comment]
During the optimization process, TPOT passes whatever is in the `cv` parameter directly to the `cross_val_score` `cv` parameter. Thus, the 'training' score is from whatever cross-validation scheme you passed to the `cv` parameter.

You're correct that the generated Python code from the `export` function is based on a fixed template that uses `train_test_split` for the initial train/test split on the data. We don't have the `export` function generate code with a cross-validation scheme, so there is no configuration for that. You could add a cross-validation scheme yourself by, e.g.,

```Python
training_features, testing_features, training_target, testing_target = \
train_test_split(features, tpot_data['target'].values, random_state=42)

# Score on the training set was:0.7281553398058253
exported_pipeline = make_pipeline(
    FeatureAgglomeration(affinity="l1", linkage="average"),
    DecisionTreeClassifier(criterion="gini", max_depth=10, min_samples_leaf=5, min_samples_split=11)
)

cross_val_score(exported_pipeline, training_features, training_target, cv=LeaveOneOut())
```

Essentially, the generated Python code is meant only to be a starting point for you to integrate the pipeline into your own ML workflow. The `exported_pipeline` (and related imports) are the important part.

**Comment by sohrabtowfighi** [comment]
Yes that makes sense. Thank you for your reply.

**Comment by rhiever** [comment]
Happy to help. Please re-open this issue if you have any more related questions.
