### ISSUE TITLE
TPOTBase.predict_proba doesn't impute values like TPOTBase.predict

### ISSUE THREAD

**Issue by oirontro** [EpistasisLab/tpot#734]
https://github.com/EpistasisLab/tpot/blob/a53ba31d9aa62133a25eb137340558ff01481fe8/tpot/base.py#L866

Maybe the following lines should be inserted before the above line?

    if np.any(np.isnan(features)):
        features = self._impute_values(features)

It seems like the same issue as #682

**Comment by weixuanfu** [comment]
I have fixed this issue in dev branch (see [this line](
https://github.com/EpistasisLab/tpot/blob/development/tpot/base.py#L888) and it will be fixed in next version of TPOT

**Comment by rhiever** [comment]
IMO a better long-term solution to this problem is to refactor the imputation logic to insert a median imputer at the start of every TPOT pipeline when missing values are detected in the training data.

**Comment by PGijsbers** [comment]
From the looks of things, while the current (0.9.4) implementation does produce predictions, but the imputer gets refitted on the test data.

A call to `predict_proba` creates a call to [`_check_dataset`](https://github.com/EpistasisLab/tpot/blob/master/tpot/base.py#L906), in turn `_check_dataset` sets [imputer to None](https://github.com/EpistasisLab/tpot/blob/master/tpot/base.py#L1053) which means that in the consequent [call](https://github.com/EpistasisLab/tpot/blob/master/tpot/base.py#L1070) to `_impute_values` this causes a the Imputer to be [refit](https://github.com/EpistasisLab/tpot/blob/master/tpot/base.py#L1021) on the test data.

When calling `predict` and `predict_proba` the imputer that was fit to the training data should be used instead. `_check_dataset` should not always force an imputer to be fit on the passed data.

**Comment by weixuanfu** [comment]
@PGijsbers Thank you for catching this bug. I just added a patch into TPOT 0.9.5
