### ISSUE TITLE
Accessing feature names of the best model 

### ISSUE THREAD

**Issue by datauni** [EpistasisLab/tpot#735]
@rhiever 
I am running TPOTClassifier on my data and the best model resulted to be LogisticRegression. I am able to access the coefficients via `tpot.fitted_pipeline_.steps[-1][1].coef_`  but since it performed feature selection (from 51 features 12 are being selected) I can not find which features are selected, therefore which coefficient belongs to which feature. I need to interpret my result and say e.g. the gender, age are the most important features etc. 

Thanks

**Comment by rhiever** [comment]
Can you please post the full pipeline generated by TPOT?

**Comment by datauni** [comment]
Thank you for the prompt response, here is the pipeline:

```
# Score on the training set was:0.999646646481159
exported_pipeline = make_pipeline(
    SelectFwe(score_func=f_classif, alpha=0.038),
    MinMaxScaler(),
    LogisticRegression(C=10.0, dual=False, penalty="l1")
)
```
Thanks

**Comment by weixuanfu** [comment]
Please check the example in the [link for scikit-learn Pipeline](http://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html) (see codes after "# getting the selected features chosen by anova_filter")

Below is a demo for the pipeline in this issue.

```python
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.feature_selection import SelectFwe, f_classif
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression

digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
                                                    train_size=0.75, test_size=0.25)


exported_pipeline = make_pipeline(
    SelectFwe(score_func=f_classif, alpha=0.038),
    MinMaxScaler(),
    LogisticRegression(C=10.0, dual=False, penalty="l1")
)


exported_pipeline.fit(X_train, y_train)
# print steps
print(exported_pipeline.steps)
# getting the selected features chosen by selectfwe
exported_pipeline.named_steps['selectfwe'].get_support()
```

**Comment by datauni** [comment]
Thank you so much. @weixuanfu 
It was very helpful.

You may close this issue.

**Comment by Jocker1980** [comment]
@weixuanfu 
Hi,
How to get the features importance with more complex selection in the pipeline ?
Here is my code, but using Tpot there are so many complex pipeline. Is there a generic manner ?

``` python

from sklearn.decomposition import PCA
from sklearn.feature_selection import VarianceThreshold
from sklearn.linear_model import HuberRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import MinMaxScaler

# Average CV score on the training set was:-3.3020662381360717
exported_pipeline = make_pipeline(
    MinMaxScaler(),
    VarianceThreshold(threshold=0.005),
    PCA(iterated_power=7, svd_solver="randomized"),
    HuberRegressor(alpha=0.037700000000000004, epsilon=1.175, max_iter=100)
)

exported_pipeline.fit(training_features, training_target)
results = exported_pipeline.predict(testing_features)

```

Thanks for your help.

**Comment by weixuanfu** [comment]
@Jocker1980 for the pipeline with the more complex selection, I suggest that try the [permutation_importance](https://scikit-learn.org/stable/modules/generated/sklearn.inspection.permutation_importance.html#sklearn.inspection.permutation_importance) function with the pipeline to get permutation feature importance.

**Comment by manbau10** [comment]
I built a model using Logistic regression in TPOT classifier. I used `model.fitted_pipeline_.steps[-1][1].coef_` to get the coefficients. However, the output returns 23 coefficient values, whereas the features are only 10. 

Can someone help on this, please?
