### ISSUE TITLE
How TPOT tune the parameters?

### ISSUE THREAD

**Issue by shuaianuoe** [EpistasisLab/tpot#743]
Hi all,

I am interested in how TPOT tune the parameters.

As a beginner, i know that TPOT is based on  genetic programming. I have a question, does the genetic algorithm has the ability to tune the parameters, such as the lightgbm's paremeters? In other words, what strategy does TPOT use to tune parameters? is grid search or Bayesian optimization or what other methods?

Thank you very much and best regards!
shuai

**Comment by weixuanfu** [comment]
TPOT just uses genetic programming to tune the parameters. If the lightgbm has a scikit-learn API then the answer is yes. 

A related issue #335 #688

**Comment by weixuanfu** [comment]
Here is [lightgbm's scikit-learn API](https://lightgbm.readthedocs.io/en/latest/Python-API.html#scikit-learn-api).  Please check [the link](https://epistasislab.github.io/tpot/using/#customizing-tpots-operators-and-parameters) for more details about how to make a custom configuration for the operators and parameters in TPOT.
