### ISSUE TITLE
Accessing the dataset after being transformed by the pipeline

### ISSUE THREAD

**Issue by cpereir1** [EpistasisLab/tpot#744]
Hi,

I have the following pipeline which I fit to my train data:

pipeline = make_pipeline(
    SelectFwe(score_func=f_classif, alpha=0.048),
    RobustScaler(),
    StackingEstimator(estimator=BernoulliNB(alpha=0.01, fit_prior=True)),
    DecisionTreeClassifier(criterion="gini", max_depth=7, min_samples_leaf=2, min_samples_split=3)
)

This creates 3 additional features resulting from SelectFwe, RobustScaler() and BernoulliNB, and then classifies with a DecisionTreeClassifier.
I am finding it difficult to access the transformed train set (with the the additional features). Is it possible to do so? If not, is it possible to know in which order are the features added? Is it at the left or at the right of the original train set? Is it by the order that they are presented in the pipeline definition?

Thanks in advance!

BR,
Carmina

**Comment by weixuanfu** [comment]
`StackingEstimator` in step 3 should add synthetic feature(s) to left of the features from step 2 RobustScaler.

There is not a very simply way to access those transformed features in the intermediate steps. One work-around is to build a partial pipeline to refit dataset and then to get the transformed features (see a demo below). But by using this way, please set a fix `random_state` if the operators in the pipeline (including the nested operator 'BernoulliNB') has the parameter for getting consistent results.

```python
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.tree import DecisionTreeClassifier
from tpot.builtins import StackingEstimator
from sklearn.feature_selection import SelectFwe, f_classif
from sklearn.naive_bayes import BernoulliNB


digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
                                                    train_size=0.75, test_size=0.25)


partial_pipeline = make_pipeline(
SelectFwe(score_func=f_classif, alpha=0.048),
RobustScaler(),
StackingEstimator(estimator=BernoulliNB(alpha=0.01, fit_prior=True)),
)

partial_pipeline.fit(X_train, y_train)
# get transformed X_train after step 3
X_transformed_after_step3 = partial_pipeline.transform(X_train)
print(X_transformed_after_step3.shape)
```
