### ISSUE TITLE
Feature request: Resume fitting process

### ISSUE THREAD

**Issue by saddy001** [EpistasisLab/tpot#746]
It would be nice to resume the fitting process after program cancellation. Reasons:
* Fits can be very time-consuming. One could shut down the computer and resume fitting on the next day
* It would be possible to resume fitting after changing TPOT parameters that (like n_jobs, generations, use_dask) and don't lose progress. For other parameters of course, TPOT should prevent resuming (scoring, ...)

**Comment by rhiever** [comment]
If you set `warm_start=True` when creating the TPOTClassifier object, TPOT will store its current state after finishing/interruption so you can call `fit` again starting from that point.

**Comment by saddy001** [comment]
Oh :-)
