### ISSUE TITLE
How can I use this toolkit to do multi-output regression?

### ISSUE THREAD

**Issue by offchan42** [EpistasisLab/tpot#747]
For example, I have a bunch of real numbers (camera image from headset) as input and I want to predict where my left hand is relative to the camera (4 numbers, x, y, z, length).
My left hand will be visible on the camera.

`x,y,z` is a unit vector representing direction from camera to the left hand, and `length` is the distance from the camera to the left hand.

So can this tool support predicting multiple outputs? If yes, how could I do it?
If not please suggest me a tool that can do it or another way of solving my problem.

**Comment by rhiever** [comment]
You would have to create a custom TPOT configuration that used operations that support multi-output regression, e.g., the sklearn [MultiOutputRegressor](http://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputRegressor.html#sklearn.multioutput.MultiOutputRegressor). As `MultiOutputRegressor` takes another estimator as a parameter, see our [SelectFromModel example](https://github.com/EpistasisLab/tpot/blob/9c712821c400d3b67f4045b451c687d7fb783a5d/tpot/config/regressor.py#L186-L194) in another configuration dictionary.

I'm not 100% familiar with multi-output support in sklearn, but any operations that work with the `MultiOutputRegressor` and `cross_val_score` should also work with TPOT.

You can read more about custom configuration dictionaries [here](http://epistasislab.github.io/tpot/using/#customizing-tpots-operators-and-parameters).

**Comment by robertritz** [comment]
Could you provide a bit more help with the custom configuration dictionary? I'm attempting to set up a simple custom configuration using the SelectFromModel example you gave. Here is my current config:

```
tpot_config = {
    'sklearn.multioutput.MultiOutputRegressor': {
        'estimator': {
            'sklearn.ensemble.ExtraTreesRegressor': {
                'n_estimators': [100],
                'max_features': np.arange(0.05, 1.01, 0.05)
            }
        }
    }
}
```

And here is my code to run TPOT:

```
pipeline_optimizer = TPOTRegressor(generations=5, population_size=20, max_time_mins=480, n_jobs=-1, verbosity=2, random_state=12345, config_dict=tpot_config)
pipeline_optimizer.fit(X_train, y_train)
print(pipeline_optimizer.score(X_test, y_test))
pipeline_optimizer.export('tpot_exported_pipeline.py')
```

I receive an error:
`ValueError: Error: Input data is not in a valid format. Please confirm that the input data is scikit-learn compatible. For example, the features must be a 2-D array and target labels must be a 1-D array.`

Is it necessary to specify the parameters to search for each algorithm? Before reading the documentation and your example I naively just passed through a list of algorithms like so:

```
tpot_config = {
    'sklearn.multioutput.MultiOutputRegressor': {
        'estimator': ['ExtraTreesRegressor']
      }
}
```

There are sklearn algorithms that are inherently multioutput, but with MultiOutputRegressor I get many more options. Thanks!
