### ISSUE TITLE
Dask not listed as requirement.

### ISSUE THREAD

**Issue by PGijsbers** [EpistasisLab/tpot#755]
Installing TPOT 0.9.4 through PyPI fails to install dask, which is a must-have dependency in the latest version.

Edit: After reading through the source code it seems that dask is supposed to be an optional dependency, but the import at [gp_deap](https://github.com/EpistasisLab/tpot/blob/master/tpot/gp_deap.py#L26) violates this.

**Comment by weixuanfu** [comment]
@PGijsbers Thank you for catching this bug. I just added a patch into TPOT 0.9.5
