### ISSUE TITLE
Categorical Encoders Support

### ISSUE THREAD

**Issue by DataDave-datajoi** [EpistasisLab/tpot#756]
sklearn should adding support for [categorical-encoder](https://github.com/scikit-learn-contrib/categorical-encoding) in 0.20+. But I do not see examples of TPOT doing anything with categorical features, is this supported?

I will usually use it in a [sklearn-pandas](https://github.com/scikit-learn-contrib/sklearn-pandas) DataFrame Mapper:
```python
from sklearn_pandas import DataFrameMapper
from sklearn_pandas import CategoricalImputer
from category_encoders import OneHotEncoder

features = DataFrameMapper([
    (categorical_columns, [CategoricalImputer(), OneHotEncoder()]),
    (boolean_columns, [LabelBinarizer()])
])
```

But does TPOT already do this?

**Comment by weixuanfu** [comment]
From TPOT v0.9 we added [`OneHotEncoder`](https://github.com/EpistasisLab/tpot/blob/v0.9/tpot/config/classifier.py#L158-L161) to handle Categorical features.

From TPOT v0.9.5, we added two builtin operators to handle mixed features (Related PR #560 and issue #549)

**Comment by DataDave-datajoi** [comment]
Understood, thank you. I have added comments to see if I understand args or not, could you verify my understanding of the intent of the arguments?

```python
'tpot.builtins.OneHotEncoder': {
        'minimum_fraction': [0.05, 0.1, 0.15, 0.2, 0.25], # minimum number of categories to use, otherwise use "other" category?
        'sparse': [False],
        'threshold': [10] # minimum number of records per category?
    },
```

**Comment by weixuanfu** [comment]
Oh, please check [this link](https://github.com/EpistasisLab/tpot/blob/master/tpot/builtins/one_hot_encoder.py#L151-L173) for intent of arguments.
