### ISSUE TITLE
No tags in repo since 0.9.0

### ISSUE THREAD

**Issue by dhirschfeld** [EpistasisLab/tpot#757]
Whereas [pypi](https://pypi.org/project/TPOT/0.9.5/#history) is up to `0.9.5`

It's handy to have tags in the repo so users know exactly what code they're running and can do things like see the changes from the released version to master

**Comment by weixuanfu** [comment]
Thanks for your suggestion. We will start tagging every minor release of TPOT since TPOT 0.9.5. I just added the release information of 0.9.5 in this repo.

**Comment by dhirschfeld** [comment]
Happy for this to be closed then!
