### ISSUE TITLE
tpot stuck at 3rd generation without any error

### ISSUE THREAD

**Issue by deadsoul44** [EpistasisLab/tpot#775]
Tpot stuck at 3rd generation (pipeline 268) without any error after running 20 hours. Tpot settings are below. Dataset is very large (900k rows, 50 columns). I use Python 3.6 with Anaconda - Spyder (windows 10). I couldn't even stop the code by hitting the "Stop the current command" at the top-right of the console. 

tpot = TPOTRegressor(verbosity=3, 
                     scoring="neg_mean_squared_error", 
                     random_state=None, 
                     periodic_checkpoint_folder="tpot_v4", 
                     n_jobs=1, 
                     population_size=70,
                     offspring_size=70,
                     generations=10, 
                     max_eval_time_mins=10)

![image](https://user-images.githubusercontent.com/31016182/46478932-a04bbb00-c7f6-11e8-9e19-2eb63cfd2805.png)

I will re-run the code today. I am not sure if the problem is repeatable.

Any idea how to solve this issue?

Thank you.

**Comment by weixuanfu** [comment]
Hmm, I am not sure what happened. It seems that we met a lot of similar issues when using TPOT on Spyder or in Windows OS. Could you please set a `random_state` for reproducing this issue? Or Could you please run TPOT in official python console?
