### ISSUE TITLE
Number of variables to search

### ISSUE THREAD

**Issue by mill1016** [EpistasisLab/tpot#778]
Hello, looked through documentation but I still have a question regarding how many variables TPOT searches.

What parameter determines the number of hyperparameters to search? In GA trems, what determines the number of variables in the chromosone. 

My Understanding:
generations:  Total amount of times to reproduce.  
population_size:  total number of chromosomes

Thanks much for the help.  Great tool, very easy to use.

**Comment by weixuanfu** [comment]
The GP trees in TPOT are strongly typed with [pre-select operators and their parameters](https://epistasislab.github.io/tpot/using/#built-in-tpot-configurations) and those configurations determine search space of nodes and their leaves in the tree-structure. But for now, TPOT don't have a hyperparameter to control the  the height of produced trees.
