### ISSUE TITLE
All my graphs and charts show no results

### ISSUE THREAD

**Issue by Ropena** [EpistasisLab/tpot#786]
I have set up 17.10 and all seems to be running fine. But, when I select any dashboard, the graphs and charts show "No Results." No matter what I chose, it is the same. Also, when I click on Kibana I get this:

Script error. (:0)
Version: 5.6.9
Build: 15629
Error: Script error. (:0)
onerror@https://192.168.15.31:64297/kibana/bundles/commons.bundle.js?v=15629:90:22037
## Context of the issue

Can someone tall me what is going on?

**Comment by weixuanfu** [comment]
Can you please provide more details for reproducing this issue, like a demo?
