### ISSUE TITLE
Why is tpot sleeping?

### ISSUE THREAD

**Issue by CBrauer** [EpistasisLab/tpot#793]
Howdy,
My environment is:

```
Operating system version.... Windows-10-10.0.17134-SP0
Python version is........... 3.6.5
scikit-learn version is..... 0.20.0
pandas version is........... 0.23.4
numpy version is............ 1.15.3
matplotlib version is....... 3.0.1
tpot version is............. 0.9.5
```
Below is a screen shot showing the progress of a TPOT training session, and the usage of my CPU's.  They are all sleeping.
Why?
![tpot](https://user-images.githubusercontent.com/1317234/47958065-84b40b80-df80-11e8-87c6-f66f5bb704e0.png)

Charles

**Comment by weixuanfu** [comment]
I think it is related to [this issue](https://epistasislab.github.io/tpot/using/#crashfreeze-issue-with-n_jobs-1-under-osx-or-linux)

**Comment by CBrauer** [comment]
Hi Weixuan,

 



 

I’m working on Windows 10.  Is there any hope?

 

Charles

**Comment by GinoWoz1** [comment]
Same issue for me on windows 10 via google cloud. Not using spyder, just command line.  Has a weird situation where the CPU drops to 0 and then when I right click on command line the generation updates as well as the pbar object then CPU pumps back up.

**Comment by GinoWoz1** [comment]
**Before click - just started**

![image](https://user-images.githubusercontent.com/17535345/48041793-bb7e5300-e133-11e8-9f5d-6a947480033e.png)



**After click - immediately updates**

![image](https://user-images.githubusercontent.com/17535345/48041808-cc2ec900-e133-11e8-8ddd-eb211d95ac96.png)

**Comment by weixuanfu** [comment]
Could you please try one way mentioned in ["Parallel Training with Dask"](https://epistasislab.github.io/tpot/using/#parallel-training-with-dask)? Please check the [installation guide](https://epistasislab.github.io/tpot/installing/) for installing dask.

**Comment by CBrauer** [comment]
I installed dask and ran my notebook.  It ran for a while and then blew up.  Here is a screen capture of the results. This is very discouraging.  
![dask](https://user-images.githubusercontent.com/1317234/48078419-42681580-e19e-11e8-80a7-a301ae94a441.png)

**Comment by weixuanfu** [comment]
Sorry to see that. I saw only the memory limit is 1Gb. I think the issue is related to how dask handle out-of-memory error (see #779). I think increasing memory limit and larger memory will help.

**Comment by CBrauer** [comment]
Well... I continued to increase memory from 1GB to 16GB and no cigar.
![dask](https://user-images.githubusercontent.com/1317234/48083675-a690d680-e1aa-11e8-9a7f-2aaa9b624611.png)

**Comment by CBrauer** [comment]
I tried moving to Ubuntu and I get a Segmentation fault.  I also get this on Mac OS X Sierra.
My Python 3 script is:
```
def LoadData():
    df = pd.read_csv("data.csv")
    response_name = ['Gain']
    feature_names = ['BoxRatio', 'Thrust', 'Velocity', 'OnBalRun', 'vwapGain']
    mask = feature_names + response_name
    model = df[mask]
    print('model:\n', model.head(5))
    print('\nDescription of model dataset:\n', model[feature_names].describe(include='all'))
    X_train, X_test, y_train, y_test = train_test_split(X,
                                                        y,
                                                       test_size = 0.2,
                                                       random_state = 7)
    return X_train, y_train, X_test, y_test

if __name__ == "__main__":
    import multiprocessing
    multiprocessing.set_start_method('forkserver')

    import pandas as pd
    import numpy as np
    import timeit
    from tpot import TPOTRegressor
    from sklearn.model_selection import train_test_split

    start_time = timeit.default_timer()

    X_train, y_train, X_test, y_test = LoadData()

    p = 100
    g = 100
    tpot = TPOTRegressor(generations=g,
                         population_size=p,
                         random_state=7,
                         verbosity=2)

    tpot.fit(X_train, y_train)
    print('\ntpot:\n', tpot) 

    score = tpot.score(X_test, y_test)   
    print('Score: {0}, generations: {1}, population: {2}'.format(score, g, p)) 

    tpot.export('exported_pipeline_' + str(g) + '_' + str(p) + '_regress.py')

    elapsed = timeit.default_timer() - start_time
    print("\nTotal compute time was: %s" % elapsed)
    print('Done.') 

```

My Bash screen looks like:
![bash](https://user-images.githubusercontent.com/1317234/48522967-5f9c8400-e82f-11e8-82e9-738a4e223f53.png)

Any suggestions would be greatly appreciated.
Charles
