### ISSUE TITLE
I ran TPOT in intel/PyDAAL environment, but i got slower speed. Why?

### ISSUE THREAD

**Issue by Jaimecclin** [EpistasisLab/tpot#801]
hi, 

I want to speed up the TPOT program, so I tried to run TPOT on intel/PyDAAL environment.

As i know, sklearn already used the PyDAAL integrated version.    

But it get more slower in most machine learning methods, only a few methods can be faster, eg. Ridge function.

Does that mean intel/PyDAAL is not suitable for TPOT? Or any mistakes i did?

Additionally, i used n_jobs=-1, but I have to wait more time on training. WHY?

link1: https://github.com/daaltces/pydaal-getting-started
link2: https://software.intel.com/en-us/articles/intel-distribution-for-python-pydaal-module

**Comment by weixuanfu** [comment]
I think it is [related to this issue of using n_jobs](https://epistasislab.github.io/tpot/using/#crashfreeze-issue-with-n_jobs-1-under-osx-or-linux) and maybe [using dask](https://epistasislab.github.io/tpot/using/#parallel-training-with-dask) can be a good solution.

**Comment by Jaimecclin** [comment]
To weixuanfu:

Thanks for your response. I found the answer. I used python 2 and 3 to compare the result. That's my fault.
:)
