### ISSUE TITLE
No information showing when tpot  is running

### ISSUE THREAD

**Issue by chjq201410695** [EpistasisLab/tpot#802]
I want watch the information producted by the running topt. however,  I set verbosity=3, there are no information is showed.

## Context of the issue
system: ubantu 16.08
evironment: jupyter notebook
TPOT version: 0.9.5

## Process to reproduce the issue

data = pd.read_csv('/media/zhouhao/workspace/CJQ/Result/181029_2_database_4w.csv', index_col=0)
y = data.iloc[:,0]
X = data.iloc[:,1:]
X_train,X_text, y_train, y_test =train_test_split(X, y, test_size=0.05,random_state=2018)

pipeline_optimizer = TPOTRegressor(generations=30, population_size=30, cv=4,
                                    random_state=2018, verbosity=3,
                                    mutation_rate=0.85, crossover_rate=0.15,
                                    subsample=0.25,n_jobs=-1,
                                    max_time_mins=60*12,use_dask=True,
                                    early_stop = 10,
                                    periodic_checkpoint_folder=r'/media/zhouhao/workspace/CJQ/Result/model',
                                  )
pipeline_optimizer.fit(X_train,y_train)

## `name of issue` screenshot
![image](https://user-images.githubusercontent.com/29965893/48675906-52b6c200-eb9a-11e8-8298-1c7cb912288b.png)

![image](https://user-images.githubusercontent.com/29965893/48675913-78dc6200-eb9a-11e8-946e-16df81255500.png)

**Comment by weixuanfu** [comment]
I think it is [related to this issue of using n_jobs](https://epistasislab.github.io/tpot/using/#crashfreeze-issue-with-n_jobs-1-under-osx-or-linux) and maybe [using dask](https://epistasislab.github.io/tpot/using/#parallel-training-with-dask) can be a good solution.
