### ISSUE TITLE
unhashable type: 'slice'

### ISSUE THREAD

**Issue by jarlva** [EpistasisLab/tpot#803]
getting error below when trying to fit the exported model. 
Tried converting y to numpy (y.values), same error.

**Code:**
X1 = feather.read_dataframe(file+'X.feather')
y1 = pd.read_pickle(file+'y.pick') 

exported_pipeline = make_pipeline(
    OneHotEncoder(minimum_fraction=0.05, sparse=False, threshold=10),
    StackingEstimator(estimator=GradientBoostingClassifier(learning_rate=0.5, max_depth=4, max_features=0.55, min_samples_leaf=18, min_samples_split=11, n_estimators=100, subsample=0.8500000000000001)),
    ExtraTreesClassifier(bootstrap=False, criterion="gini", max_features=0.3, min_samples_leaf=16, min_samples_split=16, n_estimators=100)
)

exported_pipeline.fit(X1, y1)

**Error:**
`TypeError                                 Traceback (most recent call last)
<ipython-input-12-918b5c137597> in <module>
     12 )
     13 
---> 14 exported_pipeline.fit(X1, y1)
     15 # results = exported_pipeline.predict(testing_features)

/home/userx/py/36env/lib64/python3.6/site-packages/sklearn/pipeline.py in fit(self, X, y, **fit_params)
    263             This estimator
    264         """
--> 265         Xt, fit_params = self._fit(X, y, **fit_params)
    266         if self._final_estimator is not None:
    267             self._final_estimator.fit(Xt, y, **fit_params)

/home/userx/py/36env/lib64/python3.6/site-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params)
    228                 Xt, fitted_transformer = fit_transform_one_cached(
    229                     cloned_transformer, Xt, y, None,
--> 230                     **fit_params_steps[name])
    231                 # Replace the transformer of the step with the fitted
    232                 # transformer. This is necessary when loading the transformer

/home/userx/py/36env/lib64/python3.6/site-packages/sklearn/externals/joblib/memory.py in __call__(self, *args, **kwargs)
    327 
    328     def __call__(self, *args, **kwargs):
--> 329         return self.func(*args, **kwargs)
    330 
    331     def call_and_shelve(self, *args, **kwargs):

/home/userx/py/36env/lib64/python3.6/site-packages/sklearn/pipeline.py in _fit_transform_one(transformer, X, y, weight, **fit_params)
    612 def _fit_transform_one(transformer, X, y, weight, **fit_params):
    613     if hasattr(transformer, 'fit_transform'):
--> 614         res = transformer.fit_transform(X, y, **fit_params)
    615     else:
    616         res = transformer.fit(X, y, **fit_params).transform(X)

/home/userx/py/36env/lib64/python3.6/site-packages/tpot/builtins/one_hot_encoder.py in fit_transform(self, X, y)
    388         """
    389         if self.categorical_features == "auto":
--> 390             self.categorical_features = auto_select_categorical_features(X, threshold=self.threshold)
    391 
    392         return _transform_selected(

/home/userx/py/36env/lib64/python3.6/site-packages/tpot/builtins/one_hot_encoder.py in auto_select_categorical_features(X, threshold)
     69             unique = np.unique(X.data[indptr_start:indptr_end])
     70         else:
---> 71             unique = np.unique(X[:, column])
     72 
     73         feature_mask.append(len(unique) <= threshold)

/home/userx/py/36env/lib64/python3.6/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2686             return self._getitem_multilevel(key)
   2687         else:
-> 2688             return self._getitem_column(key)
   2689 
   2690     def _getitem_column(self, key):

/home/userx/py/36env/lib64/python3.6/site-packages/pandas/core/frame.py in _getitem_column(self, key)
   2693         # get column
   2694         if self.columns.is_unique:
-> 2695             return self._get_item_cache(key)
   2696 
   2697         # duplicate columns & possible reduce dimensionality

/home/userx/py/36env/lib64/python3.6/site-packages/pandas/core/generic.py in _get_item_cache(self, item)
   2485         """Return the cached item, item represents a label indexer."""
   2486         cache = self._item_cache
-> 2487         res = cache.get(item)
   2488         if res is None:
   2489             values = self._data.get(item)

TypeError: unhashable type: 'slice'`

**Comment by weixuanfu** [comment]
How about converting `X1` to `np.ndarray`, like `X1.values`?

**Comment by jarlva** [comment]
That seems to fix it (still evaluating results, it finishes without errors).
Any chance to fix tpot?
