### ISSUE TITLE
TPOT persistent problem. joblib.load does not agree with joblib.dump.

### ISSUE THREAD

**Issue by CBrauer** [EpistasisLab/tpot#814]
Hello,

When I store a trained TPOT model to local storage it does not agree with the reloaded model.

I have a test case on [https://github.com/CBrauer/CypressPoint.github.io/tree/master/Issue](url)
The "notebook_regress.ipynb" shows the problem.  I also enclosed the script "run_regress.py" that shows how the exported script was generated.

I store the trained model with:
`
exported_pipeline.fit(X_train, y_train)
joblib.dump(exported_pipeline, 'tpot_regress.pkl')
`

And when I read it back with

`new_pipeline = joblib.load('tpot_regress.pkl')
assert (exported_pipeline == new_pipeline), 'exported_pipeline != new_pipeline'`

the assert fails.

Charles

**Comment by weixuanfu** [comment]
I don't think `==` is useful here to check if the two scikit-learn classes are identical.

You can check `str(exported_pipeline.get_params()) == str(new_pipeline.get_params())` or `str(exported_pipeline) == str(new_pipeline)` instead.

**Comment by CBrauer** [comment]
Thanks.
