### ISSUE TITLE
CV parameters

### ISSUE THREAD

**Issue by ckliu1402** [EpistasisLab/tpot#815]
Hello, I'm confused about the StratifiedShuffleSplit method with cv parameter, 
my code is as follow:

> sss= StratifiedShuffleSplit(5,test_size=0.33,random_state=None)
> model = TPOTClassifier(scoring='accuracy',generations=10,verbosity=0, population_size=200,n_jobs=-1,cv=sss,warm_start=False,early_stop=True,memory='auto',max_eval_time_mins = 10)
> model.fit (X,y)

I have a few questions, 
1) Is the StratifiedShuffleSplit method successfully applied into TPOTClassifier yet?
2) Should I add subsample parameter (subsample=0.67) to split the data? or StratifiedShuffleSplit has done the splitting already?

Thanks for answering!

**Comment by weixuanfu** [comment]
1. Yes, the TPOTClassifier will use StratifiedShuffleSplit instead of `StratifiedKFold` (default) when cv is specified as this CV splitter.
2. No need to add subsample parameter to split the data. `subsample` is just getting a subset of dataset before CV.

**Comment by ckliu1402** [comment]
Thanks! You just cleared my confusion! Thank you so much!

**Comment by ckliu1402** [comment]
> 1. Yes, the TPOTClassifier will use StratifiedShuffleSplit instead of `StratifiedKFold` (default) when cv is specified as this CV splitter.
> 2. No need to add subsample parameter to split the data. `subsample` is just getting a subset of dataset before CV.

Can StratifiedShuffleSplit avoid the over-fitting to a certain extent? or I should add subsample if I need to do avoidance?

Besides, are there any other methods that can avoid the over-fitting in TPOT?

**Comment by weixuanfu** [comment]
I think StratifiedShuffleSplit and default StratifiedKFold can avoid the overfitting issue in most of case.
