### ISSUE TITLE
How's the splitting data used?

### ISSUE THREAD

**Issue by bhavsarpratik** [EpistasisLab/tpot#816]
Hi, I need help on what happens to the train data while splitting and optimising.
I am working with this custom tpot config where I want to just use RandomForest as the model.

{
    "sklearn.ensemble.RandomForestClassifier": {
      "n_estimators": [
        50,
        100,
        150,
        200,
        500
      ],
      "criterion": [
        "entropy"
      ],
      "bootstrap": [
        true
      ],
      "min_samples_leaf": [
        10,
        15,
        20
      ],
      "max_features": [
        3,
        "sqrt"
      ]
    }
  }

As per the API, if subsample is 1.0, complete data is used for optimisation which is further split 75/25 train/test.

Is this correct?
The pipelines generated while genetic optimisation and cross-validated are tested on 75% of data.

After the best parameters are found, is the model finally trained on the complete data and returned?

Randomforests having same parameters will be different when trained over 75% data and 100% data.

Is the best model that is returned by model.fitted_pipeline_ trained over 100% data?

**Comment by weixuanfu** [comment]
TPOT internally use [`cross_val_score`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html) for evaluating pipeline via mean CV score. In default setting the CV split is 5-fold StratifiedKFold for classification task but KFold for regression task.

**Comment by bhavsarpratik** [comment]
Right @weixuanfu. 
model.fitted_pipeline_ returns the best model.
Can you please confirm that on how much data is this best model trained on? Is it 75%?

**Comment by weixuanfu** [comment]
The best module is trained on the full dataset in `.fit()` function.
