### ISSUE TITLE
Determine best estimator of one certain type (not an ensemble)

### ISSUE THREAD

**Issue by lucasmaia1202** [EpistasisLab/tpot#819]
I would like to know if it is possible to estimate all parameters of a certain Machine Learning Algorithm. Like: if one wanted to get the best SVM model for one dataset, how would one proceed?

**Comment by weixuanfu** [comment]
TPOT did not support this application so far, but you could try [scikit-deap](https://github.com/rsteca/sklearn-deap) for this purpose.
