### ISSUE TITLE
TPOTRegressor doesn't support categorical features

### ISSUE THREAD

**Issue by mirik123** [EpistasisLab/tpot#820]
## Context of the issue
When running TPOTRegressor on https://www.kaggle.com/c/house-prices-advanced-regression-techniques it fails with error:
```JS
  File "C:\ProgramData\Anaconda3\lib\site-packages\tpot\base.py", line 1064, in _check_dataset
    if np.any(np.isnan(features)):
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

## Process to reproduce the issue
```python
from tpot import TPOTRegressor
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score, make_scorer

train = pd.read_csv('/kaggle/house_prices/train.csv', parse_dates=True, index_col=0)
y_train = np.log(train['SalePrice'])
X_train = train.drop('SalePrice', axis=1)
scorer = make_scorer(lambda y_pred, y_train: np.sqrt(np.mean((y_pred - y_train) ** 2)), greater_is_better=False)
pipeline_optimizer = TPOTRegressor(scoring=scorer, generations=10, population_size=50, verbosity=2, cv=5)
pipeline_optimizer.fit(X_train, y_train)
pipeline_optimizer.export('tpot_houses_pipeline.py')
```

## Possible fix
It works when I convert categorical values to floats:
```python
categorical = X_train.select_dtypes(include=['object'])
numerical = X_train.select_dtypes(exclude=['object'])
categorical = np.array([pd.Categorical(categorical[col]).codes for col in categorical.columns]).T
X_train = np.concatenate((numerical, categorical), axis=1)
```

**Comment by weixuanfu** [comment]
The reason of the TypeError is that the input `X_train ` is a `pandas.DataFrame` and the current version of TPOT does not fully support `pandas.DataFrame` input.

**Comment by mirik123** [comment]
I run it with "values" and the result is the same:
```python
y_train = np.log(train['SalePrice'].values)
X_train = train.drop('SalePrice', axis=1).values
```
`TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

**Comment by weixuanfu** [comment]
OK, I see. I just found that there are **string** type values in the Kaggle raw data. I think transforming dataset via [OneHotEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html#sklearn.preprocessing.OneHotEncoder) before using TPOT can be another solution.

**Comment by mirik123** [comment]
OK, I see. I'll add some preprocessing to convert all object data to floats.

**Comment by ravisurdhar** [comment]
May I suggest using pd.isna instead of np.isnan? I'm having a similar issue with the TPOTClassifier where I am passing in a pandas DataFrame consisting of columns with numpy.int64 and numpy.bool entries and no NaNs, but I still get the Numpy TypeError above. Changing the call to pd.isna fixes the issue.

Even appending .values to the end of my DataFrame when passing it to tpot.fit() doesn't work for me, and there are no strings in the data, just int and bool.

**Comment by sam-s** [comment]
I get this error with all-numeric dataframe:
```python
collections.Counter(work10k_num.dtypes)

Counter({dtype('float64'): 13,
         dtype('int64'): 374,
         dtype('bool'): 15,
         dtype('uint8'): 1})
```

and then
```
~/.virtualenvs/.../site-packages/tpot/base.py in _check_dataset(self, features, target, sample_weight)
   1062                 )
   1063         else:
-> 1064             if np.any(np.isnan(features)):
   1065                 self._imputed = True
   1066                 features = self._impute_values(features)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by weixuanfu** [comment]
`np.isnan` can be applied to np.arrays of native dtype (such as `np.float64`). I saw 'bool' dtype in your dataframe, so type conversion or encoding may be needed.

**Comment by sam-s** [comment]
`bool` is a numeric type, isn't it?

**Comment by weixuanfu** [comment]
TPOT does not fully support `pandas.DataFrame` input yet. So I supposed that  `work10k_num.values` is used in your codes.

For reproducing this issue related to `bool` type, try the demo below:


```python
import numpy as np
import pandas as pd
import collections
d = {'col1': [1.0, 2.0], 'col2': [3, 4], 'col3': [1, 2]}
df = pd.DataFrame(data=d)
df['col3'] = df['col3'].astype(np.uint8)
print(collections.Counter(df.dtypes))
print(np.isnan(df.values)) # this will pass without bool type 

d = {'col1': [1.0, 2.0], 'col2': [3, 4], 'col3': [1, 2],'col4': [True, False]}
df = pd.DataFrame(data=d)
df['col3'] = df['col3'].astype(np.uint8)

print(collections.Counter(df.dtypes))
print(np.isnan(df.values)) # this will raise error due to bool type
```
