### ISSUE TITLE
Kernel dies during on_boundary in jupyter

### ISSUE THREAD

**Issue by unclegueralt** [EpistasisLab/tpot#821]
Hi, I was trying to run this notebook for my FEM project, the problem is kernel dies when I get to running the on_boundary block. I have no idea what is happening, I searched and I saw people said reinstalling kernel might help, which didnt. any ideas? 
![2018-12-17](https://user-images.githubusercontent.com/43437396/50092209-bc63d380-020d-11e9-8b0d-dc762ee38af7.png)

[part3 (1).zip](https://github.com/EpistasisLab/tpot/files/2686370/part3.1.zip)

**Comment by weixuanfu** [comment]
Based on the screenshot, it seems it is not a TPOT issue.
