### ISSUE TITLE
Documentation contradictory: Default offspring size

### ISSUE THREAD

**Issue by kasuteru** [EpistasisLab/tpot#831]
I found a contradiction in the tpot api documentation and am not sure which statement is correct:

[http://epistasislab.github.io/tpot/api/](http://epistasislab.github.io/tpot/api/)

> class tpot.TPOTClassifier(generations=100, population_size=100,
>                           **offspring_size=None**, mutation_rate=0.9,
>                           crossover_rate=0.1,
>                           scoring='accuracy', cv=5,
>                           subsample=1.0, n_jobs=1,
>                           max_time_mins=None, max_eval_time_mins=5,
>                           random_state=None, config_dict=None,
>                           warm_start=False,
>                           memory=None,
>                           use_dask=False,
>                           periodic_checkpoint_folder=None,
>                           early_stop=None,
>                           verbosity=0,
>                           disable_update_check=False)

But the documentation below states:

> offspring_size: int, optional **(default=100)**
> 
>     Number of offspring to produce in each genetic programming generation. Must be a positive number. 
>

**Comment by weixuanfu** [comment]
The default value of `offspring_size` is None. In this case, the `offspring_size`  is equal to `population_size` in genetic programming.,
