### ISSUE TITLE
data filename could be provided when exporting

### ISSUE THREAD

**Issue by sergiolucero** [EpistasisLab/tpot#838]
It is always a bit of a pain in the neck to have to replace 'PATH/TO/DATA/FILE' with the actual name when exporting, and usually this is a known variable. Also, separator and dtype could be replaced by something like "cols=['...']".

Adding data_filename to export in base.py (and then to export_pipeline in export_utils) is trivial. The other options could be discussed.

**Comment by weixuanfu** [comment]
Sounds a good idea! I think it can be easily added to export function.

**Comment by weixuanfu** [comment]
The issue has been fixed in a new version of TPOT (v0.10.1). Please feel free to reopen it if you have any questions or suggestions.
