### ISSUE TITLE
Question: How to report multiple scoring metrics after fitting

### ISSUE THREAD

**Issue by sskaye** [EpistasisLab/tpot#848]
After fitting TPOT to the training data, I'd like to print the scores for multiple scoring functions, not just the one used to optimize the pipeline.

Is there a way to do this?

For example, I fit a regression pipeline using training data and scoring = neg. mean squared error, then output the score for test data using neg. mean square error and r2.

**Comment by weixuanfu** [comment]
The demo below is for getting those scores after `tpot_obj.fit()`. Please check [this link](https://scikit-learn.org/stable/modules/model_evaluation.html#common-cases-predefined-values) for more scoring metrics.

```python
from sklearn.metrics import SCORERS
best_pipeline = tpot_obj.fitted_pipeline_
# r2 score
holdout_score_r2 = SCORERS['r2'](
                          best_pipeline,
                          testing_features,
                          testing_target
                      )

# neg_mean_squared_error
holdout_score_nmse = SCORERS['neg_mean_squared_error'](
                          best_pipeline,
                          testing_features,
                          testing_target
                      )

```

**Comment by sskaye** [comment]
Thanks! Worked perfectly.
