### ISSUE TITLE
Test TPOT ERROR

### ISSUE THREAD

**Issue by zhengxinvip** [EpistasisLab/tpot#858]
I have installed TPOT but when I use this code test it.
from tpot import TPOTRegressor
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

housing = load_boston()
X_train, X_test, y_train, y_test = train_test_split(housing.data, housing.target)
                                                   # ,train_size=0.75, test_size=0.25)

tpot = TPOTRegressor(generations=20, verbosity=2) 
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
tpot.export('pipeline.py')

ERROR:
ImportError                               Traceback (most recent call last)
<ipython-input-2-80608a0debf2> in <module>()
----> 5 from tpot import TPOTRegressor
      6 import pandas as pd
      7 import numpy as np

C:\ProgramData\Anaconda3\lib\site-packages\tpot\__init__.py in <module>()
     25 
     26 from ._version import __version__
---> 27 from .tpot import TPOTClassifier, TPOTRegressor
     28 from .driver import main

C:\ProgramData\Anaconda3\lib\site-packages\tpot\tpot.py in <module>()
     24 """
     25 
---> 26 from .base import TPOTBase
     27 from .config.classifier import classifier_config_dict
     28 from .config.regressor import regressor_config_dict

C:\ProgramData\Anaconda3\lib\site-packages\tpot\base.py in <module>()
     44 from scipy import sparse
     45 import deap
---> 46 from deap import base, creator, tools, gp
     47 from copy import copy, deepcopy
     48 

ImportError: cannot import name 'base'
How can I fix it. Thanks.

**Comment by weixuanfu** [comment]
Which version of `deap` in your environment? Could you please try `python -c "import deap; print('deap %s' % deap.__version__)"` to find out the information?

**Comment by zhengxinvip** [comment]
> Which version of `deap` in your environment? Could you please try `python -c "import deap; print('deap %s' % deap.__version__)"` to find out the information?

1.2.2

**Comment by weixuanfu** [comment]
Hmm, it is weird that this version deap module in your environement cannot find 'base' (I used the same version in my environment). Could you please reinstall deap and then try ` from deap import base, creator, tools, gp` in python shell?

**Comment by zhengxinvip** [comment]
> Hmm, it is weird that this version deap module in your environement cannot find 'base' (I used the same version in my environment). Could you please reinstall deap and then try ` from deap import base, creator, tools, gp` in python shell?

which version shoulid i reinstall, thanks

**Comment by weixuanfu** [comment]
Still `1.2.2`, the latest version.

**Comment by zhengxinvip** [comment]
i will try ,thanks.

**Comment by weixuanfu** [comment]
I closed this issue for now. Please feel free to reopen it if there is a update on this issue.

**Comment by jralha** [comment]
Was having the same problem.

My mistake, however, was naming my script tpot.py as an idiot haha
