### ISSUE TITLE
Why the training steps stop suddenly?

### ISSUE THREAD

**Issue by aeadod** [EpistasisLab/tpot#863]
![捕获](https://user-images.githubusercontent.com/33121476/57059681-f4654200-6ce8-11e9-9c86-0e166ed24c2a.PNG)
![捕获2](https://user-images.githubusercontent.com/33121476/57059740-32fafc80-6ce9-11e9-8159-28c63dfaef67.PNG)

**Comment by weixuanfu** [comment]
That it is `STATUS_STACK_BUFFER_OVERRUN (0xc0000409)` error. How large is RAM in your environment? It maybe due to out of memory.

**Comment by weixuanfu** [comment]
I closed this issue for now. Please feel free to reopen it if there is a update on this issue.
