### ISSUE TITLE
pareto front in first generation causes RuntimeError

### ISSUE THREAD

**Issue by jhmenke** [EpistasisLab/tpot#868]
A RuntimeError appears after a certain number of pipelines have already been successfully evaluated:

>RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly.

May be related to #849 

## Context of the issue

After running tpot for a data set and if some pipelines timeout (message: *Skipped pipeline #82 due to time out. Continuing to the next pipeline.*) there will be an error thrown because *self.optimized_pipeline* is *None* in https://github.com/EpistasisLab/tpot/blob/1387839b55cfee2e5f31465841582973f30b5ea1/tpot/base.py#L829

In my example, 94 (out of 100 for a generation, so we are in the first generation) pipelines have already been evaluated with two pipelines being stopped due to timeout. Then, in this code line
https://github.com/EpistasisLab/tpot/blob/1387839b55cfee2e5f31465841582973f30b5ea1/tpot/base.py#L824

the length of the zipped tuple will be 1 with the *pipeline_scores.wvalues[1]* being *-inf*. The condition is therefore not valid so *self.optimized_pipeline* is None.

Two possible problems:
- Why is the length of *self._pareto_front.items* 1? Is this only calculated after a first successful generation?
- Why is the fitness value *-inf*? 

## Process to reproduce the issue

The dataset used contains floats and ints as features and an int array as the target. tpot is run like this:
```
tpot = TPOTClassifier(generations=99, population_size=100, verbosity=3, n_jobs=3, periodic_checkpoint_folder="pipelines", scoring="f1")
tpot.fit(X_train, y_train)
```

The problem is triggered in the deap generation loop:
https://github.com/EpistasisLab/tpot/blob/1387839b55cfee2e5f31465841582973f30b5ea1/tpot/gp_deap.py#L236

I can provide the dataset privately if necessary to solve this issue. I would also be willing to solving this issue myself, but need additional guidance.

## Possible fix

the pareto front initialization should probably be different?

**Comment by jhmenke** [comment]
after considerable debugging, my scoring function is to blame.

**Comment by flowersw** [comment]
how was your scoring function to blame?

I'm running into something similar

**Comment by jhmenke** [comment]
> how was your scoring function to blame?
> 
> I'm running into something similar

Sorry, i'm not sure anymore. Maybe i was using scoring for binary classification in a multi-class classification problem or something like that. I remember having some issues with that.
