### ISSUE TITLE
Question about extracting models explored by TPOT that scored lower thant top

### ISSUE THREAD

**Issue by lmsanch** [EpistasisLab/tpot#872]
When finishing a TPOT based model, I was curious about the models explored. I found that using this:
`models_tested  = pd.DataFrame(tpot.evaluated_individuals_).transpose()`

If I sort this dataFrame by internal_cv_score, I can see the top model in index position 0, s well as the cv_score for other models tested. For example:

`models_tested.sort_values(['internal_cv_score'], ascending=False)[3:6]`

Returns this for models 3 to 6:
![Screen Shot 2019-05-28 at 11 29 32 AM](https://user-images.githubusercontent.com/3156487/58491314-c2ef6300-813c-11e9-8cda-5ffd2ddbebf0.png)

I can then select, for example, model 5 like this:
`models_tested.index[5]`
which returns the string:
`'LassoLarsCV(SelectPercentile(SelectFwe(LassoLarsCV(input_matrix, LassoLarsCV__normalize=True), SelectFwe__alpha=0.016), SelectPercentile__percentile=79), LassoLarsCV__normalize=True)'`

Is there a way to "convert" that model definition (str) into an actual model? Is there any function in TPOT that internally stored the fit method for that specific model to come up with its CV score?

**Comment by weixuanfu** [comment]
Please check the demo in issue #516 for converting the str to pipeline. 

For your 2nd question, TPOT did not save those fitted pipeline because it may make tpot object too big. So far TPOT only save the cv scores and other statistics of those evaluated pipeline.

**Comment by lmsanch** [comment]
Thank you. Very helpful and very quick feedback, your suggestion will definitely help; but I am thinking about forking the project and working on a utility to do what I want in my regression problem, leveraging regressor_config_dict in regressor.py.
Cheers
