### ISSUE TITLE
tpot how to choose feature selection operators?

### ISSUE THREAD

**Issue by ajoeajoe** [EpistasisLab/tpot#873]
randomly choose?

**Comment by weixuanfu** [comment]
In default setting, TPOT will randomly generate pipeline with or without feature selection operators in initial generation and then the best pipelines can include/exclude feature selection operators randomly via crossover/mutation in genetic programming.

**Comment by ajoeajoe** [comment]
I  asked this question because it seems that it can not see any feature selections operator in the last corresponding Python code TPOT exported. is it means that I must define the feature algorithm operators in the tpot_config setting, otherwise we won know if TPOT use any feature selections algorithm？

**Comment by weixuanfu** [comment]
You can check `evaluated_individuals_` attribute to find out if TPOT evaluated pipelines ( there is a similar question in comments of issue #870)
