### ISSUE TITLE
Partial fit

### ISSUE THREAD

**Issue by justusschock** [EpistasisLab/tpot#880]
Hi, I got a quick question: 
In your docs you're saying, that `tpot` is build upon `scikit-learn`. Since there are some models in scikit-learn which support iterable fitting (via `partial_fit`), I was wondering if this appproach could be applied here to? 

Can the `warm_start` argument be (kind of) missused for this or does this only apply to the already completely evaluated pipelines?

**Comment by weixuanfu** [comment]
TPOT does not support `partial_fit` and `warm_start` in TPOT is not for `partial_fit` but for reusing the population (evaluated pipelines) from previous calls to fit() instead of a random generated population.

**Comment by justusschock** [comment]
Thanks for clearing this up. I suppose there aren't any plans to support it in the (near) future?

**Comment by weixuanfu** [comment]
No, we don't have plan to support `partial_fit` so far. But any contributions are welcome.
