### ISSUE TITLE
Problem installing TPOT in Windows 10 - Python 3.7.

### ISSUE THREAD

**Issue by constiii** [EpistasisLab/tpot#883]
Hi, I have troubles installing TPOT on my local Windows 10 machine. I'm using Python 3.7. with Anaconda distribution.

Using the Anaconda prompt, I get the following error message:

```
(base) C:\Users\Peter>pip install tpot
Collecting tpot
  Using cached https://files.pythonhosted.org/packages/15/c8/46f5c7231f8e3088052cda78ed36198f9ded9f5a5edfc99290f31aa6b57e/TPOT-0.10.1-py3-none-any.whl
Requirement already satisfied: numpy>=1.12.1 in c:\users\peter\anaconda3\lib\site-packages (from tpot) (1.16.2)
Requirement already satisfied: pandas>=0.20.2 in c:\users\peter\anaconda3\lib\site-packages (from tpot) (0.24.2)
Requirement already satisfied: scipy>=0.19.0 in c:\users\peter\anaconda3\lib\site-packages (from tpot) (1.2.1)
Collecting deap>=1.0 (from tpot)
  Using cached https://files.pythonhosted.org/packages/59/1a/830bdaae9b629f1b7627eec5d0c4845fad83206d087fa0d896392451e64e/deap-1.3.0-cp37-cp37m-win_amd64.whl
Requirement already satisfied: scikit-learn>=0.18.1 in c:\users\peter\anaconda3\lib\site-packages (from tpot) (0.20.3)
Requirement already satisfied: tqdm>=4.26.0 in c:\users\peter\anaconda3\lib\site-packages (from tpot) (4.31.1)
Collecting stopit>=1.1.1 (from tpot)
  Using cached https://files.pythonhosted.org/packages/35/58/e8bb0b0fb05baf07bbac1450c447d753da65f9701f551dca79823ce15d50/stopit-1.1.2.tar.gz
    Error [WinError 87] Falscher Parameter while executing command python setup.py egg_info
Could not install packages due to an EnvironmentError: [WinError 87] Falscher Parameter

```

Any idea what I am doing wrong?

**Comment by weixuanfu** [comment]
Hmm, I didn't saw this error before. Could you please try ['--no-cache-dir'](https://pip.pypa.io/en/stable/reference/pip_install/#caching) option in `pip install`?

**Comment by constiii** [comment]
> Hmm, I didn't saw this error before. Could you please try ['--no-cache-dir'](https://pip.pypa.io/en/stable/reference/pip_install/#caching) option in `pip install`?

**Comment by constiii** [comment]
Same error unfortunately, but thank you!

**Comment by weixuanfu** [comment]
Hmm, sorry for overlooking this issue. Is this `EnvironmentError` fixed in your environment?

**Comment by weixuanfu** [comment]
There is no update about this issue for a while. Please feel free to reopen it if you have any questions or suggestions.

**Comment by CrystalFU** [comment]
you should make the domain name trusted. run the following code before you install tpot:
pip --trusted-host pypi.python.org --trusted-host pypi.org install --trusted-host files.pythonhosted.org  Active-SQLAlchemy==0.4.0

**Comment by constiii** [comment]
worked perfectly, thank you!
