### ISSUE TITLE
Update the library in IBM Watson studio

### ISSUE THREAD

**Issue by ELGUMOS** [EpistasisLab/tpot#885]
I am trying to update the joblib library inside the  IBM watson studio(jupyter notebook), some documentation suggests to use the pip install command but still no results.
Any suggestion?

**Comment by weixuanfu** [comment]
I don't think this is a TPOT-related question. Please resubmit this issue to [IBM watson support](https://cloud.ibm.com/login?redirect=%2Funifiedsupport%2Fsupportcenter)
