### ISSUE TITLE
Statistics during generational process

### ISSUE THREAD

**Issue by superaja** [EpistasisLab/tpot#892]
I have just started using TPOT and I think it is a phenomenal product. 
I am wondering if there is a way to access the CV and other stats during the generational process. I can get `evaluated_individual_` but that would be after the fit process. Any way, I can get the pipelines evaluated in each generation and their average CV  scores as it iterates through the generation during the fit process (tdqm bar during generation evaluation) ? 

Any guidance would be helpful.

**Comment by superaja** [comment]
I will re-ask the question after I do some more research. Closing now.

**Comment by weixuanfu** [comment]
You could try the `warm_start` parameter in TPOT API with generations=1 to check the test performance every generation. (Related issue #832 )

**Comment by superaja** [comment]
@weixuanfu - Thanks for the quick response. So let me confirm my understanding of your suggestion. Are you saying, I do the following instead of say setting `generations=10` during instantiation? 

`digits = load_digits()`
`X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, train_size=0.75, test_size=0.25)`

`pipeline_optimizer = TPOTClassifier(generations=1, population_size=20, cv=5,`
                                    `random_state=42, verbosity=2, warm_start=True)`
`for i in range(10): # where 10 is a proxy for gens`
   `  pipeline_optimizer.fit(X_train, y_train)`
   `  # get test performance stats `

**Comment by weixuanfu** [comment]
Yep, the demo looks good

**Comment by superaja** [comment]
Excellent - Thanks so much for quick responses. Will close this now.
