### ISSUE TITLE
TPOT Light is not telling me which model it actually used

### ISSUE THREAD

**Issue by ParthJawale1996** [EpistasisLab/tpot#900]
I'm trying to train a multi-class classification using TPOT Light and I stopped the optimization process at 5% just to see what's happening. 

`clf_tpot = TPOTClassifier(generations=5, population_size=20, cv=5, random_state=42, verbosity=3, scoring = "precision_micro", config_dict='TPOT light', max_eval_time_mins=300)
clf_tpot.fit(X_train, y_train)
`
This is my output:

TPOTClassifier(config_dict='TPOT light', crossover_rate=0.1, cv=5,
        disable_update_check=False, early_stop=None, generations=5,
        max_eval_time_mins=300, max_time_mins=None, memory=None,
        mutation_rate=0.9, n_jobs=1, offspring_size=None,
        periodic_checkpoint_folder=None, population_size=20,
        random_state=42, scoring='precision_micro', subsample=1.0,
        template=None, use_dask=False, verbosity=3, warm_start=False)

I'm able to evaluate it on my test set but this output doesn't tell me what the pipeline actually is, that I'm evaluating my results on.

**Comment by weixuanfu** [comment]
Please check [TPOT API](http://epistasislab.github.io/tpot/api/), the `fitted_pipeline_` attribute will show the pipeline. Also you could export the pipeline via `clf_tpot.export('xxx.py')` to python codes.
