### ISSUE TITLE
import classifier previously exported

### ISSUE THREAD

**Issue by pdeman** [EpistasisLab/tpot#902]
Hi,
I am using tpot to generate a classifier:
```
tpot = TPOTClassifier(generations=30, population_size=30, n_jobs= -1,verbosity=2,cv=5, periodic_checkpoint_folder="/home",scoring="recall_micro")
    tpot.fit(X_train, y_train)
    ypredict=tpot.predict(X_test)
    conf_matrix = confusion_matrix(y_test,ypredict)
    tn, fp, fn, tp = conf_matrix.ravel()
    print(conf_matrix)    
    print(tpot.score(X_test, y_test))
    tpot.export('tpot_pipeline.py')
```

is there a way to reimport the classifier from the python file ?
like 
`tpot.import("tpot_pipeline.py") ?`
I haven't found such method.

like joblib dump and load in sckikit-learn

**Comment by weixuanfu** [comment]
TPOT don't support this import function yet. I think it should be a interesting function which TPOT may support later.

**Comment by pdeman** [comment]
ok. for now I kind of do the job by doing this after the export:
```
tpot.export('tpot_pipeline_%s.py'%(_scoring))
f = open("tpot_pipeline_%s.py"%(_scoring),"a+")
f.write("from sklearn.externals import joblib\n")
f.write("import os\n")
f.write("joblib.dump(exported_pipeline,os.path.basename(__file__).replace(".py",".pkl"))\n")
```

**Comment by weixuanfu** [comment]
Maybe pickling `tpot_obj.fitted_pipeline_` (which is fitted scikit-learn pipeline) is better. (Related to this issue #520)

**Comment by pdeman** [comment]
ok perfect thanks
