### ISSUE TITLE
Custom scoring with scorer object not implemented

### ISSUE THREAD

**Issue by limlug** [EpistasisLab/tpot#906]
The API documentation reads:

> You can pass the callable object/function with signature scorer(estimator, X, y), where estimator is trained estimator to use for scoring, X are features that will be passed to estimator.predict and y are target values for X. To do this, you should implement your own function. See the example below for further explanation.

This is currently not implemented despite sklearn.model_selection.cross_val_score supporting scorer objects just fine.

## Process to reproduce the issue

1. User creates TPOT instance with scoring=scorer(estimator, X, y)
2. User calls TPOT `fit()` function with training data
3. TPOT crashes with a `KeyError` for scorer = SCORERS[scoring]

## Possible fix

The case selection for the scoring in TPOTBase needs to be extended to check if not only is a function passed with signature y_pred, y_true but also with estimator, X, y.

**Comment by weixuanfu** [comment]
Thank you for reporting this issue! TPOT will deprecate the scoring function with signature `y_pred, y_true` in version 0.11 (as mentioned [here](https://github.com/EpistasisLab/tpot/blob/master/tpot/base.py#L347-L350)) and then the scoring-related function in TPOT should be fixed and simplified by using [`check_scoring`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.check_scoring.html) function from sklearn. Contribution is welcome!

**Comment by weixuanfu** [comment]
The issue has been fixed in new version of TPOT (v0.11.0). Please feel free to reopen it if you have any questions or suggestions.
