### ISSUE TITLE
Column Mismatch ---- Output in Tpot

### ISSUE THREAD

**Issue by pratik-poudel** [EpistasisLab/tpot#910]
After fitting the 
TPOTClassifier(verbosity=3,  
                    random_state=55, 
                    #scoring=rmsle,
                    periodic_checkpoint_folder="intermediate_results",
                    n_jobs=-1, 
                    warm_start = True,
                    generations=20, 
                    population_size=80,
                    early_stop=8)
column mismatch :
expected V233, C1, V87, V195, C14, D11, D5, V128, V45, V187, TransactionID, D2, V312, V317, D15, card5, card1, V308, D1, V259, D4, V199, V257, V314, V127, V217, V318, V258, V307, C2, V188, C6, addr1, dist1, V131, card2, V189, V44, V200, TransactionAmt, C11, V315, V190, C13, V310, V246, V201, V244, TransactionDT, D10 in input data
training data did not have the following fields: f32, f15, f38, f0, f26, f30, f16, f45, f27, f19, f34, f46, f39, f4, f29, f8, f14, f36, f40, f42, f10, f43, f3, f12, f41, f22, f2, f11, f17, f33, f1, f9, f35, f13, f21, f37, f44, f48, f47, f18, f25, f31, f5, f7, f49, f20, f28, f23, f6, f24.

These fields ( f32, f15, f38, f0, f26, f30, f16, f45, f27, f19, f34, f46, f39, f4, f29, f8, f14, f36, f40, f42, f10, f43, f3, f12, f41, f22, f2, f11, f17, f33, f1, f9, f35, f13, f21, f37, f44, f48, f47, f18, f25, f31, f5, f7, f49, f20, f28, f23, f6, f24.) are not in any data
![error](https://user-images.githubusercontent.com/37284545/64047424-77f74880-cb8e-11e9-9329-fcc43de87c72.png)

**Comment by weixuanfu** [comment]
Hmm, I did not have this error before. Maybe converting your input dataset from `pd.DataFrame` to `np.ndarray` can help.

Could you please provide more details about this issue, like a demo for reproducing it?

**Comment by pratik-poudel** [comment]
got it
