### ISSUE TITLE
Question: Is there a reason that MLPClassifier is not included?

### ISSUE THREAD

**Issue by jhmenke** [EpistasisLab/tpot#912]
I was wondering why the sklearn MLPClassifier is not included in the default config. 

I was noticing why tpot never picked it since in some other optimization that classifier outperformed the others, but not in tpot. Then i noticed it's not even included. Were there specific reasons why someone should avoid it?

**Comment by weixuanfu** [comment]
`MLPClassifier` is very computational intensive for some parameter combinations, which is main reason we did not include it into default setting of TPOT.

**Comment by jhmenke** [comment]
Thanks!

For anyone finding this topic later. You can integrate MLPClassifier easily by adding it to the config:

```
def mlp_layer_conf():
    return tuple(np.random.randint(5, 100) for _ in range(np.random.randint(1, 5)))


'sklearn.neural_network.MLPClassifier': {
    'hidden_layer_sizes': [mlp_layer_conf()],
    'solver': ['sgd', 'adam'],
    'alpha': [0.0001, 0.001, 0.005, 0.01, 0.05],
    'learning_rate': ['constant', 'adaptive'],
    'max_iter': [100, 200, 500, 1000, 2000, 5000],
    'activation': ['tanh', 'logistic', 'relu'],
    'early_stopping': [True, False],
    'learning_rate_init': [1e-4, 5e-4, 1e-3],
    'validation_fraction': [0.1, 0.15, 0.2, 0.25],
    'n_iter_no_change': [3, 5, 10, 20]
    }
```
