### ISSUE TITLE
How to use LeaveOneOut cross validation inside TPOT? 

### ISSUE THREAD

**Issue by maksimovkonstantin** [EpistasisLab/tpot#913]
Hi! 

Is it possible to use LeaveOneOut inside tpot for parameters optimization?

**Comment by weixuanfu** [comment]
I think you may easily use `LeaveOneOut` via setting `cv=LeaveOneOut()` within `TPOTClassifier` or `TPOTRegessor`. (see [TPOT API](http://epistasislab.github.io/tpot/api/) for details)
