### ISSUE TITLE
custom scorer does not work with n_jobs > 1 and use_dask=False

### ISSUE THREAD

**Issue by jhmenke** [EpistasisLab/tpot#914]
A custom scorer works fine with n_jobs=1, but raises an Exeption with n_jobs > 1, because the scorer was not added to SCORERS

## Process to reproduce the issue

See above

## Expected result

The optimization continues as usual

## Current result

The new scorer is not added to SCORERS

## Possible fix

I would guess that due to the multiprocessing the SCORERS variable, where the new scorer is correctly added for the main process, the imports in the new processes refer to the original SCORERS in the metrics.py file

But i'm not sure how to elegantly solve this issue. A workaround is to statically add the custom scorer in metrics.py

**Comment by weixuanfu** [comment]
Thank you for reporting this issue. I think maybe a better workaround is not to SCORERS for custom scorer ([related codes](https://github.com/EpistasisLab/tpot/blob/master/tpot/base.py#L320-L359)) but pass the scorer directly to [`_wrapped_cross_val_score`](https://github.com/EpistasisLab/tpot/blob/master/tpot/gp_deap.py#L382-L418). 

BTW, I am on vacation those days and will work on this issue later. But contribution is welcome.

**Comment by jhmenke** [comment]
If it's okay to not user SCORERS in that case i might be able to fix it over the weekend.
