### ISSUE TITLE
My graphs and charts is empty

### ISSUE THREAD

**Issue by tXambe** [EpistasisLab/tpot#915]
Hello,

I just installed TPOT v19.03 in the dasboard everything are empty. I open the ports in the firewall
but I don't now what I can do.

    What version of the OS are you currently using lsb_release -a and uname -a?
    **5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux**
    What T-Pot version are you currently using?
    19.03
    What edition (Standard, Nextgen, etc.) of T-Pot are you running?
    Standard
    What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
    Vmware
    Did you have any problems during the install? If yes, please attach /install.log /install.err.
    No
    How long has your installation been running?
    24 Hours
    Did you install upgrades, packages or use the update script?
    No
    Did you modify any scripts or configs? If yes, please attach the changes.
    Please provide a screenshot of glances and htop.
    
    How much free disk space is available (df -h)?
    Filesystem      Size  Used Avail Use% Mounted on
    udev            3.9G     0  3.9G   0% /dev
    tmpfs           782M   21M  761M   3% /run
    /dev/sda2       149G   22G  120G  16% /
    tmpfs           3.9G     0  3.9G   0% /dev/shm
    tmpfs           5.0M     0  5.0M   0% /run/lock
    tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
    tmpfs           782M     0  782M   0% /run/user/1000

    What is the current container status (dps.sh)?
     Don't run -->  dps.sh: command not found
    What is the status of the T-Pot service (systemctl status tpot)?
     running
    What ports are being occupied? Stop T-Pot systemctl stop tpot and run netstat -tulpen
    (Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          16152      -
tcp        0      0 0.0.0.0:61209           0.0.0.0:*               LISTEN      0          16830      -
tcp6       0      0 :::64294                :::*                    LISTEN      0          13517      -
tcp6       0      0 :::64295                :::*                    LISTEN      0          16163      -
udp        0      0 192.168.100.34:123      0.0.0.0:*                           0          15935      -
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          15933      -
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          15929      -
udp6       0      0 :::123                  :::*                                0          15926      -

    If a single container shows as DOWN you can run docker logs <container-name> for the latest log entries

Thanks and greeting

**Comment by weixuanfu** [comment]
I think this issue should be posted in this repo: https://github.com/dtag-dev-sec/tpotce.
