### ISSUE TITLE
Can anyone teach me how to use my dataset +tpot to find the best model,

### ISSUE THREAD

**Issue by yuxiaomu** [EpistasisLab/tpot#934]
I now have a slab map of the steel mill, I want to identify the slab number, but I will not use this code, any help Would be greatly appreciated, I am a newbie, really awkward, if you can please add me WeChat love_qinging

[not necessary, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by weixuanfu** [comment]
Is those [examples](http://epistasislab.github.io/tpot/examples/) helpful for the usage of TPOT on your dataset?

**Comment by gosuto-inzasheru** [comment]
Hello this is not a bar or cafe! This section is for reporting issues you encounter while working with this module.

**Comment by yuxiaomu** [comment]
It’s weird to talk to you.@jorijnsmit

**Comment by weixuanfu** [comment]
It seems not a TPOT-related issue now. Please use the proper issue title and also provide detailed description for resubmitting a issue.
