### ISSUE TITLE
suggestion for more intuitive use of parameter max_time_mins

### ISSUE THREAD

**Issue by jhmenke** [EpistasisLab/tpot#936]
Right now the logic is:

*generations* > 1 and *max_time_mins*=None --> tpot will run for *generations*
*generations* > 1 and *max_time_mins* > 0 --> tpot will run for ~*max_time_mins* minutes and ignore generations

However, if both *generations* and *max_time_mins* are defined, i would expect both to be a limiting factor. E.g, if generations is reached and the time is not up, stop regardless. The other way around, if generations is not reached but the time is up, tpot should be stopped.

What do you think about this proposal? I think it would be more intuitive if no parameter is just ignored.
That would also mean:

*generations*=None and *max_time_mins* > 0 --> tpot will run for *max_time_mins* minutes

**Comment by weixuanfu** [comment]
I like this proposal and I think it's more logical.

**Comment by weixuanfu** [comment]
The issue has been fixed in a new version of TPOT (v0.11.0). Please feel free to reopen it if you have any questions or suggestions.
