### ISSUE TITLE
.export() to something else than a file

### ISSUE THREAD

**Issue by gosuto-inzasheru** [EpistasisLab/tpot#938]
Sometimes running this library on hosted instances instead of local machines, the process of exporting to `.py` file is not always optimal. I might not have access to file output or they can get wiped after closing sessions.

An alternative way of reporting the best performing pipeline so far would be via stdout. For example, whenever a new best performing pipeline is found during the fitting process, a simple output of the `make_pipeline([...])` and its performance measure would suffice.

Is there something I am missing that already makes this possible? I could not find anything in the documentation in regards to the `.export()` function besides that [it takes a string as a parameter for the output file](https://epistasislab.github.io/tpot/api/#tpotclassifier-export).

**Comment by gosuto-inzasheru** [comment]
Found a demo code block by @weixuanfu at https://github.com/EpistasisLab/tpot/issues/337#issuecomment-470681480. I think adding a flag to `.export()` which would run something along the lines of that demo and thus print the `generate_pipeline_code` to screen instead of to file would be exactly what I am looking for!

Edit: Actually, this might be as simple as setting a boolean flag which would print to screen instead of to file.

**Comment by weixuanfu** [comment]
The issue has been fixed in a new version of TPOT (v0.11.0). Please feel free to reopen it if you have any questions or suggestions.
