### ISSUE TITLE
How can I use my own data to train an optimal network model? My data set is like this: picture +txt, where the number of txt and picture is the same, each txt holds the label of the corresponding picture.

### ISSUE THREAD

**Issue by yuxiaomu** [EpistasisLab/tpot#942]

**Comment by 1810325** [comment]
Any tips will be greatly appreciated, because I really remember to make it.

**Comment by yuxiaomu** [comment]
Any tips will be greatly appreciated, because I am really eager to make it.

**Comment by weixuanfu** [comment]
It seems not a TPOT-related issue. Please use the proper issue title and also provide detailed description for resubmitting a issue.
