### ISSUE TITLE
Can you tell me the reason why the following error occurred while I was running titanic data

### ISSUE THREAD

**Issue by yuxiaomu** [EpistasisLab/tpot#947]
![image](https://user-images.githubusercontent.com/47933430/68183486-90913e00-ffd7-11e9-8179-5e07807426e0.png)
Traceback (most recent call last):
  File "/home/yyk/PycharmProjects/untitled1/jinhua/tpot-master/tutorials/tpot_titanic_pipeline.py", line 7, in <module>
    tpot_data = np.recfromcsv('/home/yyk/PycharmProjects/untitled1/jinhua/tpot-master/tutorials/data/titanic_train.csv', delimiter='COLUMN_SEPARATOR', dtype=np.float64)
  File "/opt/anaconda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 2322, in recfromcsv
    output = genfromtxt(fname, **kwargs)
  File "/opt/anaconda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 2205, in genfromtxt
    output = np.array(data, dtype)
ValueError: could not convert string to float: b'1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,,S'

**Comment by weixuanfu** [comment]
We are updating our docs now.

Please update the expected codes in the screenshot based on the demo below:

```python
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# NOTE: Make sure that the class is labeled 'target' in the data file
tpot_data = pd.read_csv('PATH/TO/DATA/FILE', sep='COLUMN_SEPARATOR', dtype=np.float64)
features = tpot_data.drop('target', axis=1)
training_features, testing_features, training_classes, testing_classes = \
    train_test_split(features, tpot_data['class'], random_state=None)

exported_pipeline = RandomForestClassifier(bootstrap=False, max_features=0.4, min_samples_leaf=1, min_samples_split=9)

exported_pipeline.fit(training_features, training_classes)
results = exported_pipeline.predict(testing_features)

```

**Comment by weixuanfu** [comment]
Also, the exported code is just an example and you should also update the data processioning before `exported_pipeline = ...` based on this [Jupyter notebook](https://github.com/EpistasisLab/tpot/blob/master/tutorials/Titanic_Kaggle.ipynb)
