### ISSUE TITLE
Using "memory="C:/memdir/"" with dask distributed

### ISSUE THREAD

**Issue by rjstange** [EpistasisLab/tpot#959]
Does only the machine with the scheduler have the joblib memory data stored locally, while the other worker machines send the scheduler machine their own joblib info of completed work to be stored on the scheduler's hard drive?

I hope I am phrasing this question properly. I am about to foray into using Dask Distributed with my two desktops and want to make sure that the worker desktop is not going to be storing away the same data that my scheduler/worker machine is, mostly since my worker machine does not have room for hundreds of gigabytes.

**Comment by weixuanfu** [comment]
Yes, I think it should be stored on your scheduler's hard drive.
