### ISSUE TITLE
max_time_mins fails to function in some scenarios

### ISSUE THREAD

**Issue by jrm5100** [EpistasisLab/tpot#966]
There are certain scenarios where the _max_time_mins_ parameter is ignored.  I believe it depends on the data, TPOT configuration, population size, and value of _max_time_mins_.

## Context of the issue

I am working on creating pipelines using a TPOTRegressor.  I wanted to test performance across different population/generation sizes to find suitable values for running a full analysis (balancing performance and runtime).  Initially I was thinking something like 4 different population sizes and 4 different values for the number of generations.  Rather than creating 16 runs, I realized I could simply use the max_time_mins parameter to run for some amount of time and then check the performance of pipelines saved to the _periodic_checkpoint_folder_.

I have three different outputs that I am looking at using the same input features.  Therefore I set up scripts to run TPOT for 24 hours per output, using four different population sizes.  

## Process to reproduce the issue

I was using the tpot-light configuration and a template (FeatureSetSelector-Transformer-Regressor).

I haven't been able to reproduce this in a shorter scenario (for example, I tried using a population size of 20 and limiting the run to an hour).  My assumption is that repeating it should be possible with a small population size and large max_time_mins parameter, but using a simple configuration (so that there aren't many possible pipelines) or some specific kind of data may also be helpful.

## Expected result

Like the 1000 population run, the smaller population sizes should have stopped optimization at or shortly after hitting the 24 hour (1440 minute) mark.

## Current result

Using a population size of 1000 worked as expected.  Running the same scripts with 100, 250, or 500 as the population size resulted in TPOT continuing to evaluate the first output, ignoring the max_time_mins parameter.

|   Run   	| Last saved checkpoint generation 	|  Last saved checkpoint time 	| Total Generations 	| Stopped? 	|
|:-------:	|:--------------------------------:	|:---------------------------:	|:-----------------:	|:--------:	|
|  100pop 	|                39                	|          58 minutes         	|        6439       	|    No    	|
|  250pop 	|                35                	|         131 minutes         	|        2015       	|    No    	|
|  500pop 	|                24                	|         199 minutes         	|        820        	|    No    	|
| 1000pop 	|                44                	|         620 minutes         	|        102        	|    Yes   	|

## Possible fix

The `_stop_by_max_time_mins()` method is only run inside of a `for sklearn_pipeline in sklearn_pipeline_list:` loop.  My guess is that `sklearn_pipeline_list` is empty in later generations and the method isn't run.

Notably, the TPOTRegressors that failed to stop running were not seeing any improvement when the time limit would have been reached- no checkpoint pipelines were saved recently and the _Current best internal CV score_ was not changing.  The progress bars showed 100% progress immediately in each generation:

Early generations:
```
Optimization Progress: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 200/200 [02:19<00:00,  6.29s/pipeline]
Optimization Progress: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 200/200 [03:14<00:00,  5.44s/pipeline]
Optimization Progress:  67%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‹   | 202/300 [03:29<09:43,  5.96s/pipeline]
Optimization Progress:  81%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  | 242/300 [03:39<04:06,  4.25s/pipeline]
Optimization Progress:  94%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–| 282/300 [03:50<00:54,  3.05s/pipeline]
```

Later generations:
```
Optimization Progress: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 101600/101600 [14:42:19<00:00, 17.19s/pipeline]
Optimization Progress: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 101600/101600 [14:43:06<00:00, 12.17s/pipeline]
                                                                                       

Optimization Progress: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 101700/101700 [14:43:06<00:00, 12.17s/pipeline]
Optimization Progress: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 101700/101700 [14:43:55<00:00,  8.67s/pipeline]
                                                                                       

Optimization Progress: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 101800/101800 [14:43:55<00:00,  8.67s/pipeline]
Optimization Progress: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 101800/101800 [14:44:43<00:00,  6.21s/pipeline]
```

**Comment by weixuanfu** [comment]
Thank you for reporting this issue.

As you found it in this issue, max_time_mins may not stop by end of the time since TPOT only checks how many seconds it has used once a pipeline evaluation is done (or a chunk of pipelines is done if n_jobs != 1). So TPOT cannot interrupt pipeline evaluation even the max_time_mins limit is reached. 

I think we should refine this function of TPOT.

**Comment by weixuanfu** [comment]
In this case TPOT ran with a limited search space and template. So the `sklearn_pipeline_list` can be empty for prevent  the `_stop_by_max_time_mins()` from running even after the time limit.

I will push a patch to dev branch soon.

**Comment by weixuanfu** [comment]
@jrm5100 I pushed the PR #967 with a quick demo for testing this issue. And I will merge it to development branch soon. 

you may install TPOT with patch into an environment via:

```shell
pip install --upgrade --no-deps --force-reinstall git+https://github.com/EpistasisLab/tpot.git@development
```

**Comment by jrm5100** [comment]
This fix resolved the issue for me.

**Comment by weixuanfu** [comment]
The issue was fixed in the latest version of TPOT, thus I closed this issue. Please feel free to reopen this issue if you have any questions.

**Comment by pratik-poudel** [comment]
With  max_time_mins of 300 and generations=100, population_size=100, tpot has been running for over 5 hours already.  I installed it today and the version is '0.11.1'.
Do i have to install the patch for this to be working ?
