### ISSUE TITLE
Optimization always get stuck at the same place

### ISSUE THREAD

**Issue by smrutib2017** [EpistasisLab/tpot#969]
Hi, I am using TPot to create a pipeline for a time-series based classification project. The data involved is not huge (4000*100 matrix size). I am running on a Debian Linux platform.

When I run the fit operation, my optimization gets stuck at the same point. i.e. whatever CV score I get in the first generation doesn't ever change and the model that's picked always remains the same even if I change the data. I have attached the screenshot below.

Based on what I have read on these forums these are the things I have tried.

- Made sure I am passing numpy arrays of the correct dimension to fit

_**     
ipdb> type(features_train.values)
<class 'numpy.ndarray'>
ipdb> np.shape(features_train.values)
(1305, 61)
ipdb> type(labels_train.values)
<class 'numpy.ndarray'>
ipdb> np.shape(labels_train.values)
(1305,)
**_
- Made sure there are no NaNs in my data

- Tried increasing population_size. I was using defaults for generations and population_size.
   

>  

    tscv = TimeSeriesSplit(n_splits=5)
    train_test = tscv.split(features_train)

    tpot = TPOTClassifier(verbosity=3, 
                          scoring="accuracy", 
                          cv=train_test,
                          random_state=RANDOM_STATE, 
                          periodic_checkpoint_folder="tpotout",
                          n_jobs=1)

    tpot.fit(features_train.values, labels_train.values)

    print(tpot.score(features_test.values, labels_test.values))

    tpot.export('tpot_pipeline_' + filetag + '.py')

    probs = pd.DataFrame(tpot.predict_proba(features_test.values), index=features_test.index)
    probs.to_csv('AutoTPotProbs_' + filetag + '.csv')

I suspect, this has something to do with the type of data I am using. Maybe the error messages in the screenshot will shed some light?

![image](https://user-images.githubusercontent.com/58296354/69808938-98ac5a00-11e0-11ea-908f-47ccad6007f6.png)

**Comment by weixuanfu** [comment]
Hi, it seems a issue about cv parameter . Could you please try `cv=TimeSeriesSplit(n_splits=5)` instead?

**Comment by smrutib2017** [comment]
That worked like a charm. Thanks so much for your help.

This also fixed an error that was preventing me from using multiple cores. There was a pickling error which has gone away after this fix.
Thanks
