### ISSUE TITLE
Scoring method verification should be updated

### ISSUE THREAD

**Issue by gatl** [EpistasisLab/tpot#985]
Since the scikit-learn changed a bit their API with version 22, scorer objects are no longer defined at `sklearn.metrics.scorer` but on `sklearn.metrics` (that is where `make_scorer()` is defined now).

In light of this, tpot's method of distinguishing between metrics and scorers (checking the name of the module in which they were defined) is no longer working correctly since it rejects all scoring objects in the new scikit-learn version. As such, I would recommend that the code that does this verification be revised for the next release.

**Comment by weixuanfu** [comment]
Thank you for the suggestion. It is related to the issue #981 and it should be fixed in next version of TPOT.

**Comment by gatl** [comment]
Yes it is, but I decided to report this anyway to ensure you were aware of this aspect too.
Thank you for your attention. It will be a bit of work but your effort is well appreciated.

**Comment by weixuanfu** [comment]
The issue was fixed in the latest version of TPOT, thus I closed this issue. Please feel free to reopen this issue if you have any questions.

**Comment by gatl** [comment]
Works great! Thank you for your effort.
