### ISSUE TITLE
ImportError: Error: could not import sklearn.cluster.FeatureAgglomeration. cannot import name 'lobpcg'

### ISSUE THREAD

**Issue by shapatel13** [EpistasisLab/tpot#991]
[TPOT working previously but giving me this error now]

## Context of the issue

from tpot import TPOTClassifier

tpot = TPOTClassifier(generations=1, population_size=50, max_time_mins=120, verbosity=3)

tpot.fit(X_train,y_train)

[the remaining entries are only necessary if you are reporting a bug]

## Process to reproduce the issue

[ordered list the process to finding and recreating the issue, example below]

1. User creates TPOT instance
2. User calls TPOT `fit()` function with training data
3. TPOT crashes with a `KeyError` after 5 generations

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you currently experience from this process, and thereby explain the bug]

## Possible fix

[not necessary, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by weixuanfu** [comment]
Please reopen this issue with codes and more details for reproducing this error.

**Comment by weixuanfu** [comment]
Could you please let me know the version of scikit-learn in your environment? you may need update scikit-learn to v0.22

**Comment by weixuanfu** [comment]
I just googled a related issue in [this link](https://github.com/slundberg/shap/issues/957) and it seemed that something was messed up in your sklearn install.

**Comment by shapatel13** [comment]
> Could you please let me know the version of scikit-learn in your environment? you may need update scikit-learn to v0.22

Hi the version is 
Requirement already satisfied, skipping upgrade: scikit-learn>=0.22.0 in /usr/local/lib/python3.6/dist-packages (from tpot) (0.22.1)

**Comment by weixuanfu** [comment]
Hmm, somehow I cannot install  scikit-learn v0.22.1 via conda (maybe because it was released yesterday) into my environment for testing this issue. I tested it with scikit-learn 0.22 but no error showed up. Could you please build a clean conda environment with scikit-learn 0.22 for testing it again? I am not sure if it is installation issue of scikit-learn.

**Comment by shapatel13** [comment]
hello i am using google colab so not a conda environment.

**Comment by weixuanfu** [comment]
Hmm, I just used google colab for a quick test and no error showed up too. Please check this [link](https://colab.research.google.com/gist/weixuanfu/addbba317679a10a405512c20f58317b/issue991.ipynb)

**Comment by shapatel13** [comment]
So weird, i cut and paste exactly what you put into my colab and i get
an error.

Requirement already satisfied: tpot in
/usr/local/lib/python3.6/dist-packages (0.11.1)
Requirement already satisfied: scikit-learn>=0.22.0 in
/usr/local/lib/python3.6/dist-packages (from tpot) (0.22.1)
Requirement already satisfied: pandas>=0.24.2 in
/usr/local/lib/python3.6/dist-packages (from tpot) (0.25.3)
Requirement already satisfied: update-checker>=0.16 in
/usr/local/lib/python3.6/dist-packages (from tpot) (0.16)
Requirement already satisfied: stopit>=1.1.1 in
/usr/local/lib/python3.6/dist-packages (from tpot) (1.1.2)
Requirement already satisfied: numpy>=1.16.3 in
/usr/local/lib/python3.6/dist-packages (from tpot) (1.17.4)
Requirement already satisfied: deap>=1.2 in
/usr/local/lib/python3.6/dist-packages (from tpot) (1.3.0)
Requirement already satisfied: scipy>=1.3.1 in
/usr/local/lib/python3.6/dist-packages (from tpot) (1.3.3)
Requirement already satisfied: joblib>=0.13.2 in
/usr/local/lib/python3.6/dist-packages (from tpot) (0.14.1)
Requirement already satisfied: tqdm>=4.36.1 in
/usr/local/lib/python3.6/dist-packages (from tpot) (4.41.1)
Requirement already satisfied: pytz>=2017.2 in
/usr/local/lib/python3.6/dist-packages (from pandas>=0.24.2->tpot)
(2018.9)
Requirement already satisfied: python-dateutil>=2.6.1 in
/usr/local/lib/python3.6/dist-packages (from pandas>=0.24.2->tpot)
(2.6.1)
Requirement already satisfied: requests>=2.3.0 in
/usr/local/lib/python3.6/dist-packages (from
update-checker>=0.16->tpot) (2.21.0)
Requirement already satisfied: six>=1.5 in
/usr/local/lib/python3.6/dist-packages (from
python-dateutil>=2.6.1->pandas>=0.24.2->tpot) (1.12.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in
/usr/local/lib/python3.6/dist-packages (from
requests>=2.3.0->update-checker>=0.16->tpot) (1.24.3)
Requirement already satisfied: idna<2.9,>=2.5 in
/usr/local/lib/python3.6/dist-packages (from
requests>=2.3.0->update-checker>=0.16->tpot) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in
/usr/local/lib/python3.6/dist-packages (from
requests>=2.3.0->update-checker>=0.16->tpot) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in
/usr/local/lib/python3.6/dist-packages (from
requests>=2.3.0->update-checker>=0.16->tpot) (2019.11.28)



from tpot import TPOTClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np

iris = load_iris()
X_train, X_test, y_train, y_test =
train_test_split(iris.data.astype(np.float64),
    iris.target.astype(np.float64), train_size=0.75, test_size=0.25,
random_state=42)

tpot = TPOTClassifier(generations=5, population_size=50, verbosity=3,
random_state=42)
tpot.fit(X_train, y_train)



else:
---> 80             exec('from {} import {}'.format(import_str,
op_str))     81         op_obj = eval(op_str)


------------------------------
9 frames
------------------------------

ImportError: cannot import name 'lobpcg'

During handling of the above exception, another exception occurred:


ImportError                               Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/tpot/operator_utils.py
<https://localhost:8080/#> in source_decode(sourcecode, verbose)
82     except Exception as e:     83         if verbose > 2:
---> 84             raise ImportError('Error: could not import
{}.\n{}'.format(sourcecode, e))     85         else:     86
 print('Warning: {} is not available and will not be used by
TPOT.'.format(sourcecode))


ImportError: Error: could not import sklearn.cluster.FeatureAgglomeration.
cannot import name 'lobpcg'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------

**Comment by shapatel13** [comment]
Okay I just opened a new notebook, and it is working now.  thank you for your help!
